"""MSC V1 world: the #115 factorized KnowledgeSpace population, stream and ground truth.

The population is generated by the PRODUCTION ``ocm.kso.checks.random_space`` generator
(parameterized, salt-seeded) -- not a generator authored for this study. Two hostile twin
blocks are planted for the mandatory FQ-5 hostile; they are adversarial to the quotient
mechanism, not to the parent arms, and are declared planted in the protocol.

Ground truth for every decision is production ``gated_closure``. Nothing in this module is
arm-specific; every arm replays the identical frozen stream.

Python 3.8-compatible syntax; imports production ocm.kso (3.10+ at runtime).
"""
from __future__ import annotations

import hashlib
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO / "src"))

from ocm.kso import checks as prod_checks  # noqa: E402
from ocm.kso.navigation import gated_closure, ungated_closure  # noqa: E402
from ocm.kso.space import Atom, Hyperedge, KnowledgeSpace  # noqa: E402
from ocm.kso.types import Authority  # noqa: E402
from ocm.kso.warrant import WarrantProfile  # noqa: E402

SALT_POPULATION = "ocm-q216-msc-v1-20260909/pop-01"
SALT_TASKS = "ocm-q216-msc-v1-20260909/tasks-02"
SALT_UPDATES = "ocm-q216-msc-v1-20260909/updates-03"
SALT_HOSTILE = "ocm-q216-msc-v1-20260909/hostile-04"
SALT_QREF = "ocm-q216-msc-v1-20260909/qref-05"

CUSTODY = "custody"

RELS = ("DEPENDENCE", "SUPPORT", "CONSTRAINT", "RESTRICTION",
        "EMBEDDING", "SCALE_CHANGE", "BOUNDARY_CHANGE",
        "REPRESENTATION_TRANSPORT", "DECISION_TRANSPORT", "COMPOSITION")


def stable_seed(salt: str) -> int:
    return int(hashlib.sha256(salt.encode("utf-8")).hexdigest(), 16) % (2 ** 32)


# ---------------------------------------------------------------------------
# Population: production generator, scaled. Hostile twins planted on top.
# ---------------------------------------------------------------------------

def build_field(n_atoms: int = 480, n_edges: int = 1280, n_evidence: int = 24,
                salt: str = SALT_POPULATION) -> Tuple[KnowledgeSpace, Dict[str, object]]:
    """The persistent field F: production random_space, scaled, plus two planted twin blocks.

    The twin blocks are the FQ-5 hostile substrate (QG-30 witness class): two members with
    identical decision-relevant coordinates (type, warrant, quarantined, outgoing signature)
    that differ ONLY in the discarded authority coordinate ``custody``.
    """
    rng = random.Random(stable_seed(salt))
    ks = prod_checks.random_space(rng, n_atoms=n_atoms, n_edges=n_edges, n_evidence=n_evidence)
    planted = []
    atoms = list(ks.atoms)
    edges = list(ks.hyperedges)
    for h in range(2):
        seed_id = "h%d_seed" % h
        tgt_id = "h%d_target" % h
        tw_a = "h%d_tw_a" % h
        tw_b = "h%d_tw_b" % h
        twin_warrant = WarrantProfile.certified([frozenset(["hostile_ev_%d" % h])])
        atoms.append(Atom(seed_id, "query_seed"))
        atoms.append(Atom(tgt_id, "claim"))
        # twins: same type, same warrant, same quarantined. custody assigned by hostile_field().
        atoms.append(Atom(tw_a, "claim", twin_warrant, authority=Authority.of(**{CUSTODY: 2})))
        atoms.append(Atom(tw_b, "claim", twin_warrant))
        edges.append(Hyperedge("h%d_e_in_a" % h, (seed_id,), (tw_a,), "SUPPORT"))
        edges.append(Hyperedge("h%d_e_in_b" % h, (seed_id,), (tw_b,), "SUPPORT"))
        edges.append(Hyperedge("h%d_e_out_a" % h, (tw_a,), (tgt_id,), "SUPPORT"))
        edges.append(Hyperedge("h%d_e_out_b" % h, (tw_b,), (tgt_id,), "SUPPORT"))
        planted.append({"seed": seed_id, "target": tgt_id, "twins": [tw_a, tw_b],
                        "evidence": "hostile_ev_%d" % h})
    field = KnowledgeSpace(tuple(atoms), tuple(edges))
    meta = {"salt": salt, "n_atoms": len(field.atoms), "n_edges": len(field.hyperedges),
            "planted": planted,
            "evidence_universe": sorted(str(x) for x in field.evidence_universe())}
    return field, meta


def hostile_pair(field: KnowledgeSpace, planted: List[Dict[str, object]]) -> Tuple[KnowledgeSpace, KnowledgeSpace]:
    """F_A: custody on twin a. F_B: custody moved to twin b. Everything else identical.

    The two fields have isomorphic decision-sufficient quotients (the quotient colors exclude
    authority) but different correct D2 decisions.
    """
    def swapped(on_b: bool) -> KnowledgeSpace:
        atoms = []
        for a in field.atoms:
            if any(a.atom_id == p["twins"][0] for p in planted):
                atoms.append(Atom(a.atom_id, a.atom_type, a.warrant,
                                  authority=Authority() if on_b else Authority.of(**{CUSTODY: 2})))
            elif any(a.atom_id == p["twins"][1] for p in planted):
                atoms.append(Atom(a.atom_id, a.atom_type, a.warrant,
                                  authority=Authority.of(**{CUSTODY: 2}) if on_b else Authority()))
            else:
                atoms.append(a)
        return KnowledgeSpace(tuple(atoms), field.hyperedges)
    return swapped(False), swapped(True)


# ---------------------------------------------------------------------------
# Stream: tasks + updates, frozen by salt before any arm runs.
# ---------------------------------------------------------------------------

def ground_truth(ks: KnowledgeSpace, s: str, t: str, revoked) -> bool:
    return t in gated_closure(ks, [s], revoked)


def build_stream(field: KnowledgeSpace, n_tasks: int = 32, n_updates: int = 10,
                 salt_tasks: str = SALT_TASKS, salt_updates: str = SALT_UPDATES
                 ) -> Dict[str, object]:
    """The frozen stream: D1 tasks interleaved with admissions and revocations.

    Task polarity is fixed at half SUPPORTED / half NOT by selecting pairs against ground
    truth at the stream state where the task runs. Update lists are frozen here once; every
    arm replays the identical sequence.
    """
    rng_t = random.Random(stable_seed(salt_tasks))
    rng_u = random.Random(stable_seed(salt_updates))
    ks = field
    revoked = frozenset()
    tasks: List[Dict[str, object]] = []
    updates: List[Dict[str, object]] = []
    ids = [a.atom_id for a in ks.atoms if not a.atom_id.startswith("h")]
    want_sup = n_tasks // 2
    want_nosup = n_tasks - want_sup
    got_sup = got_nosup = 0
    task_idx = 0
    ev_universe = [e for e in field.evidence_universe() if not str(e).startswith("hostile")]
    # interleave: n_tasks tasks, one update every n_tasks//n_updates tasks
    every = max(1, n_tasks // n_updates)
    while task_idx < n_tasks:
        s = rng_t.choice(ids)
        t = rng_t.choice(ids)
        if s == t:
            continue
        truth = ground_truth(ks, s, t, revoked)
        if truth and got_sup >= want_sup:
            continue
        if (not truth) and got_nosup >= want_nosup:
            continue
        tasks.append({"kind": "D1", "idx": task_idx, "s": s, "t": t,
                      "revoked_at_task": sorted(str(x) for x in revoked)})
        got_sup += 1 if truth else 0
        got_nosup += 0 if truth else 1
        task_idx += 1
        if task_idx % every == 0 and len(updates) < n_updates and task_idx < n_tasks:
            # admission batch: new edges among existing atoms, salted
            n_new = rng_u.randint(3, 7)
            new_edges = []
            for j in range(n_new):
                tail = rng_u.choice(ids)
                head = rng_u.choice([x for x in ids if x != tail])
                rel = rng_u.choice(RELS)
                wp = WarrantProfile.certified([frozenset([rng_u.choice(ev_universe)])])
                new_edges.append(Hyperedge("adm_%d_%d" % (len(updates), j), (tail,), (head,), rel, warrant=wp))
            updates.append({"kind": "admission", "after_task": task_idx - 1,
                            "edges": [{"id": e.edge_id, "tails": list(e.tails),
                                       "heads": list(e.heads), "rel": e.relation_type} for e in new_edges],
                            "_edges": new_edges})
            ks = ks.with_edges(*new_edges)
            # revocation: an evidence id whose removal flips at least one liveness
            cand = rng_u.sample(ev_universe, min(8, len(ev_universe)))
            pick = None
            for c in cand:
                if any(not a.is_live(revoked | {c}) and a.is_live(revoked) for a in ks.atoms):
                    pick = c
                    break
            if pick is None:
                pick = rng_u.choice(cand)
            updates.append({"kind": "revocation", "after_task": task_idx - 1,
                            "evidence": str(pick)})
            revoked = revoked | {pick}
    return {"tasks": tasks, "updates": updates,
            "final_revoked": sorted(str(x) for x in revoked),
            "n_support": got_sup, "n_not_support": got_nosup}


def stream_apply(field: KnowledgeSpace, stream: Dict[str, object]):
    """Replay generator: yields ('task', task, ks, revoked) / ('update', upd) in stream order."""
    ks = field
    revoked = set()
    # merge by after_task order
    seq = []
    for upd in stream["updates"]:
        seq.append((upd["after_task"], 1, upd))
    for t in stream["tasks"]:
        seq.append((t["idx"], 0, t))
    # sort on (position, kind) only: tasks before their updates; stable order keeps
    # admission before revocation within one update block; dicts are never compared.
    seq.sort(key=lambda x: (x[0], x[1]))
    for _, _, item in seq:
        if item["kind"] == "D1":
            yield ("task", item, ks, frozenset(revoked))
        elif item["kind"] == "admission":
            ks = ks.with_edges(*item["_edges"])
            yield ("update", item, ks, frozenset(revoked))
        else:
            revoked = revoked | {item["evidence"]}
            yield ("update", item, ks, frozenset(revoked))


# ---------------------------------------------------------------------------
# Measurement helpers shared by all arms.
# ---------------------------------------------------------------------------

def measure_bytes(obj) -> int:
    """Persistent/active byte measure: canonical JSON length of the object's serial form."""
    import json
    return len(json.dumps(obj, sort_keys=True, default=_json_default).encode("utf-8"))


def _json_default(o):
    if isinstance(o, frozenset):
        return sorted(str(x) for x in o)
    if isinstance(o, (set, tuple)):
        return list(o)
    return str(o)


def field_snapshot(ks: KnowledgeSpace) -> Dict[str, object]:
    return {"atoms": [a.as_dict() for a in ks.atoms],
            "edges": [e.as_dict() for e in ks.hyperedges]}
