"""Mandatory measured A–F, survivor, malformed-input and custody checks."""
REQUIRED = {'test_controls_v25': {'anchored_category_controls': 11, 'carrier_name_controls': 497, 'survivor_law_controls': 8},
 'test_coverage_v25': {'coverage_guard_rejections': 436},
 'test_custody_v25': {'inherited_custody_rejections': 15,
                      'source_path_escape_rejections': 5,
                      'unavailable_inherited_controls': 5,
                      'valid_inherited_custody_controls': 1},
 'test_hostiles_v25': {'malformed_model_encoder_rejections': 102,
                       'malformed_tree_rejections': 374,
                       'semantic_mutation_rejections': 18,
                       'valid_semantic_certificates': 9},
 'test_information_v25': {'e_basis_queries': 70,
                          'e_decoder_cases': 276,
                          'e_model_pairs': 69,
                          'e_models': 11,
                          'e_recoverable_cases': 160,
                          'f_basis_queries': 69,
                          'f_decoder_cases': 176,
                          'f_groups': 6,
                          'f_model_pairs': 44,
                          'f_models_n0_k0': 1,
                          'f_models_n1_k0': 1,
                          'f_models_n1_k1': 1,
                          'f_models_n2_k0': 1,
                          'f_models_n2_k1': 6,
                          'f_models_n2_k2': 2,
                          'f_named_models': 12,
                          'f_recoverable_cases': 112},
 'test_kernel_guard_v25': {'kernel_registration_rejections': 4},
 'test_presentations_v25': {'absent_singletons': 29,
                            'ambient_trees': 34882,
                            'guarded_subtype_folds': 12178,
                            'models': 82,
                            'models_n0': 1,
                            'models_n1': 2,
                            'models_n2': 8,
                            'models_n3': 71,
                            'padded_cells': 673,
                            'successful_trees': 7808,
                            'trees_n0': 0,
                            'trees_n1': 44,
                            'trees_n2': 1184,
                            'trees_n3': 33654},
 'test_survivors_v25': {'survivor_ledger_mutation_rejections': 550, 'valid_survivor_ledger_controls': 1},
 'test_tables_v25': {'a_accepted': 59,
                     'a_accepted_n0': 1,
                     'a_accepted_n1': 1,
                     'a_accepted_n2': 5,
                     'a_accepted_n3': 52,
                     'a_encoded_leaves': 462734,
                     'a_endpoint_certificates': 59,
                     'a_failed_trees': 59928,
                     'a_laws_000': 218695,
                     'a_laws_001': 42291,
                     'a_laws_010': 540,
                     'a_laws_011': 237,
                     'a_laws_100': 119,
                     'a_laws_101': 237,
                     'a_laws_110': 50,
                     'a_laws_111': 59,
                     'a_tables': 262228,
                     'a_tables_n0': 1,
                     'a_tables_n1': 2,
                     'a_tables_n2': 81,
                     'a_tables_n3': 262144,
                     'a_tree_formula_n0': 0,
                     'a_tree_formula_n1': 102,
                     'a_tree_formula_n2': 3312,
                     'a_tree_formula_n3': 115368,
                     'a_typed_trees': 118782,
                     'b_associative_trees': 28764,
                     'b_failed_trees': 107517,
                     'b_nonassoc_witnesses': 61,
                     'b_raw_trees': 115872,
                     'b_tables': 84},
 'test_transports_v25': {'arrow_permutations': 324,
                         'categories': 59,
                         'inverse_categories': 407,
                         'inverse_queries': 9680,
                         'object_permutations': 83,
                         'query_comparisons': 9680}}

def validate_coverage(coverage):
    if type(coverage) is not dict or set(coverage) != set(REQUIRED):
        raise ValueError("missing or unexpected mandatory experiment")
    for module, required in REQUIRED.items():
        actual = coverage[module]
        if type(actual) is not dict or set(actual) != set(required):
            raise ValueError("missing or unexpected coverage field: " + module)
        for key, expected in required.items():
            if type(actual[key]) is not int or actual[key] != expected:
                raise ValueError("required check not executed: " + module + "/" + key)
    return True
