"""DC7 — quantum-cognition carrier: exact microscope and bounded-reduction attack
(GMI_DOMAIN_CANDIDATES_DC1_DC9_V1.md section 2, record RV-377-047).

Carrier: a real amplitude vector psi in R^d, d = 2^n, with two questions realized as orthogonal projectors P_A, P_B
built from declared rotation frames. Native law: apply a projector (Lueders rule) and read a Born-rule probability.
Because the joint probability of an ordered pair of yes/no answers is ||M2 M1 psi||^2 with M1, M2 in {P, I-P}, no
normalization (and therefore no division) is ever needed: the whole model is matrix-vector products and norms.

Ecology E_order(n, Q): a REGISTERED table of question-order response frequencies. For each of Q question pairs and each
of the two asking orders the table holds the four joint outcome probabilities P(A then B) and P(B then A), generated by
a DECLARED projective model (a declared state angle and declared per-pair projector angles, all on the declared angle
grid) and quantized to PROB_UNITS = 4096ths. The obligation is to reproduce every one of the 8Q entries to within TOL.

Rows:
  QPROJ             the candidate: carrier = one shared unit state vector plus two projector angles per pair; the
                    angles are SEARCHED over the declared grid (and, at n = 1, so is the state angle).
  BAYES_ORDERED     the strongest D3 parent: a probabilistic row with an EXPLICIT ORDER VARIABLE. Per pair and order it
                    carries a marginal and two conditionals — (a, u, v) with P(A y B y) = a u, P(A y B n) = a(1-u),
                    P(A n B y) = (1-a)v, P(A n B n) = (1-a)(1-v) — six numbers per pair. The marginal is two charged
                    ADDs; each conditional is a charged division-free binary search of log2(S) MUL/GT steps.
  TABLE             the D2 parent: memorize the 8Q registered numbers; answered by a charged linear scan.
  QPROJ_COMMUTING   the negative twin: both questions are read off the SAME frame (declared index sets), so the
                    projectors commute and NO order effect is representable.

TWO DECLARED PRECISION INSTRUMENTS with IDENTICAL charged operation sequences (the dc_energy.Arith pattern):
  fx8   the registered 8-bit fixed point (FRAC_BITS 4: probabilities resolved only to 1/16);
  wide  a declared wide fixed point at scale 2^24 evaluated at unbounded integer precision.
Every row stores its numbers at the instrument's scale, so a capability difference between the instruments is
attributable to precision alone.

THE STRUCTURAL WITNESS. The QQ equality
     P(A then B, both yes) + P(not-A then not-B, both) - P(B then A, both yes) - P(not-B then not-A, both) = 0
is a constraint on the MODEL CLASS, not on any one fitted model: a row that reproduces a QQ-satisfying table inherits QQ
from the data. The microscope therefore runs a FAMILY CENSUS over a declared parameter grid of each class and reports
the QQ residual distribution: the projective class satisfies QQ identically (up to the instrument's rounding), the
ordered-Bayes class does not.

REDUCTION COST. The native price is one op per PROJECT and one per Born readout; the reduced price is the exact
classical state-vector simulation, d = 2^n amplitudes per state and d^2 = 4^n charged scalar operations per dense
operator application. The receipt reports the measured charged-ops-per-native-op alongside these analytic factors.
"""
from __future__ import annotations

import json
import math
import os
import sys

from . import bases
from .core import FX_ONE, Machine, sha256_of

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(os.path.dirname(HERE), "microscopes", "results")

THETA = 0.85
G_ANGLES = 12            # declared angle grid: theta_g = g * pi / G_ANGLES, g = 0..G-1
PROB_UNITS = 4096        # the registered table is quantized to 4096ths
TOL_UNITS = 16           # declared tolerance: 16/4096 = 1/256
WIDE_BITS = 24
PROB_BITS = 12           # declared description cost of one stored probability
ANGLE_BITS = 4           # declared description cost of one stored angle (an index into the 12-point grid)

# declared high-precision pi: floor(pi * 10^50) over 10^50
PI_NUM = 314159265358979323846264338327950288419716939937510
PI_DEN = 10 ** 50


def _cos_w(a, b):
    """cos(a*pi/b) at the declared working scale PI_DEN, by integer Taylor series (a >= 0, 0 <= a/b <= 1)."""
    x = PI_NUM * a // b
    mag = PI_DEN; total = PI_DEN; sign = 1; k = 1
    while mag and k < 80:
        mag = mag * x // PI_DEN * x // PI_DEN // ((2 * k - 1) * (2 * k))
        sign = -sign; total += sign * mag; k += 1
    return total


def _sin_w(a, b):
    """sin(a*pi/b) = cos(|b - 2a| * pi / (2b)) at the declared working scale."""
    return _cos_w(abs(b - 2 * a), 2 * b)


def _quant(val_w, S):
    """round a value at working scale PI_DEN to the instrument scale S (round half away from zero)."""
    neg = val_w < 0; v = -val_w if neg else val_w
    q = (v * S + PI_DEN // 2) // PI_DEN
    return -q if neg else q


def cos_q(g, S): return _quant(_cos_w(g, G_ANGLES), S)


def sin_q(g, S): return _quant(_sin_w(g, G_ANGLES), S)


class QArith:
    """two declared precision instruments with IDENTICAL charged operation sequences.
      fx8 : the registered 8-bit fixed point (scale FX_ONE = 16, clamp at +-127 raw);
      wide: a declared wide fixed point at scale 2^WIDE_BITS evaluated at unbounded integer precision."""

    def __init__(self, M, mode):
        self.M = M; self.mode = mode
        self.S = FX_ONE if mode == "fx8" else (1 << WIDE_BITS)

    def mul(self, a, b):
        if self.mode == "wide":
            self.M.op("MUL", 0, 0)
            p = a * b; neg = p < 0; p = -p if neg else p
            r = (p + (self.S >> 1)) >> WIDE_BITS
            return -r if neg else r
        return self.M.op("MUL", a, b)

    def add(self, a, b):
        if self.mode == "wide": self.M.op("ADD", 0, 0); return a + b
        return self.M.op("ADD", a, b)

    def sub(self, a, b):
        if self.mode == "wide": self.M.op("SUB", 0, 0); return a - b
        return self.M.op("SUB", a, b)

    def gt(self, a, b):
        if self.mode == "wide": self.M.op("GT", 0, 0); return int(a > b)
        return self.M.op("GT", a, b)

    def to_units(self, v):
        """convert an instrument-scale value to the registered table's 4096ths (uncharged readout convention)."""
        neg = v < 0; u = -v if neg else v
        r = (u * PROB_UNITS + self.S // 2) // self.S
        return -r if neg else r

    def from_units(self, u):
        neg = u < 0; v = -u if neg else u
        r = (v * self.S + PROB_UNITS // 2) // PROB_UNITS
        return -r if neg else r


# ------------------------------------------------------------------------------------- declared projective model
def _rot(A, d, g, i, j):
    """a plane rotation matrix at the instrument scale (charged: only the two trig entries are placed)."""
    S = A.S
    m = [[S if p == q else 0 for q in range(d)] for p in range(d)]
    c, s = cos_q(g, S), sin_q(g, S)
    m[i][i] = c; m[j][j] = c; m[i][j] = -s; m[j][i] = s
    return m


def _matmul(A, X, Y, d):
    out = [[0] * d for _ in range(d)]
    for i in range(d):
        for j in range(d):
            acc = 0
            for k in range(d): acc = A.add(acc, A.mul(X[i][k], Y[k][j]))
            out[i][j] = acc
    return out


def _frame(A, d, g, planes):
    U = [[A.S if p == q else 0 for q in range(d)] for p in range(d)]
    for (i, j) in planes: U = _matmul(A, U, _rot(A, d, g, i, j), d)
    return U


PLANES_A = {2: [(0, 1)], 4: [(0, 2), (1, 3)]}
PLANES_B = {2: [(0, 1)], 4: [(0, 1), (2, 3)]}
PLANES_STATE = {2: [(0, 1)], 4: [(0, 1), (1, 2), (2, 3)]}
KEEP_A = {2: (0,), 4: (0, 1)}
KEEP_B_COMMUTING = {2: (1,), 4: (0, 2)}


def _proj(A, U, keep, d):
    """P = sum_{k in keep} u_k u_k^T where u_k is the k-th COLUMN of U (charged)."""
    P = [[0] * d for _ in range(d)]
    for i in range(d):
        for j in range(d):
            acc = 0
            for k in keep: acc = A.add(acc, A.mul(U[i][k], U[j][k]))
            P[i][j] = acc
    return P


def _complement(A, P, d):
    return [[(A.S if i == j else 0) - P[i][j] for j in range(d)] for i in range(d)]


def _state(A, d, g):
    U = _frame(A, d, g, PLANES_STATE[d])
    return [U[i][0] for i in range(d)]


def _matvec(A, P, v, d, native):
    out = []
    for i in range(d):
        acc = 0
        for j in range(d): acc = A.add(acc, A.mul(P[i][j], v[j]))
        out.append(acc)
    native[0] += 1  # one PROJECT at the declared native price
    return out


def _norm2(A, v, d, native):
    acc = 0
    for i in range(d): acc = A.add(acc, A.mul(v[i], v[i]))
    native[0] += 1  # one Born readout at the declared native price
    return acc


def joint_probs(A, d, psi, PA, PB, native):
    """the eight joint probabilities: order AB then order BA, each (yes yes, yes no, no yes, no no), in table units."""
    nA = _complement(A, PA, d); nB = _complement(A, PB, d)
    out = []
    for (M1, M1c, M2, M2c) in ((PA, nA, PB, nB), (PB, nB, PA, nA)):
        for a_yes in (True, False):
            v = _matvec(A, M1 if a_yes else M1c, psi, d, native)
            for b_yes in (True, False):
                w = _matvec(A, M2 if b_yes else M2c, v, d, native)
                out.append(A.to_units(_norm2(A, w, d, native)))
    return out  # [AyBy, AyBn, AnBy, AnBn, ByAy, ByAn, BnAy, BnAn]


def single_prob(A, d, psi, ops, idx, native):
    """ONE ordered joint probability from PRE-COMPILED projector matrices: two Lueders applications and one Born
    readout (2 matvecs + 1 norm), i.e. the serve cost the candidate actually pays."""
    PA, nA, PB, nB = ops
    o, j = idx // 4, idx % 4
    first, firstc, second, secondc = (PA, nA, PB, nB) if o == 0 else (PB, nB, PA, nA)
    M1 = first if j // 2 == 0 else firstc
    M2 = second if j % 2 == 0 else secondc
    return A.to_units(_norm2(A, _matvec(A, M2, _matvec(A, M1, psi, d, native), d, native), d, native))


def compile_ops(A, d, gs, ga, gb, commuting=False):
    """compile the served state and the four projector matrices from the stored angles (charged at compile time)."""
    psi = _state(A, d, gs)
    UA = _frame(A, d, ga, PLANES_A[d])
    PA = _proj(A, UA, KEEP_A[d], d)
    PB = _proj(A, UA, KEEP_B_COMMUTING[d], d) if commuting else _proj(A, _frame(A, d, gb, PLANES_B[d]), KEEP_A[d], d)
    return psi, (PA, _complement(A, PA, d), PB, _complement(A, PB, d))


def qq_residual(p):
    """QQ equality: P(A then B, yy) + P(notA then notB, both) - P(B then A, yy) - P(notB then notA, both)."""
    return p[0] + p[3] - p[4] - p[7]


def model_probs(A, d, gs, ga, gb, native, commuting=False):
    psi = _state(A, d, gs)
    UA = _frame(A, d, ga, PLANES_A[d])
    PA = _proj(A, UA, KEEP_A[d], d)
    if commuting:
        PB = _proj(A, UA, KEEP_B_COMMUTING[d], d)
    else:
        PB = _proj(A, _frame(A, d, gb, PLANES_B[d]), KEEP_A[d], d)
    return joint_probs(A, d, psi, PA, PB, native)


# ----------------------------------------------------------------------------------------------------- ecology
TRUTH_STATE = 5
TRUTH_PAIRS = [(1, 4), (2, 7), (3, 5), (5, 10), (1, 8), (4, 9), (2, 3), (6, 11),
               (3, 10), (7, 8), (1, 6), (5, 2), (9, 4), (11, 3), (2, 9), (8, 1)]


def ecology(n, Q):
    """the REGISTERED table: generated by the declared projective model at the wide instrument."""
    d = 2 ** n
    M = Machine(bases.ALL["B0_LOCAL_ADAPTIVE_TRANSDUCERS"]); A = QArith(M, "wide"); native = [0]
    pairs = TRUTH_PAIRS[:Q]
    table = [model_probs(A, d, TRUTH_STATE, ga, gb, native) for (ga, gb) in pairs]
    order_effect = [max(abs(t[0] - t[4]), abs(t[3] - t[7])) for t in table]
    return {"n": n, "d": d, "Q": Q, "truth_state": TRUTH_STATE, "truth_pairs": pairs, "table": table,
            "qq_of_registered_table": [qq_residual(t) for t in table],
            "order_effect_units": order_effect, "min_order_effect_units": min(order_effect)}


# -------------------------------------------------------------------------------------------------------- rows
class Row:
    row = "?"

    def __init__(self, eco, A): self.e = eco; self.A = A; self.native = [0]

    def init(self, M): pass

    def learn(self, M): pass

    def answer(self, M, q, idx): raise NotImplementedError

    def desc_bits(self): return 0


def _grid_fit(A, d, native, target, states, commuting=False):
    """declared search: minimise the MAXIMUM absolute entry error over the declared angle grid; ties to the
    smallest (state, alpha, beta) index triple."""
    best = None
    for gs in states:
        tot = 0; sel = []
        for t in target:
            bb = None
            for ga in range(G_ANGLES):
                for gb in ([ga] if commuting else range(G_ANGLES)):
                    p = model_probs(A, d, gs, ga, gb, native, commuting)
                    e = max(abs(x - y) for x, y in zip(p, t))
                    if bb is None or e < bb[0]: bb = (e, ga, gb, p)
            sel.append(bb); tot = max(tot, bb[0])
        if best is None or tot < best[0]: best = (tot, gs, sel)
    return best


class QProj(Row):
    row = "QPROJ"

    def learn(self, M):
        d = self.e["d"]
        states = range(G_ANGLES) if self.e["n"] == 1 else [self.e["truth_state"]]
        self.max_err, self.gs, self.sel = _grid_fit(self.A, d, self.native, self.e["table"], states)
        self.state_fitted = self.e["n"] == 1
        self.compile(M)

    def compile(self, M, commuting=False):
        d = self.e["d"]
        self.compiled = [compile_ops(self.A, d, self.gs, self.sel[q][1], self.sel[q][2], commuting) for q in range(self.e["Q"])]

    def answer(self, M, q, idx):
        psi, ops = self.compiled[q]
        return single_prob(self.A, self.e["d"], psi, ops, idx, self.native)

    def desc_bits(self):
        return self.e["d"] * PROB_BITS + self.e["Q"] * 2 * ANGLE_BITS


class QProjCommuting(QProj):
    """negative twin: both questions are read off the SAME frame, so the projectors commute."""
    row = "QPROJ_COMMUTING"

    def learn(self, M):
        d = self.e["d"]
        states = range(G_ANGLES) if self.e["n"] == 1 else [self.e["truth_state"]]
        self.max_err, self.gs, self.sel = _grid_fit(self.A, d, self.native, self.e["table"], states, commuting=True)
        self.state_fitted = self.e["n"] == 1
        self.compile(M, commuting=True)

    def desc_bits(self):
        return self.e["d"] * PROB_BITS + self.e["Q"] * ANGLE_BITS


class BayesOrdered(Row):
    """the D3 parent with an explicit order variable: (marginal, two conditionals) per pair per order."""
    row = "BAYES_ORDERED"

    def _fit_cond(self, M, a, target):
        """division-free charged binary search for u minimising |a*u - target|, u in [0, S]."""
        A = self.A; lo, hi = 0, A.S
        for _ in range(A.S.bit_length()):
            mid = (lo + hi) // 2
            if A.gt(target, A.mul(a, mid)): lo = mid
            else: hi = mid
            self.native[0] += 1
        return lo if abs(A.mul(a, lo) - target) <= abs(A.mul(a, hi) - target) else hi

    def learn(self, M):
        A = self.A; self.par = []
        for t in self.e["table"]:
            s = [A.from_units(x) for x in t]
            a = A.add(s[0], s[1]); b = A.add(s[4], s[5])
            u = self._fit_cond(M, a, s[0]); v = self._fit_cond(M, A.sub(A.S, a), s[2])
            x = self._fit_cond(M, b, s[4]); y = self._fit_cond(M, A.sub(A.S, b), s[6])
            self.par.append((a, u, v, b, x, y))

    def answer(self, M, q, idx):
        A = self.A; a, u, v, b, x, y = self.par[q]
        self.native[0] += 1
        if idx == 0: return A.to_units(A.mul(a, u))
        if idx == 1: return A.to_units(A.mul(a, A.sub(A.S, u)))
        if idx == 2: return A.to_units(A.mul(A.sub(A.S, a), v))
        if idx == 3: return A.to_units(A.mul(A.sub(A.S, a), A.sub(A.S, v)))
        if idx == 4: return A.to_units(A.mul(b, x))
        if idx == 5: return A.to_units(A.mul(b, A.sub(A.S, x)))
        if idx == 6: return A.to_units(A.mul(A.sub(A.S, b), y))
        return A.to_units(A.mul(A.sub(A.S, b), A.sub(A.S, y)))

    def desc_bits(self): return self.e["Q"] * 6 * PROB_BITS


class TableRow(Row):
    """the D2 parent: memorize all 8Q registered numbers at the instrument's resolution; charged linear scan."""
    row = "TABLE"

    def learn(self, M):
        A = self.A
        self.mem = [[(q, i, A.from_units(v)) for i, v in enumerate(t)] for q, t in enumerate(self.e["table"])]

    def answer(self, M, q, idx):
        A = self.A
        for entries in self.mem:
            for (qq, ii, v) in entries:
                if M.op("EQ", qq * 8 + ii, q * 8 + idx):
                    self.native[0] += 1
                    return A.to_units(v)
        self.native[0] += 1
        return 0

    def desc_bits(self): return self.e["Q"] * 8 * PROB_BITS


ROWS = {"QPROJ": QProj, "BAYES_ORDERED": BayesOrdered, "TABLE": TableRow, "QPROJ_COMMUTING": QProjCommuting}


def run(row, basis, eco, seed=0, precision="wide"):
    M = Machine(basis, seed=seed); A = QArith(M, precision); ref = ROWS[row](eco, A)
    M.phase("exec"); ref.init(M)
    M.phase("upd"); ref.learn(M); M.end_event()
    learn = dict(M.L.c); learn_native = ref.native[0]
    M.phase("exec"); ok = 0; outs = []; served = []
    for q in range(eco["Q"]):
        for i in range(8):
            v = ref.answer(M, q, i); served.append(v); outs.append((q, i, v))
            ok += int(abs(v - eco["table"][q][i]) <= TOL_UNITS)
    nq = 8 * eco["Q"]
    cap = round(ok / nq, 4)
    R = dict(M.L.c)
    qq = [qq_residual(served[8 * q:8 * q + 8]) for q in range(eco["Q"])]
    return {"row": row, "basis": basis.name, "precision": precision, "capability": cap, "admissible": cap >= THETA,
            "R": R, "learn_ops": learn["upd"], "exec_per_query": (R["exec"] - learn["exec"]) / nq,
            "native_ops": ref.native[0] - learn_native, "native_per_query": (ref.native[0] - learn_native) / nq,
            "learn_native_ops": learn_native, "desc_bits": ref.desc_bits(), "n_queries": nq,
            "max_abs_error_units": max(abs(v - eco["table"][q][i]) for q in range(eco["Q"]) for i, v in enumerate(served[8 * q:8 * q + 8])),
            "qq_residual_units_served": qq, "max_abs_qq_served": max(abs(x) for x in qq),
            "answer_signature": sha256_of(outs)}


# ------------------------------------------------------------------------------- QQ family census (the witness)
BAYES_CENSUS_GRID = (1, 2, 3, 4, 5)  # sixths
BAYES_CENSUS_DEN = 6


def qq_census(n, precision="wide"):
    d = 2 ** n
    M = Machine(bases.ALL["B0_LOCAL_ADAPTIVE_TRANSDUCERS"]); A = QArith(M, precision); native = [0]
    proj = []
    for gs in range(G_ANGLES):
        for ga in range(G_ANGLES):
            for gb in range(G_ANGLES):
                proj.append(abs(qq_residual(model_probs(A, d, gs, ga, gb, native))))
    com = []
    for gs in range(G_ANGLES):
        for ga in range(G_ANGLES):
            com.append(abs(qq_residual(model_probs(A, d, gs, ga, ga, native, commuting=True))))
    bay = []
    U = PROB_UNITS
    for a in BAYES_CENSUS_GRID:
        for u in BAYES_CENSUS_GRID:
            for v in BAYES_CENSUS_GRID:
                for b in BAYES_CENSUS_GRID:
                    for x in BAYES_CENSUS_GRID:
                        for y in BAYES_CENSUS_GRID:
                            D = BAYES_CENSUS_DEN
                            r = (a * u + (D - a) * (D - v) - b * x - (D - b) * (D - y)) * U // (D * D)
                            bay.append(abs(r))
    return {"projective_family_size": len(proj), "projective_max_abs_qq_units": max(proj),
            "projective_frac_violating_tol": round(sum(1 for x in proj if x > TOL_UNITS) / len(proj), 6),
            "commuting_family_size": len(com), "commuting_max_abs_qq_units": max(com),
            "commuting_frac_violating_tol": round(sum(1 for x in com if x > TOL_UNITS) / len(com), 6),
            "ordered_bayes_family_size": len(bay), "ordered_bayes_max_abs_qq_units": max(bay),
            "ordered_bayes_frac_violating_tol": round(sum(1 for x in bay if x > TOL_UNITS) / len(bay), 6),
            "ordered_bayes_frac_exactly_zero": round(sum(1 for x in bay if x == 0) / len(bay), 6),
            "census_charged_ops": dict(M.L.c)}


# ------------------------------------------------------------------------------------------------------- cells
CELLS = {"n1_Q2": {"n": 1, "Q": 2}, "n1_Q4": {"n": 1, "Q": 4}, "n1_Q8": {"n": 1, "Q": 8}, "n1_Q16": {"n": 1, "Q": 16},
         "n2_Q2": {"n": 2, "Q": 2}, "n2_Q4": {"n": 2, "Q": 4}}


def lifecycle(r, H, native=False):
    per_q = r["native_per_query"] if native else r["exec_per_query"]
    fixed = r["desc_bits"] + (0 if native else r["learn_ops"])
    return fixed + H * per_q


def crossovers(adm, price):
    out = {}; names = sorted(adm); nat = price == "native"
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            ra, rb = adm[a], adm[b]
            fa = ra["desc_bits"] + (0 if nat else ra["learn_ops"]); fb = rb["desc_bits"] + (0 if nat else rb["learn_ops"])
            pa = ra["native_per_query"] if nat else ra["exec_per_query"]; pb = rb["native_per_query"] if nat else rb["exec_per_query"]
            if pa == pb: continue
            h = (fb - fa) / (pa - pb)
            if h > 0: out[f"{a}|{b}"] = round(h, 4)
    return out


def grid_for(cross, base=(1, 16, 128, 1024)):
    g = set(base)
    for h in cross.values():
        g.add(max(1, int(math.floor(h)))); g.add(int(math.ceil(h)) + 1); g.add(2 * int(math.ceil(h)) + 2)
    return sorted(g)


def main(tag="V31_DC7_QUANTUM", seed=0, cells=None, do_census=True):
    col = "B0_LOCAL_ADAPTIVE_TRANSDUCERS"; b = bases.ALL[col]
    use = cells if cells is not None else CELLS
    out = {}; ecos = {}
    for cname, spec in use.items():
        eco = ecology(spec["n"], spec["Q"]); ecos[cname] = eco
        for rname in ROWS:
            for prec in ("fx8", "wide"): out[(cname, rname, prec)] = run(rname, b, eco, seed, prec)
    census = {f"n{n}": qq_census(n) for n in sorted({s["n"] for s in use.values()})} if do_census else {}
    frontier = {}; cross_all = {}; grids = {}; dom = {}
    for cname in use:
        for prec in ("fx8", "wide"):
            for price in ("reduced", "native"):
                adm = {r: out[(cname, r, prec)] for r in ROWS if out[(cname, r, prec)]["admissible"]}
                cr = crossovers(adm, price); key = f"{cname}|{prec}|{price}"
                cross_all[key] = cr; g = grid_for(cr); grids[key] = g
                for H in g:
                    if not adm: frontier[f"{key}|H={H}"] = []; continue
                    costs = {r: lifecycle(adm[r], H, native=(price == "native")) for r in adm}
                    frontier[f"{key}|H={H}"] = sorted(r for r, c in costs.items() if c <= min(costs.values()) + 1e-9)
                dom[key] = sorted({r for H in g for r in frontier[f"{key}|H={H}"]})
    reduction = {}
    for cname in use:
        d = ecos[cname]["d"]
        q = out[(cname, "QPROJ", "wide")]
        reduction[cname] = {"d_amplitudes_2_pow_n": d, "scalar_ops_per_dense_operator_4_pow_n": d * d,
                            "charged_exec_ops_per_query": q["exec_per_query"], "native_ops_per_query": q["native_per_query"],
                            "measured_charged_ops_per_native_op": round(q["exec_per_query"] / q["native_per_query"], 4)}
    receipt = {"schema": "StageDC7QuantumV1", "status": "EXECUTED_EXACT_AT_SCOPE", "issue": [377, 422],
               "revival_record": "RV-377-047", "run_tag": tag,
               "domain_candidate": "DC7 quantum cognition (amplitude carrier, unitary evolution, Born-rule projective measurement, non-commuting question projectors)",
               "ecology": "E_order(n, Q): a registered table of question-order response frequencies P(A then B) and P(B then A), 4 joint outcomes per order per pair, generated by a declared projective model on n qubits and quantized to 4096ths",
               "cells_spec": use, "theta": THETA, "tolerance_units": TOL_UNITS, "prob_units": PROB_UNITS,
               "angle_grid": {"G": G_ANGLES, "theta_g": "g * pi / 12", "pi_constant": "floor(pi * 10^50) / 10^50, integer Taylor series, 80 terms max"},
               "declared_prices": {"native": "one op per PROJECT (Lueders projector application) and one per Born readout", "reduced": "exact classical state-vector simulation: d = 2^n amplitudes, d^2 = 4^n charged scalar MUL/ADD per dense operator application; QPROJ compiles its projector matrices from the stored angles at COMPILE time (charged into learn_ops) and serves one entry with 2 projector applications + 1 Born readout"},
               "precision_instruments": {"fx8": "registered universe: TOTAL_BITS 8, FRAC_BITS 4 (probabilities resolved only to 1/16)", "wide": "declared wide fixed point at scale 2^24, unbounded integer precision; IDENTICAL charged operation sequence"},
               "description_accounting": {"prob_bits": PROB_BITS, "angle_bits": ANGLE_BITS,
                                          "QPROJ": "d*PROB_BITS (shared state) + Q*2*ANGLE_BITS", "BAYES_ORDERED": "Q*6*PROB_BITS",
                                          "TABLE": "Q*8*PROB_BITS", "QPROJ_COMMUTING": "d*PROB_BITS + Q*ANGLE_BITS"},
               "state_fitting_regime": {"n1": "the state angle is SEARCHED over the declared grid together with the projector angles", "n2": "the state is DECLARED (part of the registered ecology) and only the projector angles are searched: a disclosed instrument limitation, since a full d=4 state search is outside the laptop budget"},
               "rows": list(ROWS),
               "ecology_facts": {c: {"truth_pairs": ecos[c]["truth_pairs"], "min_order_effect_units": ecos[c]["min_order_effect_units"],
                                     "order_effect_units": ecos[c]["order_effect_units"], "qq_of_registered_table": ecos[c]["qq_of_registered_table"]} for c in use},
               "cells": {f"{c}|{r}|{p}": {k: v for k, v in d.items() if k not in ("row", "basis")} for (c, r, p), d in out.items()},
               "qq_family_census": census,
               "qq_census_note": "the QQ equality is a constraint on the MODEL CLASS: any row that reproduces a QQ-satisfying registered table inherits QQ from the data, so the served-response QQ does NOT distinguish the classes. The family census over the declared parameter grids is the distinguishing witness.",
               "reduction_cost": reduction, "analytic_crossovers": cross_all, "frontier_grids": grids,
               "frontier": frontier, "frontier_occupants_over_extended_grid": dom,
               "claim_ceiling": "exact charged replay at scope; one declared truth model per cell; angles restricted to a declared 12-point grid, so every fit is a grid fit and no continuous optimum is claimed; the n = 2 state is declared rather than searched; native prices are declared, not measured; the QQ census is over declared finite parameter grids (12^3 projective members, 5^6 ordered-Bayes members), not over the continuum"}
    receipt["receipt_sha256"] = sha256_of({k: v for k, v in receipt.items() if k != "receipt_sha256"})
    json.dump(receipt, open(os.path.join(RES, f"STAGE_DC_{tag}.json"), "w"), indent=1, sort_keys=True, default=str)
    for cname in use:
        print(cname, "min order effect", ecos[cname]["min_order_effect_units"],
              "| fx8", {r: out[(cname, r, "fx8")]["capability"] for r in ROWS},
              "| wide", {r: out[(cname, r, "wide")]["capability"] for r in ROWS},
              "| desc", {r: out[(cname, r, "wide")]["desc_bits"] for r in ROWS},
              "| exec/q", {r: round(out[(cname, r, "wide")]["exec_per_query"], 1) for r in ROWS})
    for k, v in census.items(): print("census", k, v)
    return receipt


if __name__ == "__main__":
    main(tag=sys.argv[1] if len(sys.argv) > 1 else "V31_DC7_QUANTUM")
