"""Build ISSUE_833_COMMENT_RECONCILIATION_V1.json for the Section Z tier-1 batch.

Every `old` string is extracted programmatically from a live fetch of issue
comment 5684819296 taken immediately before the file is written -- none is
retyped. The script re-runs the substring-uniqueness check the Z map registered,
because the comment has changed since that map was taken (12036 -> ~19.7k bytes
after the first 15 rows closed) and uniqueness must be re-established, not
assumed.

Usage:
    gh api repos/SzeChunYiu/ORION-OCM/issues/comments/5684819296 --jq .body > live.md
    python3 -I -B build_reconciliation_v1.py live.md
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMMENT_ID = 5684819296

Z3 = "gmi-833-z-z3-invariance-v1"
Z5 = "gmi-833-z-z5-critical-phenomena-v1"
Z7 = "gmi-833-z-z7-impossibility-v1"

# (subsection id, row index within the subsection, suffix appended to the row)
CLOSURES = [
 ("Z3", 0, Z3, "IV-1",
  "TRANSFORMATION_REGISTRY_V1.json registers 10 transformations covering all 6 named "
  "categories, 6 claimed-irrelevant and 4 declared-relevant, each carrying the exact "
  "quantity it must or must not move, with a machine check that every declared-relevant "
  "entry actually moves it"),
 ("Z3", 1, Z3, "IV-2, IV-3",
  "over 65552 candidates and 60 registered worlds the group generated by surface "
  "renaming, state-label negation and input/output conjugation preserves "
  "(bits, e_now, e_delay) candidate-wise with 0 alarms over 200 renamings, 0 sigma "
  "breaks on the whole universe and 0 mismatches against a direct full scan, while "
  "(eta,lambda) -> (c*eta,c*lambda) scales the objective and lambda* by exactly c with "
  "0 equivariance breaks, so the verdict is a function of (p, lambda/eta) alone with "
  "boundary mu* = p/2"),
 ("Z3", 2, Z3, "IV-4",
  "12544 of the 65536 declared-stateful candidates are behaviourally identical to a "
  "stateless one -- 8448 of them outside the 4096-member syntactic dead-table family -- "
  "and dead padding under mixed accounting/labelling conventions flips the morphology "
  "verdict on exactly 20 of the 60 registered worlds"),
 ("Z3", 3, Z3, "IV-2, IV-4, IV-5",
  "both branches delivered rather than the cheaper disjunct: the conclusions survive the "
  "claimed-irrelevant group on all 60 worlds, and the non-invariant quantity is "
  "identified as the declared state-bit count with exact census 12544 and invariant "
  "replacement bits_eff, which reproduces the declared verdict 60/60 and takes 0 flips "
  "under dead padding where the declared convention takes 40"),
 ("Z3", 4, Z3, "IV-6",
  "21904 behavioural classes with multiplicity ratio exactly 785 and largest-class share "
  "785/65552 against a uniform 1/21904; 16 classes at description length 4 bits against "
  "21888 at 16; and under the frozen mutation graph 40198 of 65552 nodes lie within "
  "radius 8 of the registered start, the declared-stateless share of the ball falling "
  "from 1 at radius 0 to 15/214 at radius 3 against a universe share of 1/4097"),

 ("Z5", 0, Z5, "CP-1",
  "the objective is homogeneous of degree 1 in (eta, lambda), so the controls are "
  "exactly p and mu = lambda/eta -- 0 homogeneity violations over 60 worlds x a 6-rung "
  "rational scale ladder and 0 determinism violations across the 15 distinct (p, mu) "
  "keys -- with the argmin state-bit count as an order parameter jumping in {0,1}"),
 ("Z5", 1, Z5, "CP-2",
  "every one of the 16 stateless candidates has e_delay exactly N/2, so the best "
  "stateless cost is eta*p/2 and the best one-state-bit cost is lambda, giving "
  "lambda* = eta*p/2 by counting rather than enumeration; the analytic threshold equals "
  "the exact class-minimum crossing at all 60 worlds with 0 mismatches on both routes"),
 ("Z5", 2, Z5, "CP-3",
  "registered in the freeze before the scan and confirmed: J* = min(eta*p/2, lambda) "
  "with 0 closed-form mismatches, an exact rational tie at lambda* on 20/20 boundary "
  "worlds, zero critical width at three probe offsets down to 1e-9, and a jump in "
  "dJ*/dlambda of exactly 1 -- equal to the order-parameter jump"),
 ("Z5", 3, Z5, "CP-4",
  "exhaustive re-enumeration of all 65552 candidates at L in {2,3,4,5} (N = 4, 16, 48, "
  "128; 28, 146, 440, 444 distinct sigma classes) gives 0 threshold-drift violations at "
  "every rung, so the finite-size drift of lambda* is identically zero and the "
  "transition stays sharp at every size"),
 ("Z5", 4, Z5, "CP-5",
  "the law extrapolates exactly across problem size (zero drift in L) but NOT across "
  "substrate as scoped here: exhaustive enumeration of 16, 729 and 65536 A-ary stateless "
  "tables gives minimum delay fractions 1/2, 2/3, 3/4, so lambda*(A) = eta*p*(1 - 1/A) "
  "and the registered eta*p/2 is the A = 2 case only"),
 ("Z5", 5, Z5, "CP-6",
  "FAILED_SCALING_PREDICTION_REGISTER_V1.json publishes 1 refutation beside 4 "
  "confirmations and 1 parent negative control, all 6 pinned by path, git blob sha and a "
  "verbatim anchor occurring exactly once (0 anchor violations), and the refuted SP-3 "
  "carries the retired ceiling text plus the new forbidden promotion "
  "LAMBDA_STAR_IS_ETA_P_OVER_TWO_IN_GENERAL"),

 ("Z7", 0, Z7, "IM-1",
  "at bits = 0 zero-error delayed recall is impossible and the failure is uniform -- all "
  "16 stateless candidates sit at e_delay exactly 8 of 16, capping delay accuracy at "
  "exactly 1/2 -- while the identical task is solved with 0 errors at bits = 1, so the "
  "impossibility is resource-dependent rather than task-dependent"),
 ("Z7", 1, Z7, "IM-2",
  "exactly 286 of the 289 attainability-lattice cells are unreachable at bits = 0 and 146 "
  "at bits = 1 (Pareto frontiers {(0,8)} and {(0,0)}), and 3656 of the 7680 frozen "
  "cost-grid cells are infeasible, split 2976 at b = 0 and 680 at b = 1, with both routes "
  "agreeing on every count"),
 ("Z7", 2, Z7, "IM-3",
  "five failure-mode predictions were committed in FREEZE_V1.md before the enumeration "
  "that adjudicates them, with git log proving the order: Q1, Q2, Q3 and Q5 confirmed -- "
  "including the uncomputed modal profile (8,8) at multiplicity 14664 of 65536 -- and the "
  "deliberately naive scarcity hypothesis Q4 refuted"),
 ("Z7", 3, Z7, "IM-4",
  "six bounds frozen before evaluation and classified by whether they can be violated at "
  "all: three genuine forbidding ceilings -- C1 e_delay >= 8 with minimum 8 and 0 "
  "violations, C2 risk >= p/2 with equality at all 5 p rungs, and C6 min J = "
  "min(eta*p/2, lambda) with 0 violations over 60 worlds -- each valid AND tight, while "
  "C3, C4 and C5 are retained but not counted (C4's min(e_now,e_delay) <= 16 cannot be "
  "violated by any candidate) by a vacuity check validated to fire on C4 and on the two "
  "vacuous-ceiling hostiles and to stay silent on C1, C2 and C6"),
 ("Z7", 4, Z7, "IM-5",
  "every prediction tested exhaustively against all 65552 candidates plus six named "
  "structural families (16, 4096, 512, 4096, 61440, 256), which also yields a "
  "resource-independent structural impossibility: the Moore family cannot go below 8 "
  "copy-channel errors, frontier {(8,0)}, against the Mealy family's {(0,0)} at identical "
  "state budget"),
 ("Z7", 5, Z7, "IM-6",
  "COUNTEREXAMPLE_REGISTER_V1.json records the refutation of Q4 with an explicit witness "
  "(nxt = 68, table = 13, e_now = 16, e_delay = 0, re-scored by both routes), names the "
  "failed assumption that one state bit must be shared between the two channels, and "
  "records the repair and its claim-ceiling consequence; the null gives 153/153 witness "
  "soundness and 6/200 random claims true-and-tight against 3/3 frozen forbidding "
  "ceilings"),
]

NOT_CLOSED = [
 ("Z1", "NEW-SCIENCE. Needs a compact variational/selection principle that actually "
        "implies the registered laws as corollaries, plus a proof that some named laws "
        "cannot be compressed into it. No harness discharges it."),
 ("Z2", "EXACT-FORMAL and genuinely ready, but not reached in this lane. Rows 1-2 (finite "
        "no-free-lunch for prior-free search, and the minimal sufficient statistic that "
        "restores searchability) are provable over this universe; row 3 has a live lane "
        "(gmi-833-terminology-migration-v1) whose corpus scan must be checked before it "
        "is duplicated; rows 4-5 sit under heavy parent ownership (aj9a-aj9h, "
        "blind-recovery-v2) and the batching plan itself says they need a second pass."),
 ("Z4", "PLAN CORRECTION. The Z batching plan lists Z4 as Tier-1 ready; it is not. Row 4 "
        "reads 'Determine whether MLP/CNN/Transformer/etc. are fundamental GMI classes or "
        "implementations inside broader classes' and carries no 'where mathematically "
        "justified' escape clause. Answering it from a 65552-candidate binary transducer "
        "universe -- where the available named families are Moore and Mealy -- would be "
        "closure by narrowing, the same defect for which Z17 was excluded. Rows 1, 2, 3 "
        "and 5 are closable at registered finite scope; row 4 needs either real measured "
        "architecture families or an explicit rescoping of the row."),
 ("Z6", "NEW-SCIENCE. Needs preregistered environments where GMI and a strongest parent "
        "genuinely disagree. The likely terminal -- that MDL, Bayesian decision theory "
        "and bounded rationality are observationally equivalent to the boundary law on "
        "this finite quotient -- is row 6's own escape clause, but it must be earned by an "
        "equivalence proof, never assumed to avoid the work."),
 ("Z8", "NEW-SCIENCE. Needs an independent hostile-world generator covering nine named "
        "ingredient classes with predictions frozen before the worlds reach the scorer."),
 ("Z9", "EXTERNAL-GATE. Names separated prediction/test teams and a third-party "
        "adjudicator. Deliberately left for an unhurried HUMAN_GATE_BYPASSED__MODEL_PROXY; "
        "a proxy assembled in a hurry is exactly the POST_HOC_SUSPECT class audit #976 "
        "filed."),
 ("Z10", "EXTERNAL-GATE, plus real engineering. Needs five materially different real "
         "domains with measured CPU/GPU/wall-time/memory/I/O/energy."),
 ("Z11", "NEW-SCIENCE. Needs a benchmark whose scoring target is theory prediction rather "
         "than model accuracy, with hidden ecologies and negative controls."),
 ("Z13", "NEW-SCIENCE, and the head of the only dependency chain in Z: an unseen "
         "morphology recovered without its template in the grammar, with a prospectively "
         "predicted niche."),
 ("Z14", "EXTERNAL-GATE. Names cross-species natural-cognition evidence."),
 ("Z16", "NEW-SCIENCE, blocked on Z13. Cannot close before a genuinely surprising, "
         "predicted-before-observed result exists."),
 ("Z17", "STRUCTURALLY BLOCKED. Its rows say 'central conclusions' and 'the flagship "
         "claim', plural and definite. Running the eight robustness axes against one "
         "designated conclusion would be closure by narrowing. It needs a committed "
         "register of central conclusions first -- the BASELINE_V1.md section 1 A1-A14 "
         "assertion table is the natural authority -- and then one pass per entry."),
 ("Z18", "EXTERNAL-GATE. Names five independent hostile reviewer roles with authority to "
         "reopen green gates."),
]


def parse(body):
    """Return {subsection_id: (heading_line, [row_line, ...])} in document order."""
    out = []
    cur = None
    for line in body.split("\n"):
        if line.startswith("### "):
            sid = line[4:].split()[0]
            cur = {"id": sid, "heading": line, "rows": []}
            out.append(cur)
        elif line.startswith("- [") and cur is not None:
            cur["rows"].append(line)
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1]) as fh:
        body = fh.read()
    if body.endswith("\n"):
        body = body[:-1]
    subs = parse(body)
    by_id = dict([(s["id"], s) for s in subs])

    all_rows = []
    for s in subs:
        all_rows.extend(s["rows"])
    if len(set(all_rows)) != len(all_rows):
        sys.exit("duplicate row strings in the live comment")
    # the map's substring-uniqueness check, re-run on the current body
    subcollisions = []
    for a in all_rows:
        for b in all_rows:
            if a is not b and a in b:
                subcollisions.append(a)
    if subcollisions:
        sys.exit("row strings that are proper substrings of another: %r" % subcollisions[:3])

    replacements = []
    seen_old = set()
    for sid, idx, pkg, ids, evidence in CLOSURES:
        s = by_id[sid]
        old = s["rows"][idx]
        if not old.startswith("- [ ] "):
            sys.exit("%s row %d is not unchecked: %r" % (sid, idx, old))
        if body.count(old) != 1:
            sys.exit("%s row %d does not occur exactly once in the body" % (sid, idx))
        if old in seen_old:
            sys.exit("row used twice: %r" % old)
        seen_old.add(old)
        text = old[len("- [ ] "):]
        new = "- [x] %s — ✅ %s %s: %s." % (text, pkg, ids, evidence)
        replacements.append({"comment_id": COMMENT_ID, "anchor": s["heading"],
                             "old": old, "new": new, "subsection": sid,
                             "package": pkg, "result_ids": ids})

    unchecked_after = len([r for r in all_rows if r.startswith("- [ ] ")]) - len(replacements)
    doc = {
        "schema": "GMI_ISSUE_COMMENT_RECONCILIATION_V1",
        "issue": 833,
        "comment_id": COMMENT_ID,
        "section": "Z",
        "fetched_body_bytes": len(body.encode("utf-8")),
        "fetched_body_sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
        "rows_in_comment": len(all_rows),
        "rows_unchecked_before_this_batch": len([r for r in all_rows
                                                 if r.startswith("- [ ] ")]),
        "rows_closed_by_this_batch": len(replacements),
        "rows_left_unchecked_after_this_batch": unchecked_after,
        "heading_depth": "###",
        "claim_ceilings": {
            "gmi-833-z-z3-invariance-v1":
                "GMI_833_Z3_FINITE_TRANSFORMATION_REGISTRY_INVARIANCE_EQUIVARIANCE_AND_THE_"
                "DECLARED_STATE_BIT_NON_INVARIANT_AT_REGISTERED_BINARY_TRANSDUCER_SCOPE",
            "gmi-833-z-z5-critical-phenomena-v1":
                "GMI_833_Z5_EXACT_FIRST_ORDER_MORPHOLOGY_TRANSITION_ZERO_FINITE_SIZE_DRIFT_"
                "AND_THE_REFUTED_ALPHABET_INDEPENDENT_THRESHOLD_AT_REGISTERED_FINITE_SCOPE",
            "gmi-833-z-z7-impossibility-v1":
                "GMI_833_Z7_EXACT_RESOURCE_DEPENDENT_IMPOSSIBILITY_REGIONS_AND_"
                "PROSPECTIVELY_FROZEN_CAPABILITY_CEILINGS_AT_REGISTERED_BINARY_TRANSDUCER_"
                "SCOPE"},
        "forbidden_promotions": sorted(set([
            "REPRESENTATION_INDEPENDENCE_IN_GENERAL", "INVARIANCE_UNDER_ALL_RECODINGS",
            "SEARCH_INVARIANCE_FROM_SEMANTIC_INVARIANCE",
            "REAL_COMPILER_OR_HARDWARE_SUBSTRATE_INVARIANCE", "GRAMMAR_NEUTRALITY",
            "COMPLETE_TRANSFORMATION_REGISTRY", "DECLARED_STATE_BIT_ACCOUNTING_IS_WRONG",
            "FLAGSHIP_THEORY_FALSIFIED_BY_RECODING", "UNIVERSAL_CRITICAL_EXPONENTS",
            "CONTINUOUS_PHASE_TRANSITION", "THERMODYNAMIC_LIMIT_ESTABLISHED",
            "REAL_SUBSTRATE_SCALING", "PHYSICAL_SUBSTRATE_INVARIANCE",
            "SCALING_LAW_HOLDS_FOR_ALL_ACCOUNTING", "ALPHABET_LADDER_COVERS_ARCHITECTURES",
            "LAMBDA_STAR_IS_ETA_P_OVER_TWO_IN_GENERAL", "UNIVERSAL_IMPOSSIBILITY",
            "IMPOSSIBILITY_FOR_REAL_SYSTEMS",
            "CAPABILITY_CEILINGS_TRANSFER_TO_TRAINED_MODELS",
            "COMPLETE_ENUMERATION_OF_FAILURE_MODES",
            "RESOURCE_ACCOUNTING_IS_SUBSTRATE_INDEPENDENT",
            "IMPOSSIBILITY_REGION_IS_ARCHITECTURE_INDEPENDENT",
            "ZERO_STATE_MEANS_ZERO_MEMORY_IN_GENERAL"])),
        "replacements": replacements,
        "not_closed": [{"subsection": sid,
                        "rows_left": len(by_id[sid]["rows"]),
                        "reason": reason} for sid, reason in NOT_CLOSED],
        "note": ("every `old` is extracted verbatim from the fetched body named above and "
                 "occurs exactly once in it; no row string is a proper substring of "
                 "another; the issue comment is NOT edited by this lane"),
    }
    total_left = sum(e["rows_left"] for e in doc["not_closed"])
    if total_left != unchecked_after:
        sys.exit("not_closed rows (%d) do not account for the %d rows left unchecked"
                 % (total_left, unchecked_after))
    out = os.path.join(HERE, "ISSUE_833_COMMENT_RECONCILIATION_V1.json")
    with open(out, "w") as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print("wrote", out)
    print("closed %d rows; %d left unchecked; body sha256 %s"
          % (len(replacements), unchecked_after, doc["fetched_body_sha256"][:16]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
