"""All registered graph/admission pairs and independently enumerated typed paths."""
import importlib.util
import json
from pathlib import Path
import sys
import unittest

HERE = Path(__file__).resolve().parent

def load(name):
    spec = importlib.util.spec_from_file_location(name,HERE/(name+'.py'))
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

core,oracle = load('history_v16'),load('oracle_v16')
COVERAGE = {}


class HistoryTests(unittest.TestCase):
    def test_all_generated_domains(self):
        cases = count = admitted_count = singletons = bridge = empty = concatenations = 0
        lengths = {i:0 for i in range(5)}
        for raw,mask in oracle.graph_cases():
            graph = core.Graph(*raw)
            contains = lambda h: oracle.path_allowed(mask,h)
            queries = []
            def membership(history):
                queries.append(history)
                return history in dict(oracle.paths(raw,1)) and contains(history)
            decoded = core.decode_admission(graph,membership)
            self.assertEqual(queries,[(source,(i,)) for i,(source,_) in enumerate(raw[1])])
            self.assertEqual(decoded,mask)
            cases += 1
            kept = tuple(i for i,allowed in enumerate(mask) if allowed)
            subraw = (2,tuple(raw[1][i] for i in kept))
            subgraph = core.Graph(*subraw)
            ambient = dict(oracle.paths(raw,4))
            admitted_paths = {h:end for h,end in ambient.items() if contains(h)}
            lifted = {}
            for h,end in oracle.paths(subraw,4):
                forgotten = (h[0],tuple(kept[i] for i in h[1]))
                self.assertEqual(core.validate_history(subgraph,h),end)
                self.assertEqual(core.validate_history(graph,forgotten),end)
                restored = (forgotten[0],tuple(kept.index(i) for i in forgotten[1]))
                self.assertEqual(restored,h)
                lifted[forgotten] = end
                bridge += 1
            self.assertEqual(lifted,admitted_paths)
            subpaths = tuple(oracle.paths(subraw,4))
            for left,endpoint in subpaths:
                for right,last in subpaths:
                    if endpoint!=right[0] or len(left[1])+len(right[1])>4:
                        continue
                    joined = (left[0],left[1]+right[1])
                    forgotten = (left[0],tuple(kept[i] for i in joined[1]))
                    self.assertEqual(core.validate_history(subgraph,joined),last)
                    self.assertEqual(core.validate_history(graph,forgotten),last)
                    self.assertEqual(forgotten[1],tuple(kept[i] for i in left[1])+tuple(kept[i] for i in right[1]))
                    concatenations += 1
            for history,endpoint in ambient.items():
                self.assertEqual(core.validate_history(graph,history),endpoint)
                self.assertEqual(core.admitted(graph,mask,history),contains(history))
                count += 1
                lengths[len(history[1])] += 1
                admitted_count += contains(history)
                if not history[1]:
                    self.assertTrue(core.admitted(graph,mask,history))
                    empty += 1
            for i,(source,target) in enumerate(raw[1]):
                self.assertEqual(core.admitted(graph,mask,(source,(i,))),mask[i])
                self.assertEqual(core.validate_history(graph,(source,(i,))),target)
                singletons += 1
        self.assertEqual(cases,81)
        self.assertEqual(admitted_count,bridge)
        COVERAGE.update(graph_admission_cases=cases,typed_paths=count,admitted_paths=admitted_count,
                        singleton_decodings=singletons,subtype_correspondences=bridge,empty_path_units=empty,
                        subtype_concatenation_equations=concatenations)
        COVERAGE.update({'paths_length_'+str(k):v for k,v in lengths.items()})

    def test_domain_and_type_hostiles(self):
        graph = core.Graph(2,((0,1),(1,1)))
        mask = (True,True)
        # This domain agrees on singletons but is not generated by edge admission.
        fake = lambda h:len(h[1])<=1
        self.assertEqual(core.decode_admission(graph,fake),mask)
        self.assertTrue(core.admitted(graph,mask,(0,(0,1))))
        self.assertFalse(fake((0,(0,1))))
        # Evaluator-defined subdomain cannot substitute for the full raw source.
        full = (True,False)
        evaluated = lambda h:False
        self.assertNotEqual(core.decode_admission(graph,evaluated),full)
        parallel = core.Graph(2,((0,1),(0,1)))
        self.assertEqual(core.decode_admission(parallel,lambda h:h[1]==(1,)),(False,True))
        self.assertEqual(core.decode_admission(core.Graph(0,()),lambda _:True),())
        invalid = []
        for n in (-1,True,2.0,None):
            invalid.append(lambda v=n:core.Graph(v,()))
        for edges in ([(0,1)],((True,1),),((0.0,1),),((0,2),),((-1,0),),((0,),),('ab',),None):
            invalid.append(lambda e=edges:core.Graph(2,e))
        for h in ((True,()),(0.0,()),(-1,()),(2,()),(0,(True,)),(0,(0.0,)),(0,(2,)),
                  (1,(0,)),(0,[0]),[0,()],(0,'0'),(0,),None):
            invalid.append(lambda x=h:core.validate_history(graph,x))
        for badmask in ((1,True),(True,1.0),(True,),[True,True],None):
            invalid.append(lambda m=badmask:core.admitted(graph,m,(0,())))
        for result in (1,1.0,None,(), 'yes'):
            invalid.append(lambda r=result:core.decode_admission(graph,lambda _:r))
        invalid += [lambda:core.validate_history(core.Graph(0,()),(0,())),
                    lambda:core.decode_admission(graph,None)]
        for i,call in enumerate(invalid):
            with self.subTest(case=i),self.assertRaises(ValueError):
                call()
        COVERAGE.update(history_malformed_rejections=len(invalid),nongenerated_domain_controls=1,
                        source_definedness_controls=1,parallel_edge_controls=1,empty_graph_controls=1)


if __name__ == '__main__':
    program = unittest.main(exit=False,verbosity=2)
    print(json.dumps(COVERAGE,sort_keys=True))
    raise SystemExit(not program.result.wasSuccessful())
