#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Measure the exposure of post-freeze deviation D1.

Re-runs the executor with the deviation forced off and diffs EVERY leaf field of
the regenerated receipt against the shipped one, reporting changed/total in the
direct parent's `D1_SENSITIVITY_V1.json` format.  Inspection is not evidence;
this is.

    python3 -I -B measure_d1_sensitivity_v1.py
"""

import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RESULT = os.path.join(HERE, "RESULT_V1.json")
EXEC = os.path.join(HERE, "update_law_regimes_v1.py")
OUT = os.path.join(HERE, "D1_SENSITIVITY_V1.json")


def leaves(obj, path=""):
    if isinstance(obj, dict):
        for k in sorted(obj):
            for x in leaves(obj[k], path + "/" + str(k)):
                yield x
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            for x in leaves(v, path + "/%d" % i):
                yield x
    else:
        yield (path, obj)


def main():
    if not os.path.exists(RESULT):
        print("shipped RESULT_V1.json missing; run the executor first")
        sys.exit(1)
    shipped = json.load(open(RESULT))
    backup = RESULT + ".shipped"
    shutil.copyfile(RESULT, backup)
    env = dict(os.environ)
    env["REGIMES_D1_OFF"] = "1"
    try:
        r = subprocess.call([sys.executable, "-B", EXEC], cwd=HERE, env=env,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if r != 0:
            print("deviation-free run failed with code", r)
            sys.exit(1)
        without = json.load(open(RESULT))
    finally:
        shutil.copyfile(backup, RESULT)
        os.remove(backup)

    a = dict(leaves(shipped))
    b = dict(leaves(without))
    keys = sorted(set(a) | set(b))
    changed = []
    for k in keys:
        if a.get(k, "<absent>") != b.get(k, "<absent>"):
            changed.append({"path": k, "with_D1": a.get(k, "<absent>"),
                            "without_D1": b.get(k, "<absent>")})
    rec = {
        "schema": "GMI_833_DEVIATION_DEPENDENCE_V1",
        "package": "gmi-833-update-law-regimes-v1",
        "issue": 833,
        "deviation": "D1",
        "deviation_description": "the ascent evaluation charge conforms to "
                                 "FREEZE_V1 section 2.1, where p_test buys one "
                                 "candidate evaluated on one instance; adopted "
                                 "after the first run, in which the breadth law "
                                 "won every cell",
        "shape": "the #976 POST_HOC_SUSPECT ordering: the correction postdates "
                 "the observation that prompted it",
        "deviation_free_fallback": "one unit of p_test per candidate, reachable "
                                   "with REGIMES_D1_OFF=1",
        "why_not_in_RESULT_V1": "RESULT_V1.json is regenerated by the executor "
                                "and gated byte-exact in CI; a hand-added field "
                                "there would break reproducibility, which is the "
                                "gate working correctly",
        "sensitivity_test": {
            "method": "re-ran update_law_regimes_v1.py with REGIMES_D1_OFF=1 "
                      "and diffed every leaf field of the regenerated receipt "
                      "against the shipped run",
            "certificate_leaf_fields": len(keys),
            "fields_changed": len(changed),
            "changed_field_paths": [c["path"] for c in changed[:200]],
            "changed_field_count_truncated_at": 200,
            "examples": changed[:12],
        },
        "verdict": ("EXPOSURE_MEASURED_ZERO" if not changed
                    else "EXPOSURE_MEASURED_NONZERO"),
    }
    with open(OUT, "w") as fh:
        json.dump(rec, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print("leaf fields %d, changed %d -> %s"
          % (len(keys), len(changed), OUT))


if __name__ == "__main__":
    main()
