"""Learning generators of total arithmetic methods, with a fair primitive fallback.

Registered domain: rational univariate polynomials generated by the four total
instructions below. A learned fragment changes search order, never verification.
This is a bounded synthesis/abstraction reference, not unrestricted code execution.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from fractions import Fraction
from itertools import product
from typing import Iterable

from ocm.kso.ids import content_hash

PRIMITIVES = ("inc", "dec", "double", "square")
CHECKER = "rational-polynomial-coefficients.v1"
Program = tuple[str, ...]


def checked_program(program: Iterable[str]) -> Program:
    program = tuple(program)
    if len(program) > 8 or any(op not in PRIMITIVES for op in program):
        raise ValueError("program outside registered total grammar (maximum 8 instructions)")
    return program


def execute(program: Program, x: Fraction | int) -> Fraction:
    value = Fraction(x)
    for op in checked_program(program):
        if op == "inc":
            value += 1
        elif op == "dec":
            value -= 1
        elif op == "double":
            value *= 2
        else:
            value *= value
    return value


def normal_form(program: Program) -> tuple[Fraction, ...]:
    """Independent symbolic coefficient propagation, without calling execute."""
    coefficients = [Fraction(0), Fraction(1)]
    for op in checked_program(program):
        if op in ("inc", "dec"):
            coefficients[0] += 1 if op == "inc" else -1
        elif op == "double":
            coefficients = [2 * x for x in coefficients]
        else:
            squared = [Fraction(0)] * (2 * len(coefficients) - 1)
            for i, a in enumerate(coefficients):
                for j, b in enumerate(coefficients):
                    squared[i + j] += a * b
            coefficients = squared
    return tuple(coefficients)


def evaluate_polynomial(coefficients, x):
    value = Fraction(0)
    for coefficient in reversed(coefficients):
        value = value * x + coefficient
    return value


@dataclass(frozen=True)
class PolynomialTask:
    task_id: str
    coefficients: tuple[Fraction, ...]

    def __post_init__(self):
        coefficients = tuple(Fraction(c) for c in self.coefficients)
        if not self.task_id or not coefficients or len(coefficients) > 257:
            raise ValueError("invalid polynomial task")
        while len(coefficients) > 1 and coefficients[-1] == 0:
            coefficients = coefficients[:-1]
        if any(max(c.numerator.bit_length(), c.denominator.bit_length()) > 4096 for c in coefficients):
            raise ValueError("coefficient budget exceeded")
        object.__setattr__(self, "coefficients", coefficients)

    @property
    def fingerprint(self):
        # Task labels cannot turn the same mathematical question into held-out data.
        return content_hash({"domain": CHECKER, "coefficients": [str(c) for c in self.coefficients]})


@dataclass(frozen=True)
class SearchBudget:
    slots: int = 1000
    max_length: int = 4

    def __post_init__(self):
        if type(self.slots) is not int or not 0 <= self.slots <= 200_000:
            raise ValueError("invalid search slot budget")
        if type(self.max_length) is not int or not 0 <= self.max_length <= 8:
            raise ValueError("invalid program length bound")


@dataclass(frozen=True)
class GeneratorMethod:
    fragments: tuple[Program, ...] = ()
    training_tasks: tuple[str, ...] = ()

    def __post_init__(self):
        fragments = tuple(checked_program(p) for p in self.fragments)
        if len(fragments) > 16 or len(set(fragments)) != len(fragments) or any(len(p) < 2 for p in fragments):
            raise ValueError("invalid fragment library")
        object.__setattr__(self, "fragments", fragments)
        object.__setattr__(self, "training_tasks", tuple(self.training_tasks))

    @property
    def fingerprint(self):
        return content_hash({"grammar": PRIMITIVES, "fragments": self.fragments,
                             "training_tasks": self.training_tasks, "schedule": "alternate-baseline.v1"})


@dataclass(frozen=True)
class SearchResult:
    task_fingerprint: str
    method_fingerprint: str
    status: str
    program: Program | None
    slots: int
    candidates_checked: int
    counterexamples: tuple[int, ...]
    max_length: int

    def as_dict(self):
        return {"task_fingerprint": self.task_fingerprint, "method_fingerprint": self.method_fingerprint,
                "status": self.status, "program": self.program, "slots": self.slots,
                "candidates_checked": self.candidates_checked, "counterexamples": self.counterexamples,
                "max_length": self.max_length, "checker": CHECKER}


def verify_solution(task: PolynomialTask, result: SearchResult) -> bool:
    return (result.status == "VERIFIED_POLYNOMIAL_IDENTITY" and result.task_fingerprint == task.fingerprint
            and result.program is not None and len(result.program) <= result.max_length
            and normal_form(result.program) == task.coefficients)


def _primitive_programs(max_length):
    for length in range(max_length + 1):
        yield from product(PRIMITIVES, repeat=length)


def _guided_programs(method, max_length):
    # A fragment is expanded as data. Every attempted expansion occupies a slot,
    # including duplicate or too-long words; there is no hidden free search loop.
    tokens = method.fragments + tuple((op,) for op in PRIMITIVES)
    for length in range(1, max_length + 1):
        for word in product(tokens, repeat=length):
            yield tuple(op for token in word for op in token)


def solve(task: PolynomialTask, budget: SearchBudget = SearchBudget(),
          method: GeneratorMethod = GeneratorMethod()) -> SearchResult:
    baseline = iter(_primitive_programs(budget.max_length))
    guided = iter(_guided_programs(method, budget.max_length)) if method.fragments else None
    seen, counterexamples = set(), [0]
    checked = slots = 0
    for slots in range(1, budget.slots + 1):
        stream = guided if guided is not None and slots % 2 == 1 else baseline
        try:
            program = next(stream)
        except StopIteration:
            if stream is baseline:
                return SearchResult(task.fingerprint, method.fingerprint, "EXHAUSTED_DECLARED_GRAMMAR",
                                    None, slots - 1, checked, tuple(counterexamples), budget.max_length)
            guided = None
            continue
        if len(program) > budget.max_length or program in seen:
            continue
        seen.add(program)
        checked += 1
        if any(execute(program, x) != evaluate_polynomial(task.coefficients, x) for x in counterexamples):
            continue
        coefficients = normal_form(program)
        if coefficients == task.coefficients:
            return SearchResult(task.fingerprint, method.fingerprint, "VERIFIED_POLYNOMIAL_IDENTITY",
                                program, slots, checked, tuple(counterexamples), budget.max_length)
        # A nonzero degree-d polynomial cannot vanish at d+1 distinct integers.
        for x in range(max(len(coefficients), len(task.coefficients))):
            if evaluate_polynomial(coefficients, x) != evaluate_polynomial(task.coefficients, x):
                counterexamples.append(x)
                break
    return SearchResult(task.fingerprint, method.fingerprint, "BUDGET_EXHAUSTED", None,
                        slots, checked, tuple(counterexamples), budget.max_length)


def learn_generator(training: Iterable[tuple[PolynomialTask, SearchResult]]) -> GeneratorMethod:
    """A method-generating method: mine recurring proper fragments from checked solutions.

    Support counts distinct mathematical tasks, not copied demonstrations. No
    held-out task participates in fragment creation or ordering.
    """
    training = tuple(training)
    identities = [task.fingerprint for task, _ in training]
    if len(training) < 2 or len(set(identities)) != len(identities):
        raise ValueError("need at least two distinct training tasks")
    counts = Counter()
    for task, result in training:
        if not verify_solution(task, result):
            raise ValueError("training method has no checked solution")
        program = result.program
        fragments = {program[start:end] for start in range(len(program))
                     for end in range(start + 2, len(program) + 1) if end - start < len(program)}
        counts.update(fragments)
    fragments = sorted((p for p in counts if counts[p] >= 2), key=lambda p: (-counts[p], -len(p), p))[:16]
    return GeneratorMethod(tuple(fragments), tuple(sorted(identities)))


def validate_generator(method: GeneratorMethod, held_out: Iterable[PolynomialTask],
                       budget: SearchBudget = SearchBudget()) -> dict:
    tasks = tuple(held_out)
    ids = [t.fingerprint for t in tasks]
    if not tasks or len(set(ids)) != len(ids) or set(ids) & set(method.training_tasks):
        raise ValueError("held-out tasks must be nonempty, distinct and separate from training")
    rows = []
    for task in tasks:
        baseline, candidate = solve(task, budget), solve(task, budget, method)
        rows.append({"task": task.fingerprint, "baseline": baseline.as_dict(), "candidate": candidate.as_dict(),
                     "both_verified": verify_solution(task, baseline) and verify_solution(task, candidate)})
    accepted = (bool(method.fragments) and all(r["both_verified"] and r["candidate"]["slots"] <= r["baseline"]["slots"] for r in rows)
                and any(r["candidate"]["slots"] < r["baseline"]["slots"] for r in rows))
    return {"method": method.fingerprint, "training_tasks": method.training_tasks,
            "held_out": rows, "accepted": accepted,
            "terminal": "HELD_OUT_SEARCH_IMPROVEMENT" if accepted else "KEEP_PRIMITIVE_BASELINE",
            "scope": "Declared tasks only; no population speedup or scientific novelty claim"}


def admit_solution(runtime, task: PolynomialTask, result: SearchResult):
    """Recheck before KSO admission; support revocation reopens the method."""
    from ocm.kso.space import Atom, Hyperedge
    from ocm.kso.types import Scope
    from ocm.kso.warrant import WarrantProfile
    from ocm.store.evidence import Channel
    if not verify_solution(task, result):
        raise ValueError("only independently rechecked polynomial solutions can be admitted")
    payload = {**result.as_dict(), "coefficients": [str(x) for x in task.coefficients]}
    _, evidence = runtime.admit_evidence(payload, Channel.PROOF, CHECKER, scope=Scope.of(task.fingerprint))
    proof_id, method_id = "proof:" + content_hash(payload), "method:" + content_hash(payload)
    warrant = WarrantProfile.of({evidence})
    if proof_id not in runtime.state.ks.ids:
        runtime.admit_object(Atom(proof_id, "proof", warrant, scope=Scope.of(task.fingerprint), quarantined=True,
                                  content_ref=CHECKER), (), "EXACT_CHECKER")
    if method_id not in runtime.state.ks.ids:
        edge = Hyperedge("support:" + method_id, (proof_id,), (method_id,), "SUPPORT", warrant=warrant)
        runtime.admit_object(Atom(method_id, "procedure", warrant, scope=Scope.of(task.fingerprint),
                                  content_ref=content_hash(payload), meta=(("program", result.program),)), (edge,), "EXACT_CHECKER")
    return {"method_id": method_id, "evidence_id": evidence, "task": task.fingerprint}


def admit_generator(runtime, training, held_out, budget: SearchBudget = SearchBudget()):
    """Persist a learned generator only after rechecking its declared holdout.

    The effectiveness claim is confined to these tasks. The KSO support edge
    retains every training proof and the measured comparison, so revoking either
    disables reuse without deleting the learned fragment or its failed history.
    """
    from ocm.kso.space import Atom, Hyperedge
    from ocm.kso.types import Scope
    from ocm.kso.warrant import WarrantProfile, Liveness, meet_all_profiles
    from ocm.store.evidence import Channel
    training, held_out = tuple(training), tuple(held_out)
    method = learn_generator(training)
    validation = validate_generator(method, held_out, budget)
    if not validation["accepted"]:
        raise ValueError("learned generator did not improve the declared held-out tasks")
    supports = [admit_solution(runtime, task, result) for task, result in training]
    support_warrant = meet_all_profiles(runtime.state.ks.atom_map()[r["method_id"]].warrant for r in supports)
    if support_warrant.liveness(runtime.state.revoked) is not Liveness.LIVE:
        raise ValueError("training support is no longer live")
    _, evidence = runtime.admit_evidence(validation, Channel.OBSERVATION, "method-generator-holdout.v1")
    warrant = support_warrant.meet(WarrantProfile.of({evidence}))
    payload = {"kind": "generator.v1", "fragments": method.fragments, "training_tasks": method.training_tasks,
               "fingerprint": method.fingerprint, "validation": content_hash(validation)}
    atom_id = "generator:" + content_hash(payload)
    if atom_id not in runtime.state.ks.ids:
        edge = Hyperedge("support:" + atom_id, tuple(r["method_id"] for r in supports), (atom_id,), "SUPPORT", warrant=warrant)
        runtime.admit_object(Atom(atom_id, "procedure", warrant, scope=Scope.of("polynomial-search.v1"),
                                  content_ref=content_hash(payload), meta=tuple(payload.items())), (edge,), "OBSERVATION")
    return {"generator_id": atom_id, "validation_evidence": evidence,
            "training": supports, "validation": validation}


def load_generator(runtime, generator_id: str) -> GeneratorMethod:
    from ocm.kso.warrant import Liveness
    atom = runtime.state.ks.atom_map().get(generator_id)
    if atom is None or atom.liveness(runtime.state.revoked) is not Liveness.LIVE:
        raise ValueError("generator is missing or its support is not live")
    payload = dict(atom.meta)
    if atom.atom_type != "procedure" or payload.get("kind") != "generator.v1" or content_hash(payload) != atom.content_ref:
        raise ValueError("generator data identity mismatch")
    method = GeneratorMethod(tuple(tuple(p) for p in payload["fragments"]), tuple(payload["training_tasks"]))
    if method.fingerprint != payload["fingerprint"]:
        raise ValueError("generator method fingerprint mismatch")
    return method
