# -*- coding: utf-8 -*-
"""Row-by-row adjudication data for the 61 rows of programme comment 5687604615.

This module is DATA: bucket, disposition, reason, and (for rows closed by verified parent citation)
the parent alias + receipt fields whose pinned canonical-JSON values the RA-1 auditor verifies, plus the
frozen `row_meaning_token` that RA-1 checks against every cited parent's forbidden set.

Buckets (exactly four, as frozen): HARNESS | EXACT-FORMAL | NEW-SCIENCE | EXTERNAL-GATE.
Dispositions: EARNED | EARNED_BY_COUNTEREXAMPLE | OPEN | GOVERNANCE_NOT_A_CLOSABLE_ROW.

Row indices refer to MTG_ROWS_V1.json.  Own packages are cited by their directory name; their receipt
blob shas are computed by build_map_v1.py at build time.
"""

MAP = "gmi-833-mtg-map-v1"
GH = "gmi-833-mtg-groupoid-hom-v1"
NT = "gmi-833-mtg-naturality-tiers-v1"
EG = "gmi-833-mtg-enriched-geometry-v1"

# alias -> receipt path (parents) ; own packages resolve to research/<pkg>/RESULT_V1.json
OWN = {GH: "research/%s/RESULT_V1.json" % GH, NT: "research/%s/RESULT_V1.json" % NT,
       EG: "research/%s/RESULT_V1.json" % EG}
MANIFESTS = {  # programme packages already on main whose manifests are cited for governance rows
    "M01": "research/gmi-833-transform-geometry-v1/MANIFEST_V1.json",
    "M02": "research/gmi-833-developmental-naturality-v1/MANIFEST_V1.json",
    "M03": "research/gmi-833-remint-equivariance-v1/MANIFEST_V1.json",
    "M04": "research/gmi-833-pareto-topology-v1/MANIFEST_V1.json",
    "M05": "research/gmi-833-g0-binary-recovery-v1/MANIFEST_V1.json",
}


def C(alias, **fields):
    return {"alias": alias, "fields": dict(fields)}


ROWS = {
    # ------------------------------------------------------------------ MTG-1
    0: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=GH, token="RELABELING_GROUP_ACTS_ON_DERIVATION_RECORDS_AT_FINITE_SCOPE",
            reason="Built here: GRP-1 verifies the action axioms of Sym(X) x Sym(T) on derivation records and the action groupoid.",
            cites=[C(GH, **{"checks.grp1_action_axioms": True, "counts.compatibility_checks": 720, "counts.groupoid_associativity_triples": 1728, "counts.orbit_size_max": 12})],
            evidence="`gmi-833-mtg-groupoid-hom-v1` GRP-1: the registered relabeling group `Sym(X)×Sym(T)` (12 elements) acts on derivation records (presentation + recomputed observation table + history): identity 5/5, compatibility `(gh)·D = g·(h·D)` 720/720, inverses 60/60, action-groupoid associativity 1728/1728 triples, orbit size 12; both routes agree."),
    1: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="CONCLUSIONS_COMMUTE_WITH_REGISTERED_RELABELINGS_AT_FINITE_SCOPE",
            reason="P03 GAUGE-1A proves fingerprint and quotient transform-distance invariance; P16 and P17 prove reachability-fraction and cluster-membership invariance under 120 token relabelings; GRP-2 adds recomputed observations, Pareto and ball membership.",
            cites=[C("P03", **{"checks.canonical_fingerprint_invariant": True, "checks.quotient_transform_geometry_invariant": True, "counts.three_state_remints_exhausted": 6, "counts.base_quotient_pairs": 9}),
                   C("P16", **{"checks.all_surface_remints_preserve_membership": True, "remints.certified_surface_remint_count": 120, "remints.presentation_law_membership_checks": 276480}),
                   C("P17", **{"checks.all_certified_remints_equivariant": True}),
                   C(GH, **{"checks.grp2_conclusions_commute": True, "counts.conclusion_checks": 60})],
            evidence="P03 `GAUGE-1A`: canonical fingerprint and the 9-pair quotient transform-distance matrix are invariant under all 6 three-state relabelings; P16: law membership survives all 120 certified token relabelings (276,480 checks); P17 `STABLE-1`: cluster membership commutes with every certified relabeling; `gmi-833-mtg-groupoid-hom-v1` GRP-2: recomputed observations, Pareto-minimal and forward-ball membership commute with the 12-element action (60/60). Registered relabelings only — not grammar changes that alter length or search geometry."),
    2: dict(bucket="HARNESS", disposition="EARNED", token="LEXICAL_NEUTRALITY_WITH_SEMANTIC_CHANGE_IS_DETECTED",
            reason="P03 section 6 hostiles: neutral names with output/transition/intervention/development/resource mutation all rejected; P14 A2 semantic-rename hostiles; P13 R2 surface-tie hostile.",
            cites=[C("P03", **{"checks.semantic_mutation_hostiles_detected": True, "counts.semantic_hostile_cases": 6}),
                   C("P14", **{"checks.semantic_rename_flags": True, "semantic_mix_terminal": "SEMANTIC_MACRO_LEAKAGE"}),
                   C("P13", **{"checks.encoding_surface_tie_hostile": True})],
            evidence="P03: 6 hostile twins with neutral state names and a mutated output, transition, intervention response, developmental edge, resource vector or non-bijective map are all rejected; P14 A2: lexically clean `mix`/`local_apply` are flagged `SEMANTIC_MACRO_LEAKAGE`; P13 R2: a surface-name tie-break that changes the winner is `ENCODING_SENSITIVE`."),
    3: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="ALTERNATE_ENCODINGS_YIELD_EQUAL_QUOTIENT_CONCLUSIONS_AT_FINITE_SCOPE",
            reason="P05: two materially different low-level Boolean encodings (NAND-only, NOR-only) recover the identical semantic mechanism; P05R R2 encoding audit ENCODING_INVARIANT_AT_REGISTERED_REMINTS on all four runs.",
            cites=[C("P05", **{"checks.delay_unique_semantic_recovery_both_grammars": True, "counts.grammar_twins": 2, "recovered.DELAY1_NAND.next_truth": "0101", "recovered.DELAY1_NOR.next_truth": "0101", "checks.bounded_four_gate_cross_compilers": True}),
                   C("P05R", **{"audits.DELAY1_NAND.subaudits.encoding.terminal": "ENCODING_INVARIANT_AT_REGISTERED_REMINTS", "audits.DELAY1_NOR.subaudits.encoding.terminal": "ENCODING_INVARIANT_AT_REGISTERED_REMINTS", "audits.IDENTITY_NAND.subaudits.encoding.terminal": "ENCODING_INVARIANT_AT_REGISTERED_REMINTS"})],
            evidence="P05 `G0-1A`/`RECOVER-1A`: two low-level encodings with identical Boolean semantics (NAND-only and NOR-only, inter-compilable in 4 gates) each recover exactly one `DELAY1` semantic candidate out of 260, and it is the same one (`next=0101`, `output=0011`, resources `(1,0)`); P05R R2: the canonical semantic projection is `ENCODING_INVARIANT_AT_REGISTERED_REMINTS` on all four runs. Two encodings at a tiny finite scope; not broad grammar neutrality."),
    4: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="REPRESENTATION_INVARIANCE_SEPARATED_FROM_SEARCH_INVARIANCE",
            reason="P03 section 7: relabeling invariance does not infer search invariance (forward/reverse first hits differ); P15 RELABEL-2 same-semantics non-isometric pair reverses the choice; P07 FSB-6 order dependence.",
            cites=[C("P03", **{"checks.search_invariance_not_inferred": True, "witnesses.search_order_forward_winner": "same_semantics_long_encoding", "witnesses.search_order_reverse_winner": "same_semantics_short_encoding"}),
                   C("P15", **{"nonisometric_same_semantics_hostile.selection_GA": "A", "nonisometric_same_semantics_hostile.selection_GB": "B", "nonisometric_same_semantics_hostile.semantic_images_equal": True, "isometric_remint_certificate.certified": 24}),
                   C("P07", **{"checks.alternate_order_changes_finite_budget_morphology": True})],
            evidence="P03 §7: representation invariance is proved and search invariance is explicitly NOT inferred — a budget-one control returns `same_semantics_long_encoding` forward and `same_semantics_short_encoding` in reverse; P15 `RELABEL-1/2`: all 24 isometric relabelings preserve the choice while the same-semantics non-isometric `GA/GB` pair reverses it `A→B`; P07 `FSB-6`: reordering the same candidate set changes the finite-budget choice. `gmi-833-mtg-groupoid-hom-v1` GRP-3 re-exhibits the boundary (`M2`→`M4`)."),
    # ------------------------------------------------------------------ MTG-2
    5: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="HOM_DEFINED_OVER_MECHANISM_CLASSES_WITHOUT_ARCHITECTURE_NAMES",
            reason="P01 defines registered transforms between architecture-name-free mechanism classes with typed fields; GH HOM-1 extends the record.",
            cites=[C("P01", **{"checks.left_identity": True, "checks.right_identity": True, "counts.nodes": 5, "counts.edges": 5, "verdict": "GREEN"}),
                   C(GH, **{"counts.hom_hom_maps_total": 48, "counts.hom_ordered_pairs": 16})],
            evidence="P01 `TRANS-1A`: a transform is the typed record `(s,t,eps,rho,A,E)` between architecture-name-free mechanism classes (5 nodes, 5 edges, all fields exact); `gmi-833-mtg-groupoid-hom-v1` HOM-1 extends it to `(s,t,tau,eps,unc,rho,A,E,I,tier)` and enumerates `Hom(M,N)` as all label-preserving state maps (48 maps over 16 ordered pairs)."),
    6: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="IDENTITY_LAWS_HOLD_AT_FINITE_SCOPE",
            reason="P01 left/right identity checks; GH 96 identity checks on the extended record.",
            cites=[C("P01", **{"checks.left_identity": True, "checks.right_identity": True}), C(GH, **{"counts.hom_identity_checks": 96})],
            evidence="P01 `TRANS-1A`: `F∘1_M = F = 1_N∘F` on the complete immutable record; `gmi-833-mtg-groupoid-hom-v1` HOM-1: 96/96 two-sided identity checks on the extended typed record."),
    7: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="ASSOCIATIVITY_HOLDS_AT_FINITE_SCOPE",
            reason="P01 associativity; GH 32 composable triples on the extended record.",
            cites=[C("P01", **{"checks.associativity": True}), C(GH, **{"counts.hom_associativity_triples": 32})],
            evidence="P01 `TRANS-1A`: `H∘(G∘F) = (H∘G)∘F` for every compatible triple with consistent assumptions; `gmi-833-mtg-groupoid-hom-v1` HOM-1: 32/32 composable triples on the chain `M1→M2→M3→M5` of the extended record."),
    8: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=GH, token="COMPOSITION_LAWS_FOR_ALL_TYPED_FIELDS_STATED_AND_SOUND",
            reason="Built here: HOM-1 states the composition laws for eps, uncertainty interval, resources, contracts and tier and proves every declared field sound after composition (576/576).",
            cites=[C(GH, **{"checks.hom1_identity_associativity_composition_laws": True, "checks.hom1_tier_min_rule_sound": True, "checks.hom1_contract_rule_sound": True, "checks.hom1_eps_bound_sound": True, "counts.hom_composition_pairs": 576, "counts.hom_tier_min_rule_strict": 20, "counts.hom_contract_rule_strict": 64})],
            evidence="`gmi-833-mtg-groupoid-hom-v1` HOM-1: semantic error adds, the uncertainty interval adds endpointwise, lifecycle resources add coordinatewise, intervention contracts intersect, and the developmental tier is the minimum; over all 576 composable pairs every declared field is sound against recomputation (eps bound 576/576, tier 576/576, contract 576/576), equality is not claimed (recomputed tier strictly better in 20, contract in 64). Composition semantics for `P01`'s error/resource laws are inherited, not re-proved."),
    9: dict(bucket="HARNESS", disposition="EARNED", token="COMPOSITION_FAILS_CLOSED_ON_INCOMPATIBLE_ASSUMPTIONS_OR_EVIDENCE_LOSS",
            reason="P01 fail-closed hostiles (assumption conflict, missing evidence, endpoint mismatch, negatives, dimension); GH HOM-2 adds EVIDENCE_LOSS on composition.",
            cites=[C("P01", **{"checks.fail_closed_hostiles": True, "witnesses.hostiles.assumption_conflict": True, "witnesses.hostiles.missing_evidence": True, "counts.hostile_cases": 6}),
                   C(GH, **{"hostiles.hom2_evidence_loss.detected": True, "hostiles.hom2_evidence_loss.applicable": True, "checks.hom2_required_evidence_carried_no_alarm": True})],
            evidence="P01: 6 fail-closed cases (assumption conflict, endpoint mismatch, missing evidence, negative error/resource, resource dimension) refuse to yield a transform; `gmi-833-mtg-groupoid-hom-v1` HOM-2: a composite whose union of evidence kinds lacks a kind required by the target class is refused as `EVIDENCE_LOSS` (applicable and detected), with the no-alarm case when one component carries it."),
    10: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=GH, token="EQUIVALENT_ENDPOINT_RELABELINGS_INDUCE_ISOMORPHIC_HOM_SETS_AT_FINITE_SCOPE",
             reason="Built here: HOM-3 conjugation bijection with all fields preserved.",
             cites=[C(GH, **{"checks.hom3_conjugation_bijection": True, "counts.hom3_relabeling_pairs": 576, "counts.hom3_maps_checked": 1728, "counts.hom3_fields_preserved": 1728, "counts.hom3_bijective": 576})],
             evidence="`gmi-833-mtg-groupoid-hom-v1` HOM-3: for every ordered pair of fixture presentations and every pair of relabelings of source and target (576 pairs), conjugation `tau ↦ s∘tau∘r⁻¹` is a bijection of Hom sets (576/576) preserving eps, uncertainty, resources, contract and recomputed tier on all 1,728 maps; both routes agree. Registered bijective relabelings only."),
    # ------------------------------------------------------------------ MTG-3
    11: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=NT, token="EXACT_AND_APPROXIMATE_SQUARES_DEFINED_WITH_EXACT_DEFECT",
             reason="Built here: NAT-1 defines eps and the exact/approximate squares, proves subadditivity.",
             cites=[C(NT, **{"counts.nat1_composable_pairs": 19683, "counts.nat1_trajectory_checks_through_length_5": 2457, "counts.nat1_eps_zero_maps": 13})],
             evidence="`gmi-833-mtg-naturality-tiers-v1` NAT-1: the exact square is `eps(T)=0` and the approximate square at level `a` is `eps(T)≤a` for `eps(T)=max_{x,e} d_Y(T(Phi(x,e)),Psi(T(x),e))`; `eps(U∘T)≤eps(T)+eps(U)` on 19,683/19,683 composable pairs (discrete metric) and the Lipschitz-weighted bound under the registered path metric; the 13 exact maps reproduce the parent's trajectory preservation (2,457 checks)."),
    12: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=NT, token="STATIC_LEARNING_COMPATIBLE_AND_FULL_EQUIVALENCE_TIERS_SEPARATED",
             reason="Built here: NAT-2 four-level tier census with strict inclusions and witnesses.",
             cites=[C(NT, **{"counts.nat2_registered_three_state_static": 36, "counts.nat2_registered_three_state_lc": 24, "counts.nat2_registered_three_state_exact": 9, "counts.nat2_registered_three_state_full": 5, "counts.nat2_registered_three_state_static_minus_lc": 12, "counts.nat2_registered_three_state_lc_minus_exact": 15, "counts.nat2_registered_three_state_exact_minus_full": 4})],
             evidence="`gmi-833-mtg-naturality-tiers-v1` NAT-2: `STATIC` (labels preserved) ⊃ `LEARNING_COMPATIBLE(1/2)` (labels preserved and `eps≤1/2`) ⊃ `EXACT` (`eps=0`) ⊃ `FULL` (exact, bijective, inverse exact); census over all 243 maps is 36/24/9/5 and every inclusion is strict with a recorded witness (differences 12/15/4). Under the discrete metric `LC(1)=STATIC`, so a graded metric is what separates the middle tier."),
    13: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="EXACT_NATURALITY_CLOSED_UNDER_COMPOSITION",
             reason="P02 TRANS-2A composition theorem with executable certificate.",
             cites=[C("P02", **{"checks.composition_natural": True, "checks.identity_natural": True, "counts.trajectory_checks_through_length_5": 126, "counts.state_experience_commuting_cells_per_good_map": 4})],
             evidence="P02 `TRANS-2A`: the composite of two exact developmental-natural maps is exact developmental-natural (`(U∘T)(Phi_M(x,e)) = Phi_P((U∘T)(x),e)` by two applications of the square), identity is natural, and finite trajectory preservation holds by induction — 126 trajectory checks through length 5 on the composite."),
    14: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="STATIC_EQUIVALENCE_WITHOUT_TRAJECTORY_COMMUTATION_WITNESSED",
             reason="P02 static-only hostile: every protected label preserved, two commuting-square violations.",
             cites=[C("P02", **{"checks.static_only_hostile_detected": True, "counts.static_only_naturality_violations": 2, "witnesses.static_hostile_first_violation": ["m0", "x", "bB", "bA"]})],
             evidence="P02: the static-only hostile preserves every protected state label yet violates the commuting square in 2 cells (first violation `T(Phi_M(m0,x)) = bB` vs `Phi_N(T(m0),x) = bA`), proving `STATIC_BEHAVIOR_PRESERVATION ≠ DEVELOPMENTAL_NATURALITY` at the registered finite scope."),
    15: dict(bucket="HARNESS", disposition="EARNED", built_by=NT, token="PATH_DEPENDENCE_TRACKED_NOT_ERASED",
             reason="Built here: NAT-3 tracker vs final-output-only check; hysteresis witness.",
             cites=[C(NT, **{"counts.nat3_tracker_rows": 45, "counts.nat3_tracker_mismatches": 34, "counts.nat3_final_output_only_check_mismatches": 0, "hostiles.final_output_only_hostile.detected": True})],
             evidence="`gmi-833-mtg-naturality-tiers-v1` NAT-3: on the pair `(H,V)` final outputs agree on all 45 registered (start, word) rows — a final-output-only check reports 0 — while the per-prefix trajectory tracker reports 34 state mismatches (`eps=1`); the hysteresis witness `ab` vs `ba` from `h0` reaches distinct states `h1`, `h2` with the same label. Choice-level hysteresis stays with P09/P23."),
    16: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=NT, token="STOCHASTIC_KERNEL_NATURALITY_WITH_EXACT_DEFECT_INTERVAL",
             reason="Built here: NAT-4 total-variation defect, subadditivity, deterministic specialization, overclaim hostile, null.",
             cites=[C(NT, **{"counts.nat4_composable_pairs": 19683, "counts.nat4_deterministic_specialization_checks": 243, "hostiles.deterministic_overclaim.detected": True, "witnesses.nat4_overclaim.exact_tv": "1/4", "witnesses.nat4_overclaim.mode_projection_eps": "0", "null.passing": 0, "null.draws": 200})],
             evidence="`gmi-833-mtg-naturality-tiers-v1` NAT-4: for exact row-stochastic kernels the defect `tv(T)=max TV(T_*K_M, K_N∘T)` is subadditive on 19,683/19,683 pairs, point-mass kernels give `tv=eps` on 243/243 maps, and the reported object is the exact interval `[0,tv]`; the deterministic-overclaim hostile (mode-projected systems commute, `eps=0`, true kernels `tv=1/4`) is refused; null 0/200 random kernels reach `tv=0`. Predictive defect only — P24's uncertainty-kind boundary is inherited."),
    # ------------------------------------------------------------------ MTG-4
    17: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="VECTOR_VALUED_DIRECTED_BURDEN_DEFINED",
             reason="P04 DIST-1B Pareto antichain algebra and multiobjective closure H(M,N).",
             cites=[C("P04", **{"checks.pareto_algebra_exact": True, "checks.multiobjective_path_closure": True, "counts.triple_law_assertions": 32000, "counts.distinct_grid_frontiers": 20, "witnesses.A_to_C_pareto": [["0", "5"], ["1", "1"], ["5", "0"]]})],
             evidence="P04 `DIST-1B`: directed burden between mechanism classes is the Pareto frontier `H(M,N)` of attainable path burden vectors under the antichain algebra (choice = Pareto union, composition = Minkowski sum then Pareto reduction; 20 grid frontiers, 32,000 triple-law assertions); witness `H(A,C) = {(0,5),(1,1),(5,0)}`."),
    18: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="IDENTITY_ZERO_AND_DIRECTED_TRIANGLE_FOR_FROZEN_SCALARIZATIONS",
             reason="P01 DIST-1A identity-zero and triangle; P04 scalar triangle for three frozen weight vectors.",
             cites=[C("P01", **{"checks.distance_identity_zero": True, "checks.triangle_violations_zero": True, "counts.ordered_triples_checked": 125}),
                    C("P04", **{"checks.scalar_triangle_all_registered_weights": True, "counts.scalar_triangle_triples_checked": 192, "counts.scalar_weight_vectors": 3})],
             evidence="P01 `DIST-1A`: `d_w(M,M)=0` and `d_w(A,C) ≤ d_w(A,B)+d_w(B,C)` on 125/125 ordered triples for the frozen weights; P04: the scalar projection of the Pareto closure obeys the directed triangle inequality for all three registered price vectors (192 triples)."),
    19: dict(bucket="HARNESS", disposition="EARNED", token="UNREACHABLE_STAYS_INFINITE",
             reason="P01 d(A,E)=INF preserved; P04 empty frontier preserved.",
             cites=[C("P01", **{"checks.unreachable_is_infinite": True, "witnesses.d_A_E": "INF"}), C("P04", **{"checks.unreachable_frontier_preserved": True, "witnesses.A_to_D": "UNREACHABLE_EMPTY_FRONTIER"})],
             evidence="P01: the unreachable pair keeps `d(A,E) = INF` (no finite sentinel); P04: the isolated node keeps the empty frontier `H(A,D) = ∅` and lies outside every finite budget ball."),
    20: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="SYMMETRY_NOT_REQUIRED_ASYMMETRIC_HOSTILE_WITNESSED",
             reason="P01 d(A,C)=3 vs d(C,A)=9; P04 one-way zero-burden A->B vs (7,7) return — the compile-cheap/decompile-expensive shape.",
             cites=[C("P01", **{"checks.asymmetry_witness": True, "witnesses.d_A_C": "3", "witnesses.d_C_A": "9"}),
                    C("P04", **{"checks.directed_zero_cost_asymmetry_witness": True, "witnesses.A_to_B_zero_burden": [["0", "0"]], "witnesses.B_to_A_burden": [["7", "7"]]})],
             evidence="P01: `d(A,C) = 3` while `d(C,A) = 9`, no symmetry premise used; P04: a zero-burden one-way transform `A→B` against a `(7,7)` return burden — the asymmetric compile-versus-decompile shape — so the topology is directed and need not be `T1`."),
    21: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="FORWARD_BUDGET_BALLS_DEFINED_FROM_DIRECTED_BURDEN",
             reason="P04 TOPO-1A strict forward budget balls with basis theorem.",
             cites=[C("P04", **{"checks.forward_budget_ball_basis": True, "counts.basis_condition_cases": 433, "counts.positive_budget_vectors": 64, "counts.distinct_sampled_balls": 7})],
             evidence="P04 `TOPO-1A`: the strict forward budget ball `B_b(M) = {N : ∃v∈H(M,N), v<b}` is defined from the vector burden; the basis condition (`N∈B_b(M)` ⇒ `B_{b−v}(N) ⊆ B_b(M)`) holds in 433 cases over 64 positive budgets (7 distinct sampled balls)."),
    22: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="TOPOLOGY_GENERATED_FROM_EARNED_STRUCTURE_NO_MANIFOLD_ASSUMED",
             reason="P04 generated topology axioms verified; manifold/Hausdorff explicitly forbidden promotions.",
             cites=[C("P04", **{"checks.finite_generated_topology_axioms": True, "counts.generated_open_sets": 12, "counts.generated_topology_pair_checks": 144})],
             evidence="P04: the topology is generated only from the forward balls of the earned burden structure — 12 open sets closed under pairwise union and finite intersection (144 checks) — with `TOPOLOGY_IS_MANIFOLD_PROVED` and `TOPOLOGY_IS_HAUSDORFF_PROVED` listed as forbidden promotions."),
    23: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=EG, token="METRIC_AND_TOPOLOGY_STABILITY_UNDER_RELABELINGS_AND_COORDINATE_PERTURBATIONS_AT_FINITE_SCOPE",
             reason="Built here: STAB-1 relabeling stability; STAB-2 rescaling, bounded additive perturbation and scalar-projection stability.",
             cites=[C(EG, **{'checks.relabeling_topology_transport_equal_all': True, 'counts.relabel_topology_equalities': 120, 'counts.null_closure_equalities': 0, 'counts.rescale_closure_pair_equalities': 75, 'counts.cells_box_stable': 1544, 'counts.stable_cell_flips': 0, 'checks.frozen_nonmember_criterion_refuted_by_counterexample': True, 'checks.scalar_projection_lipschitz_bound': True})],
             evidence="`gmi-833-mtg-enriched-geometry-v1` STAB-1/STAB-2: closure and generated topology are transport-equal under all 120 node relabelings (120/120 and 120/120; null of misaligned transports 0/200 on the closure and 1/200 on the coarser topology; automorphism group trivial); positive coordinatewise rescaling commutes with closure (75/75 pairs) and, with budgets rescaled alike, yields the identical topology (3/3), while a fixed budget grid changes it for 2 of 3 rescalings (18 → 24 open sets); under ±1/4 additive edge perturbation membership is sandwiched by the two extreme closures on 113,600 checks, 1,544/1,600 cells are box-stable and 0 of 109,127 stable-cell pattern checks flip; the frozen frontier-margin non-membership rule is refuted by an exact 4-node counterexample (budget (155/16,1): frontier (10,0) reads stable, a dominated 3-edge path reaches (19/2,0) after −1/4 per edge) and replaced by the proved box criterion; scalar projections obey |d_w−d_w'| ≤ max|(w−w')·v| on 51/51 finite pairs and keep +∞ on 24/24. Finite registered graph only; no claim under arbitrary perturbation."),
    24: dict(bucket="EXACT-FORMAL", disposition="EARNED", built_by=EG, token="FINITE_ORDERED_MONOID_ENRICHMENT_VERIFIED_COMPLETENESS_NOT_CLAIMED",
             reason="Built here: ENR-1 ordered-monoid enrichment law of the closure.",
             cites=[C(EG, **{'checks.enrichment_lax_composition_law': True, 'checks.enrichment_identity_law': True, 'counts.enrichment_triples_checked': 125, 'counts.composition_monotone_checks': 7000, 'checks.choice_is_least_upper_bound': True, 'terminal': 'FINITE_ORDERED_MONOID_ENRICHMENT_VERIFIED', 'quantale_completeness_not_claimed': True})],
             evidence='`gmi-833-mtg-enriched-geometry-v1` ENR-1: the Pareto antichain algebra is a finite ordered monoid — dominance is a preorder (20 reflexive checks, 8,000 transitivity triples, antisymmetric on all 400 pairs), sequential composition is monotone in each argument (7,000 checks), choice is the least upper bound (800 + 8,000 checks), and the closure satisfies the lax enrichment law H(M,N)⊛H(N,P) ⊑ H(M,P) on 125/125 node triples with I ⊑ H(M,M) on 5/5 nodes (28 triples strictly worse, 8 equal); terminal `FINITE_ORDERED_MONOID_ENRICHMENT_VERIFIED` — a complete quantale would additionally require the four recorded infinite-join conditions, which are not claimed; the primary geometry stays resource-vector valued and the scalar d_w is a lossy projection (the coordinatewise infimum (1,1) of the frontier {(1,4),(4,1)} is unattainable; hostile detected).'),
    # ------------------------------------------------------------------ MTG-5
    25: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="BOUNDED_CONSTRUCTIVE_REALIZATION_OF_REGISTERED_PROPERTY_VECTORS_AT_FINITE_SCOPE",
             reason="P05 analytic construction + uniqueness for the persistent-state property; P17 four supplied reference fingerprints realized in G0-fin at (2,2); P20 eleven registered families recovered at declared finite scopes.",
             cites=[C("P05", **{"checks.delay_unique_semantic_recovery_both_grammars": True, "counts.delay_universal_certificate_sequences_lengths_1_to_8": 510, "recovered.DELAY1_NAND.resources": [1, 0], "grammar_results.NAND.delay_exact_solutions": 1}),
                    C("P17", **{"posthoc_mapping.known_mapped_cluster_count": 4, "posthoc_mapping.supplied_reference_count": 4}),
                    C("P20", **{"registered_families_recovered_at_their_declared_finite_scopes": 11, "registered_family_count": 11, "status": "GREEN"})],
             evidence="P05 `RECOVER-1A`: the persistent-state property is realized constructively from the NAND/NOR lower grammar (`s_{t+1}=x_t`, `y_t=s_t`, proved for all lengths, 510-sequence certificate) and is the unique exact candidate of 260; P17 `MAP-1`: 4 of 4 supplied reference fingerprints are realized among the 12 clusters of the (2,2) G0 slice; P20: all 11 registered families recovered at their declared finite task/basis scopes with labels hidden. Registered finite scopes only."),
    26: dict(bucket="HARNESS", disposition="EARNED", token="NO_SMUGGLING_STATUS_RECORDED_FOR_FLAGSHIP_RECOVERY",
             reason="P05 records level P3_RELATIVE; P20 records zero forbidden source hits and the bias boundary; P19 rejects 11/11 smuggling configurations; P14 owns the audit tooling.",
             cites=[C("P05", **{"prior_disclosure.level": "P3_RELATIVE_AT_REGISTERED_FINITE_SCOPE", "prior_disclosure.architectural_prior": False, "prior_disclosure.target_family_name_visible_to_search": False}),
                    C("P20", **{"blind_source_forbidden_hits": [], "registered_families_recovered_at_their_declared_finite_scopes": 11}),
                    C("P19", **{"hostile_configs_checked": 11, "hostile_configs_rejected": 11, "clean_generic_config": "ACCEPTED"}),
                    C("P14", **{"checks.semantic_rename_flags": True, "checks.missing_disclosures_fail_closed": True})],
             evidence="P05 records `prior_disclosure.level = P3_RELATIVE_AT_REGISTERED_FINITE_SCOPE` with no architectural prior and no family name or property vector visible to search; P20 records `blind_source_forbidden_hits = []` for all 11 recoveries; P19's contract rejects 11/11 smuggling configurations and accepts the clean generic one; P14 supplies the six-audit tooling with fail-closed missing disclosures."),
    27: dict(bucket="HARNESS", disposition="EARNED", token="NEUTRAL_INITIALIZATION_AND_ACTUAL_REACHABILITY_REQUIRED_AND_MEASURED",
             reason="P05 initial state 0, exhaustive search with forward/reverse agreement; P16 measured reachable quotient fractions from the seed under four frozen laws; P23 escape iff a feasible path exists.",
             cites=[C("P05", **{"checks.forward_reverse_exhaustive_search_same_semantic_pareto": True, "prior_disclosure.search_prior": "exhaustive finite semantic search; deterministic lexical tie only inside expression synthesis"}),
                    C("P16", **{"checks.bfs_matches_analytic_for_every_law": True, "census.registered_law_count": 4, "census.quotient_denominator": 21, "census.presentation_denominator": 576}),
                    C("P23", **{"checks.stochastic_positive_path_iff": True, "census.deterministic_escape_cases": 1792})],
             evidence="P05: recovery starts from the neutral state `s_0 = 0` under exhaustive search whose forward and reverse enumerations agree; P16: reachability is measured, not assumed — exact reachable quotient fractions from the seed under the four frozen laws (`4/21`, `6/7`, `4/21`, `1` of 21 classes over 576 presentations) with BFS matching the analytic characterization; P23 `TRAP-1`: reachability holds iff a budget-feasible path exists (1,792 deterministic cases)."),
    28: dict(bucket="HARNESS", disposition="EARNED", token="MATCHED_NEGATIVE_GRAMMAR_REMOVES_MECHANISM_PRESERVES_BACKGROUND",
             reason="P13 R1 matched-control theorem and unmatched hostile; P05R applies it: 256 stateful candidates removed, background multiset equal; P05 zero stateless solutions.",
             cites=[C("P13", **{"checks.matched_twin_detected": True, "checks.unmatched_background_rejected": True, "unmatched_grammar_hostile.matched": False}),
                    C("P05R", **{"audits.DELAY1_NAND.subaudits.grammar.terminal": "GRAMMAR_TWIN_MATCHED", "audits.DELAY1_NAND.subaudits.grammar.target_candidates_removed": 256, "audits.DELAY1_NAND.subaudits.grammar.background_multiset_equal": True}),
                    C("P05", **{"hostiles.state_removed_delay_exact_solution_count": 0})],
             evidence="P13 `R1`: a matched negative control must remove exactly the mechanism-carrying candidates and keep the background-capacity multiset and context equal (deleting an extra candidate is `GRAMMAR_TWIN_UNMATCHED`); P05R applies it — 256 stateful candidates removed, background multiset equal, `GRAMMAR_TWIN_MATCHED` — and P05 finds 0 exact `DELAY1` solutions in the state-removed grammar."),
    29: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="THREE_MATERIALLY_DIFFERENT_LOW_LEVEL_ENCODINGS",
             reason="Only two materially different low-level encodings have been applied to one recovery (P05: NAND-only, NOR-only; P19/P20 require two per hold-out). No recovery on main is replicated across three. Next tranche: gmi-833-mtg-third-encoding-recovery-v1 — add a multiplexer-tree basis and a direct truth-table encoding to the P05 DELAY1/IDENTITY recovery with an independently written synthesizer; claim ceiling at the P05 scope."),
    30: dict(bucket="HARNESS", disposition="EARNED", token="WHOLE_FAMILIES_HELD_OUT_NOT_SOURCE_INSTANCES",
             reason="P19 family-level hold-out contract (11 families, fingerprints post hoc only, 11/11 leak configurations rejected); P20 recovers the families with labels hidden.",
             cites=[C("P19", **{"family_count": 11, "all_family_fingerprints_posthoc_only": True, "hostile_configs_rejected": 11}),
                    C("P20", **{"registered_families_recovered_at_their_declared_finite_scopes": 11, "new_holdouts_two_materially_different_routes_each": True})],
             evidence="P19 `AJ9a`: the hold-out unit is the registered family (11 families, each a post-hoc fingerprint), with family ids, fingerprints, macros and family-specific scores forbidden as generator inputs (11/11 hostile configurations rejected); P20: all 11 families are then recovered with labels hidden, each new hold-out by two materially different routes."),
    31: dict(bucket="HARNESS", disposition="EARNED", token="RECOVERY_SCORED_ON_PROPERTY_NOT_SYNTAX",
             reason="P05 candidate identity is the semantic truth table; P18 novelty is a semantic/resource/developmental distance with 26,793 syntactically distinct zero-distance pairs; P26 fingerprint tests are structural predicates.",
             cites=[C("P05", **{"recovered.DELAY1_NAND.next_truth": "0101", "recovered.DELAY1_NAND.output_truth": "0011", "recovered.post_hoc_delay_property": "ONE_BIT_PERSISTENT_STATE_WITH_NEXT_STATE_INPUT_PROJECTION_AND_OUTPUT_STATE_PROJECTION"}),
                    C("P18", **{"checks.novelty_not_syntax_and_lipschitz": True, "novelty_census.zero_distance_distinct_syntax_pair_count": 26793}),
                    C("P26", **{"posthoc_terminal": "RECOVERED", "presentations": 2, "searches": 2})],
             evidence="P05: the recovered object is identified by its semantic truth tables (`next=0101`, `output=0011`) and named only post hoc as a state property; P18 `NOVELTY-1`: distance is semantic/resource/developmental, with 26,793 pairs of distinct program texts at distance 0; P26: the K01 post-hoc adjudication tests structural predicates (multi-stage composition, non-affine response) on two independently generated presentations."),
    32: dict(bucket="HARNESS", disposition="EARNED", token="UNKNOWN_IS_A_VALID_TERMINAL",
             reason="P19 typed NOT_RECOVERED_AT_SCOPE; P17 UNKNOWN total and non-forcing (8/12); P21 UNKNOWN channel exercised.",
             cites=[C("P19", **{"outcome_terminals": ["COMPILED", "RECOVERED", "PREDICTED_SELECTED", "NOT_RECOVERED_AT_SCOPE"], "unknown_reserved_for_AJ10": "UNKNOWN_MORPHOLOGY"}),
                    C("P17", **{"checks.UNKNOWN_is_explicit_and_total": True, "posthoc_mapping.unknown_cluster_count": 8, "posthoc_mapping.nearest_label_fallback": False}),
                    C("P21", **{"unknown_channel_exercised": True, "unknown_candidate": "T232", "novel_form_claimed": False})],
             evidence="P19: `NOT_RECOVERED_AT_SCOPE` is a typed outcome that must be preserved as a scientific result; P17 `UNKNOWN-1`: the post-hoc map is total and returns `UNKNOWN` for 8 of 12 clusters with no nearest-label fallback; P21: the `UNKNOWN` channel is exercised (`T232`) and reduced to a strongest parent without any novelty claim."),
    # ------------------------------------------------------------------ MTG-6
    33: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="REACHABLE_FRONTIER_FORMALIZED_AND_SEPARATED_FROM_OPTIMAL_FRONTIER",
             reason="P06 GVR-5 Pareto(M)∩R ⊆ Pareto(R) with the reverse inclusion refuted; P08 SEL-1 choice correspondence over the registered active set.",
             cites=[C("P06", **{"checks.pareto_relative_feasibility_hostile": True, "checks.pareto_census_zero_failures": True, "checks.strict_gap_witness": True, "parent_witness.budget_2.reachable_argmin": ["N_good"], "parent_witness.budget_2.global_argmin": ["X_ideal"]}),
                    C("P08", **{"checks.exhaustive_scalar_minimizer_pareto": True, "checks.reachable_optimum_not_better_than_global": True, "counts.small_grid_scalar_checks": 2044})],
             evidence="P06 `GVR-5`: the reachable frontier `F(theta) = Pareto(R(theta))` satisfies `Pareto(M) ∩ R ⊆ Pareto(R)` while `Pareto(R) ⊆ Pareto(M)` is refuted (a globally dominated candidate becomes reachable-efficient when its dominator is unreachable); `GVR-2`: reachable value equals the optimum iff a global optimizer is reachable (budget 2: `N_good` vs `X_ideal`); P08 `SEL-1`: the choice correspondence returns the Pareto frontier of the registered active set (2,044 exhaustive checks), reachable restriction kept subordinate to P06."),
    34: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="FINITE_BASE_REGIME_CROSSOVER_LAWS_UNDER_VECTOR_REPRICING",
             reason="P10 REPRICE-1 hyperplane law for any registered nonnegative price vector (memory/compute/communication/verifier coordinates included); P11 persistent-state price law lambda* = eta*p/2; P08 affine crossings.",
             cites=[C("P10", **{"checks.repricing_hyperplane_exact": True, "checks.dominance_no_flip": True, "census.repricing_cases": 1024, "census.dominance_no_flip_cases": 400, "census.strict_crossing_interval_cases": 26, "witness.one_dimensional_boundary": "1/2"}),
                    C("P11", **{"counts.heldout_transitions": 20, "checks.twenty_frozen_transitions_correct": True}),
                    C("P08", **{"witnesses.phase_crossings": ["2/5", "1/2", "3/5"], "checks.analytic_crossings_exact": True})],
             evidence="P10 `REPRICE-1`: under linear nonnegative vector repricing of any registered resource coordinates, pair order changes only on the hyperplane `v_i − v_j = p·(r_i − r_j)`, cells have constant order and quality/resource dominance forbids reversal (1,024 repricing cases, 400 no-flip, 26 strict crossings); P11: the persistent-state crossover law `lambda* = eta·p/2` predicts 20/20 held-out transitions; P08 `PHASE-1`: affine crossings `2/5, 1/2, 3/5`. Finite base regimes only."),
    35: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="SUFFICIENT_CONDITIONS_FOR_TRANSITION_COEXISTENCE_HYSTERESIS_AND_PATH_DEPENDENCE",
             reason="P08 PHASE-1A transition only at crossings; P10 NICHE-1a coexistence; P09 HIST-2 hysteresis band; P23 HYST-1 path dependence.",
             cites=[C("P08", **{"checks.phase_cells_expected": True, "checks.pareto_coexistence_preserved": True, "counts.affine_cell_checks": 507}),
                    C("P10", **{"checks.positive_mass_niches_coexist": True, "census.disjoint_unique_coexistence_cases": 18}),
                    C("P09", **{"checks.symmetric_hysteresis_census": True, "counts.symmetric_cases": 21, "witnesses.affine_thresholds": ["1/4", "3/4"]}),
                    C("P23", **{"checks.hysteresis_equal_ecology_path_dependence": True, "census.hysteresis_cases": 21})],
             evidence="Transition: P08 `PHASE-1A` — the argmin set is constant on crossing-free cells (507 checks), so a transition needs a registered pairwise crossing; coexistence: P10 `NICHE-1a` — disjoint unique winners in positive-mass niches suffice (18 cases) and P08 `SEL-3` keeps the full non-singleton frontier; hysteresis: P09 `HIST-2` — symmetric switching burden `kappa` gives the exact band `−kappa < c(B)−c(A) < kappa` (21 contexts, affine thresholds `1/4, 3/4`); path dependence: P23 `HYST-1` — inherited forms select differently under the same instantaneous ecology (21 cases)."),
    36: dict(bucket="HARNESS", disposition="EARNED", token="TRANSITION_PREDICTIONS_FROZEN_BEFORE_SEARCH",
             reason="P11: all 20 cases and predictions committed at the freeze before either outcome oracle existed; P12: predictions pushed before any training.",
             cites=[C("P11", **{"checks.twenty_frozen_transitions_correct": True, "counts.heldout_transitions": 20, "counts.endpoint_predictions": 40, "counts.endpoint_correct": 40}),
                    C("P12", **{"protocol_evaluation.terminal": "REAL_SYSTEM_TRANSITION_VALIDATED_AT_REGISTERED_SCOPE", "scientific_row_earned": True})],
             evidence="P11: the 20 held-out cases and their predicted transitions were frozen before either outcome search existed (freeze commit recorded in the package), then scored 20/20 transitions and 40/40 endpoints; P12: the real-system predictions were pushed before any training, with the custody chain V1→V2→V3 each committed before its outcomes."),
    37: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="PROSPECTIVE_HELDOUT_TRANSITIONS_UNDER_GRAMMAR_AND_SEARCH_REMINTS",
             reason="P11 predicts 20/20 held-out transitions under two search procedures and neutral candidate-ID relabelings, but no materially different GRAMMAR of the 65,552-candidate universe was applied. Closing here would narrow the row. Next tranche: re-run the P11 protocol under a second low-level encoding of the same transducer universe (frozen before outcomes)."),
    38: dict(bucket="HARNESS", disposition="EARNED", token="REPLICATED_ACROSS_SEARCH_PROCEDURES_AND_REAL_SYSTEMS_AT_REGISTERED_SCOPE",
             reason="P11 two source-separated search procedures agree on all 40 endpoints; P12 five real trained systems validate the transition under the protocol terminal.",
             cites=[C("P11", **{"checks.search_implementations_source_separated": True, "checks.independent_search_agreement_all_endpoints": True, "counts.independent_search_agreements": 40, "checks.search_strategies_materially_distinct": True}),
                    C("P12", **{"protocol_evaluation.qualifying_count": 5, "protocol_evaluation.terminal": "REAL_SYSTEM_TRANSITION_VALIDATED_AT_REGISTERED_SCOPE"})],
             evidence="P11: `FULL_ENUMERATION` and `RISK_FRONTIER_BRANCH_BOUND` are source-separated, materially distinct, and agree on all 40 held-out endpoints; P12: five distinct real trained systems (12 trained; 9 licensed all transition, 3 unlicensed correctly predicted not to) show the pre-frozen `PERSISTENT_STATE → STATELESS` transition under the registered repricing, terminal `REAL_SYSTEM_TRANSITION_VALIDATED_AT_REGISTERED_SCOPE`. Registered systems only; not calibration beyond them."),
    # ------------------------------------------------------------------ MTG-7
    39: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="NOVELTY_RELATIVE_TO_TRANSFORMATION_CLOSURE",
             reason="P18 NOVELTY-1 defines novelty as a semantic/resource/developmental archive distance (not name distance), but no package defines novelty relative to the TRANSFORM CLOSURE `∪_K B_b(K)` of a known registry under a declared budget. Next tranche: gmi-833-mtg-known-closure-v1 (COVER-1 + MTG-7 rows 39–43 together): registry of known classes, closure under the P04 antichain algebra at a frozen budget, UNKNOWN region = complement, nearest-known directed burden, holes = components disconnected from the registry."),
    40: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="UNFAMILIAR_SYNTAX_IS_NOT_NOVELTY",
             reason="P18 (26,793 syntactically distinct zero-distance pairs) and P21 (`T232` reduced to a classical truth table) establish the discipline at their scopes, but the row requires a mechanism class OUTSIDE registered known closure under a declared transform budget, which needs the closure object of row 39. Same next tranche."),
    41: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="UNKNOWN_REGIONS_AND_NEAREST_KNOWN_DIRECTED_BURDENS",
             reason="P17 defines UNKNOWN by exact-fingerprint non-identification and P18 a nearest-archive metric distance; neither is the nearest-known DIRECTED transform burden. Same next tranche."),
    42: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="LOW_COST_HOLES_AFTER_CALIBRATED_KNOWN_FORM_RECOVERY",
             reason="Requires the closure object and a calibrated known-form recovery over the same universe; neither exists on main for one universe. Same next tranche, after row 57 (COVER-1)."),
    43: dict(bucket="HARNESS", disposition="OPEN", token="UNKNOWN_FORM_CRITERIA_FROZEN_BEFORE_CANDIDATE_GENERATION",
             reason="P21 froze its discovery protocol before the held-out truth vector, which is the practice this row demands, but the criteria it froze are the AJ10 UNKNOWN-channel criteria, not the transformation-closure criteria of MTG-7. The row closes when the next tranche freezes closure-relative criteria before generating candidates."),
    44: dict(bucket="EXTERNAL-GATE", disposition="OPEN", token="STRONGER_PARENT_REFUSAL_MATCHED_SIMULATOR_BASELINES_AND_TRANSFER_TO_DISJOINT_ECOLOGIES",
             reason="Stronger-parent refusal exists (P21). Matched simulator baselines and transfer to disjoint ecology families do not exist for any unknown-form candidate; the row bundles three requirements and cannot close on one. Transfer to disjoint ecology families requires new ecologies (external data), so the bucket is EXTERNAL-GATE."),
    45: dict(bucket="HARNESS", disposition="EARNED", token="ONTOLOGICAL_COMPLETENESS_NOT_INFERRED_FROM_ABSENCE",
             reason="P22 forbids ALL_MACHINE_INTELLIGENCES_COMPLETELY_CLASSIFIED and records the unbounded undecidability boundary; P21 claims no novel form; P17 UNKNOWN is registry-relative non-identification.",
             cites=[C("P22", **{"forbidden_terminal": "ALL_MACHINE_INTELLIGENCES_COMPLETELY_CLASSIFIED", "unbounded_boundary.semantic_equivalence": "UNDECIDABLE_IN_GENERAL_AT_TURING_COMPLETE_SCOPE", "bounded_terminal": "COMPLETE_GMI_ATLAS_AT_BOUND_B"}),
                    C("P21", **{"novel_form_claimed": False, "unique_morphology_selected": False}),
                    C("P17", **{"checks.UNKNOWN_is_explicit_and_total": True})],
             evidence="P22 `AJ11`: bounded completeness is literal at the frozen bound (`COMPLETE_GMI_ATLAS_AT_BOUND_B`) while `ALL_MACHINE_INTELLIGENCES_COMPLETELY_CLASSIFIED` is a forbidden terminal because semantic equivalence is undecidable at Turing-complete scope; P21: no novel form claimed and none inferred from its absence; P17: `UNKNOWN` means registry-relative non-identification, never ontological novelty or completeness."),
    # ------------------------------------------------------------------ MTG-9 (governance)
    46: dict(bucket="HARNESS", disposition="GOVERNANCE_NOT_A_CLOSABLE_ROW", token="SMALL_DEPENDENCY_ORDERED_TRANCHES",
             reason="A working rule, not a claim: it is discharged per tranche by the dependency-ordered sequence TRANS-1/DIST-1 → TRANS-2 → GAUGE-1 → DIST-1B/TOPO-1A → RECOVER-1 already on main (each manifest's `depends_on` / base_main records the order) and by STACK-1's acyclic dependency check. Recorded, not checked off."),
    47: dict(bucket="HARNESS", disposition="EARNED", token="FREEZE_PRECEDES_IMPLEMENTATION_AND_EVIDENCE",
             reason="FRZ-1 census over the five programme packages: each manifest's freeze_commit exists, FREEZE_V1.md is present at it and RESULT_V1.json is absent at it (git cat-file and git ls-tree routes agree); this tranche's own freeze commit precedes all its implementation commits.",
             cites=[C("M01", **{"freeze_commit": "fea6549a700681c0e830bf53cc53ab4f2dd5535f"}), C("M02", **{"freeze_commit": "b48d236da8329012a3c234325d65ac70de640fa4"}),
                    C("M03", **{"freeze_commit": "8af4533512ae8ce97bfd062403e745eea8cfcbec"}), C("M04", **{"freeze_commit": "39894c4b5a25521d78568955f687a10a672bce42"}),
                    C("M05", **{"freeze_commit": "302ad7fed43b0e310b6e22252ceb21260edd865b"}),
                    C(MAP, **{"checks.frz1_all_programme_freezes_precede_results": True, "counts.frz1_packages": 5})],
             evidence="`gmi-833-mtg-map-v1` FRZ-1: for all 5 programme packages on `main` (TRANS-1/DIST-1, TRANS-2, GAUGE-1, DIST-1B/TOPO-1A, RECOVER-1) the manifest's `freeze_commit` is reachable, `FREEZE_V1.md` exists at it and no `RESULT_V1.json` exists at it — checked by `git cat-file -e` and independently by `git ls-tree`; this tranche's four freezes were committed at `fdd7255e` before any implementation file existed."),
    48: dict(bucket="HARNESS", disposition="GOVERNANCE_NOT_A_CLOSABLE_ROW", token="EXACT_AND_HOSTILE_CHECKS_BEFORE_PR",
             reason="A per-PR working rule enforced by each package's workflow (hostiles, null, two routes, byte-exact receipts run on every pull request). It has no terminal state to check off; it is recorded as the CI discipline every MTG package carries."),
    49: dict(bucket="HARNESS", disposition="GOVERNANCE_NOT_A_CLOSABLE_ROW", token="MERGE_ONLY_WHEN_CLAIM_CEILING_GREEN",
             reason="A merge rule. Every MTG package workflow asserts `manifest.claim_ceiling == receipt.claim_ceiling` and `verdict == GREEN` on the PR head; the repository has no required-checks protection, so enforcement is by the merging operator reading the check. Recorded, not checked off."),
    50: dict(bucket="HARNESS", disposition="GOVERNANCE_NOT_A_CLOSABLE_ROW", token="REREAD_FRESH_MAIN_AFTER_EVERY_MERGE",
             reason="A sequencing rule; its evidence is each successor freeze's `base_main` naming the predecessor's merge (P02 base_main names PR #860, P03 names TRANS-2 merged, P04 names GAUGE-1 merged). Not a checkbox with a terminal."),
    51: dict(bucket="HARNESS", disposition="EARNED", token="NEW_ASSUMPTIONS_AND_COUNTEREXAMPLES_REGISTERED_AS_DESCENDANT_GAPS",
             reason="SUCC-1 census: every programme manifest on main carries a non-empty `open_successors` list; this tranche's manifests do too, and its refuted first-run object is recorded as a descendant, not hidden.",
             cites=[C("M01", **{"open_successors": ["TRANS-2_DEVELOPMENTAL_NATURALITY", "DIST-1_VECTOR_QUANTALE_ENRICHMENT", "GAUGE-1_REMINT_EQUIVARIANCE", "COVER-1_KNOWN_FORM_CLOSURE", "RECOVER-1_P3_P4_RECOVERY", "PHASE-1_TRANSITION_LAWS", "LOFO-1_HELD_FAMILY_PREDICTION"]}),
                    C("M04", **{"open_successors": ["COMPLETE_QUANTALE_OR_ORDERED_MONOID_ENRICHMENT", "TOPOLOGY_STABILITY_UNDER_RESOURCE_COORDINATE_CHANGES", "COVER-1_KNOWN_FORM_CLOSURE", "RECOVER-1_P3_P4_RECOVERY", "PHASE-1_MORPHOLOGY_TRANSITION_LAWS"]}),
                    C(MAP, **{"checks.succ1_all_programme_manifests_register_successors": True, "counts.succ1_open_successor_entries": 22})],
             evidence="`gmi-833-mtg-map-v1` SUCC-1: all 5 programme manifests on `main` register non-empty `open_successors` (22 entries in all — e.g. P01 registers the quantale enrichment and LOFO-1, P04 registers topology stability under coordinate changes, both of which this tranche then took up); every manifest of this tranche registers its own successors, and the refuted first-run object of `gmi-833-mtg-groupoid-hom-v1` is recorded in its receipt rather than hidden."),
    52: dict(bucket="HARNESS", disposition="GOVERNANCE_NOT_A_CLOSABLE_ROW", token="REPEAT_UNTIL_CLOSED_OR_TERMINAL_NEVER_FORCE_POSITIVE",
             reason="The programme's stopping rule; it closes only when every registered MTG gap is positively closed or explicitly terminal, which this tranche does not claim (16 rows remain open). Recorded with the batching plan in STRUCTURAL_MAP.md."),
    # ------------------------------------------------------------------ Initial theorem sequence
    53: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="TRANS-1_FINITE_TRANSFORM_CATEGORY_AND_FAIL_CLOSED_COMPOSITION",
             reason="P01 earned_targets TRANS-1_FINITE_CATEGORY_KERNEL; GH extends the record.",
             cites=[C("P01", **{"checks.left_identity": True, "checks.right_identity": True, "checks.associativity": True, "checks.fail_closed_hostiles": True, "counts.hostile_cases": 6}), C(GH, **{"checks.hom1_identity_associativity_composition_laws": True, "checks.hom2_all_hostiles_detected": True})],
             evidence="P01 `TRANS-1A` (earned target `TRANS-1_FINITE_CATEGORY_KERNEL`): identities, associativity and additive composition on the typed record with 6 fail-closed cases; `gmi-833-mtg-groupoid-hom-v1` HOM-1/HOM-2 extend the record with interval, contract and tier fields (576 composable pairs, 11 fail-closed branches)."),
    54: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="TRANS-2_EXACT_DEVELOPMENTAL_NATURALITY_AND_STATIC_VS_DEVELOPMENTAL_HOSTILE",
             reason="P02 earned_target TRANS-2_EXACT_DEVELOPMENTAL_NATURALITY_FINITE_DETERMINISTIC with the static-only hostile.",
             cites=[C("P02", **{"checks.identity_natural": True, "checks.composition_natural": True, "checks.finite_trajectory_preservation": True, "checks.static_only_hostile_detected": True, "counts.static_only_naturality_violations": 2})],
             evidence="P02 `TRANS-2A` (earned target `TRANS-2_EXACT_DEVELOPMENTAL_NATURALITY_FINITE_DETERMINISTIC`): identity, composition and finite trajectory preservation of exact naturality, plus the static-only hostile with 2 commuting-square violations; approximate and stochastic extensions are `gmi-833-mtg-naturality-tiers-v1` NAT-1/NAT-4."),
    55: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="DIST-1_DIRECTED_SCALAR_DISTANCE_FROM_FROZEN_WEIGHTS_PLUS_PRIMARY_VECTOR_BURDEN",
             reason="P01 DIST-1A scalar kernel; P04 DIST-1B Pareto/vector burden primary with scalar projection.",
             cites=[C("P01", **{"checks.distance_identity_zero": True, "checks.triangle_violations_zero": True, "checks.raw_pareto_incomparability": True, "checks.scalarization_reversal": True}),
                    C("P04", **{"checks.pareto_algebra_exact": True, "checks.scalar_triangle_all_registered_weights": True, "checks.scalarization_information_loss_hostile": True, "checks.coordinatewise_infimum_unattainable_hostile": True})],
             evidence="P01 `DIST-1A`: `d_w` from frozen positive weights is a directed pseudometric (identity zero, directed triangle) and the raw Pareto vector stays primary (scalarization can reverse incomparable pairs); P04 `DIST-1B`: the vector/Pareto burden `H(M,N)` is the primary object, the scalar projection is information-losing (two frontiers with the same scalar under one price, different under another) and coordinatewise infimum is refused as unattainable."),
    56: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="GAUGE-1_RELABELING_EQUIVARIANCE_FOR_MECHANISM_CONCLUSIONS",
             reason="P03 earned_target GAUGE-1_FINITE_SEMANTIC_REMINT_EQUIVARIANCE.",
             cites=[C("P03", **{"checks.identity_remint": True, "checks.inverse_remint": True, "checks.composition_remint": True, "checks.canonical_fingerprint_invariant": True, "checks.quotient_transform_geometry_invariant": True, "checks.semantic_mutation_hostiles_detected": True, "checks.search_invariance_not_inferred": True})],
             evidence="P03 `GAUGE-1A` (earned target `GAUGE-1_FINITE_SEMANTIC_REMINT_EQUIVARIANCE`): relabelings form a groupoid, the canonical fingerprint and quotient transform-distance matrix are invariant, 6 semantic-mutation hostiles are detected and search invariance is explicitly not inferred; `gmi-833-mtg-groupoid-hom-v1` GRP-1/GRP-2 lift the action to derivation records."),
    57: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="COVER-1_BOUNDED_KNOWN_FORM_CLOSURE_AT_FROZEN_REGISTRY",
             reason="No package computes the transform/reachability closure of a frozen known-family registry. RA-1 refuses closing it by citing P17 (its forbidden set contains KNOWN_FAMILY_RECOVERY_BEYOND_FOUR_SUPPLIED_FINGERPRINTS) and P20 (REAL_SCALE_ALL_FAMILY_RECOVERY). Next tranche: gmi-833-mtg-known-closure-v1, batched with MTG-7 rows 39–43."),
    58: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="RECOVER-1_P3_P4_NEUTRAL_DEVELOPMENTAL_RECOVERY",
             reason="P05 earned RECOVER-1A/1B by exhaustive SEARCH from a neutral state at P3-relative level; the row also names DEVELOPMENTAL recovery (an update-law trajectory reaching the form), which no package shows. Closing on the search half would narrow the row. Next tranche: repeat the P05 protocol with a registered update law from a neutral seed (P16 laws), frozen before outcomes."),
    59: dict(bucket="EXACT-FORMAL", disposition="EARNED", token="PHASE-1_ECOLOGY_RESOURCE_TO_FORM_TRANSITION_LAW",
             reason="P08 PHASE-1 affine phase boundaries; P10 REPRICE-1; P11 prospective law; P12 real-system validation.",
             cites=[C("P08", **{"checks.analytic_crossings_exact": True, "checks.affine_census_no_cell_violations": True, "counts.affine_triples": 84}),
                    C("P10", **{"checks.repricing_transition_exact": True, "census.repricing_cases": 1024}),
                    C("P11", **{"checks.twenty_frozen_transitions_correct": True, "checks.incorrect_shifted_threshold_falsified": True, "counts.shifted_threshold_failures": 20}),
                    C("P12", **{"protocol_evaluation.qualifying_count": 5})],
             evidence="P08 `PHASE-1`: transitions occur only at exact affine crossings (84 triples, 507 cell checks); P10 `REPRICE-1`: the vector repricing hyperplane law (1,024 cases); P11: the law `lambda* = eta·p/2` predicts 20/20 frozen held-out transitions and a shifted law fails 20/20; P12: five real trained systems validate it. A finite registered law family, not a universal phase law."),
    60: dict(bucket="NEW-SCIENCE", disposition="OPEN", token="LOFO-1_LEAVE_ONE_FAMILY_OUT_FROZEN_PREDICTION_UNDER_REMINTS",
             reason="No leave-one-family-out frozen prediction exists: the Section-H ledger records held-out frozen prediction missing on 39 of 43 family rows, and RA-1 refuses closing LOFO-1 by citing P20 because its forbidden set contains PREDICTED_SELECTED_FOR_ALL_FAMILIES (P26 likewise forbids PREDICTED_SELECTED). Next tranche after COVER-1: freeze an architecture-name-free structural-pressure prediction for one held-out family, then search under two grammars and two searchers."),
}


def all_indices():
    return sorted(ROWS)
