"""Source of truth for the ORION concept validation atlas.

Every concept that could materially affect cognition is recorded here as a
*hypothesis under test*, never as a feature requirement.  The atlas exists to
make three things impossible to fudge:

1. **Implementation is not scientific support.**  ``implementation_status`` and
   ``scientific_status`` are separate fields and a concept may be fully built and
   still sit at ``THEORY_ONLY`` or ``PARENT_SUFFICIENT``.
2. **Existing negative results survive.**  ``preserved_terminals`` carries the
   exact terminal strings already recorded elsewhere in the repository, with
   their source.  New work may add a *new* pre-registered study; it may not
   reinterpret an old receipt.
3. **Every concept can die.**  ``falsifier`` and ``disposition`` are mandatory.
   A concept with no measurable incremental value is dropped, and a concept a
   parent explains is merged into that parent.

``atlas.py`` renders this into ``ORION_CONCEPT_VALIDATION_ATLAS_V1.json`` and its
human twin.  Nothing is transcribed by hand twice.
"""

from __future__ import annotations

SCIENTIFIC_STATUS = (
    "THEORY_ONLY", "IMPLEMENTED_UNTESTED", "CALIBRATED", "CAUSALLY_SUPPORTED",
    "FRESH_TRANSFER_SUPPORTED", "CROSS_FAMILY_SUPPORTED", "CROSS_DOMAIN_SUPPORTED",
    "PARENT_SUFFICIENT", "REFUTED", "HARMFUL", "NON_IDENTIFIABLE", "CANNOT_CHECK",
)

DISPOSITIONS = ("KEEP", "ADAPT", "MERGE", "DROP", "SPLIT")

SIGNATURES = (
    "causal_reusable_method_acquisition", "method_composition", "scoped_failure_learning",
    "amortized_future_acquisition", "amortized_future_reasoning", "sparse_relevant_cognition",
    "local_revision", "persistent_restartable_competence", "safe_negative_transfer_refusal",
    "cross_family_transfer", "cross_domain_cognitive_transfer",
    "governed_representation_operator_evolution", "bounded_recursive_self_improvement",
)


def C(**kw):
    base = dict(
        concept_id="", source_repository="", source_artifact="", formal_definition="",
        explicit_nondefinition="", strongest_parents=(), ocm_observable_state="", trigger="",
        proposed_ocm_mechanism="", information_available_to_mechanism="", positive_case_family="",
        negative_twin="", hostile_case="", ablation="", resource_coordinates=(),
        cross_family_test="", cross_domain_test="", interaction_dependencies=(), falsifier="",
        disposition="", disposition_reason="", implementation_status="", scientific_status="",
        preserved_terminals=(), signatures=(), paper_role="", reopen_condition="", pilot_rank=None,
    )
    base.update(kw)
    return base


CONCEPTS = [

C(concept_id="SCOPED_FAILURE_KNOWLEDGE", pilot_rank=1,
  source_repository="ORION-OCM", source_artifact="#62 §4; #143 §3; kso/nogoods.py; selfmodel/model.py",
  formal_definition="A record that a named method failed on a named task under a named assumption set, representation, evidence set and resource bound, together with the diagnosed responsibility, the exclusions that diagnosis justifies, the alternatives still live, the successes preserved, the scope, and the conditions under which the exclusion reopens.",
  explicit_nondefinition="NOT a memory that an attempt failed. NOT impossibility. NOT a blacklist keyed on task identity. A failure under one method and budget is never promoted to impossibility.",
  strongest_parents=("ATMS nogoods (de Kleer 1986)", "JTMS dependency-directed backtracking", "CEGIS", "Reflexion-style transcript summaries", "nearest-neighbour failure retrieval", "continual-learning replay"),
  ocm_observable_state="FailureStore exclusions keyed on (method, assumption-set); reopen index over assumptions",
  trigger="a checked attempt terminates without a certified solution",
  proposed_ocm_mechanism="diagnose the cause; create an exclusion only for REFUTED_BY_CHECKER or ASSUMPTION_VIOLATED; key it on the assumption set; reopen exactly when a depended-on assumption changes",
  information_available_to_mechanism="the attempt trace, the checker verdict, the assumption set in force, the budget consumed. Not the ground-truth label of unprobed positions.",
  positive_case_family="method learned on SUB(S1) fails on SUB(S2); a fresh S2 task avoids the same dead end",
  negative_twin="an unrelated family where the exclusion must not fire",
  hostile_case="same failure label, different root cause; budget exhaustion; non-identifying probe; evaluator defect; changed assumptions; permanent broken-shut",
  ablation="remove the failure store; replace with a task-ID blacklist; replace with cause-blind nogood exclusion",
  resource_coordinates=("search_expansions", "checker_calls", "persistent_state_bytes", "revision_work"),
  cross_family_test="exclusion learned on subtraction families must not suppress a Nim family it does not scope",
  cross_domain_test="diagnosis method frozen before language access, applied to clarification failure",
  interaction_dependencies=("SATURATION", "OBSTRUCTION_DIAGNOSIS", "REOPENING_LOCAL_REVISION"),
  falsifier="a cause-blind nogood parent matches on repeated-work avoidance AND on reopening after regime change",
  disposition="ADAPT", disposition_reason="the failure-epistemology closure already froze the strongest-parent gap at 0/32 and assigned the mechanism to TMS/nogood plus responsibility. Its OWN stated falsifier is that ORION beats the strong parent on a scientifically meaningful protected coordinate. The pilot is therefore run as an attempt at that falsifier, with expectation PARENT_SUFFICIENT, and is narrowed to the one coordinate the closure did not fix: reopening keyed on assumptions after a regime change.",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="IMPLEMENTED_UNTESTED",
  preserved_terminals=(
    "FAILURE_MEMORY_USEFUL_BUT_STANDARD_METHODS_SUFFICIENT (ORION/research/extensions/orion-jump-recursive-atoms/failure_epistemology/FAILURE_EPISTEMOLOGY_CLOSURE_V1.md) - a subsumption result; the strongest-parent incremental gap was frozen at 0/32 BEFORE execution",
    "TMS_NOGOOD_PLUS_RESPONSIBILITY_SUFFICIENT (failure-to-scoped-negative-knowledge atom, FAILURE_ATOM_PILOT_CLOSURE_V1.md)",
    "P7_TRANSPORT_SUFFICIENT (negative-knowledge staleness atom, same file)",
    "MULTIPLE_FAILURE_SIGNAL_ATOMS_REQUIRED (silent-failure observability atom)",
    "MEG-16 checked exhaustively at n=3 (kso/nogoods.py)",
    "no lifetime failure-memory benefit has ever been measured"),
  signatures=("scoped_failure_learning", "local_revision", "safe_negative_transfer_refusal"),
  paper_role="P2 primary discriminator",
  reopen_condition="if a nogood parent matches, re-scope the claim to the reopening endpoint only"),

C(concept_id="COGNITIVE_SATURATION", pilot_rank=2,
  source_repository="ORION-OCM", source_artifact="#72; RECURSIVE_KSO_ARCHITECTURE_V1.md §7; research/programme/ORION_CONCEPTS.md",
  formal_definition="For a registered representation R, operator/method space O, evidence E, allowed probe set A and resource bound B, the reachable search space has been validly closed under the registered contract. Terminal: SATURATED_WITHIN_REGISTERED_SPACE.",
  explicit_nondefinition="NOT research/donor literature saturation, which is about coverage of a survey procedure. NOT PROBLEM_IMPOSSIBLE, which requires an independent proof. NOT authority to Jump. A plateau cannot establish that no solution exists.",
  strongest_parents=("abstract interpretation fixed points", "solver completeness certificates", "equality saturation / egglog", "exhaustive search with a closure certificate"),
  ocm_observable_state="version space survivors; the set of probes that would split them",
  trigger="no allowed probe separates two surviving hypotheses",
  proposed_ocm_mechanism="declare saturation scoped to (R,O,A,B) and pass it to obstruction diagnosis as one input among several",
  information_available_to_mechanism="the surviving version space and the permitted probe set only",
  positive_case_family="W8: two extensionally identical hypotheses survive every probe",
  negative_twin="W1: a splitting probe exists, so the space is not saturated",
  hostile_case="W1H: budget spent while a splitting probe exists — exhaustion, not saturation",
  ablation="treat saturation as authority to change representation (the saturation parent)",
  resource_coordinates=("search_expansions", "index_probes", "checker_calls"),
  cross_family_test="the same saturation test over Nim combiner languages and subtraction period languages",
  cross_domain_test="saturation of a proof-tactic space under a fixed tactic vocabulary",
  interaction_dependencies=("SEARCH_MORE_VS_JUMP", "SCOPED_FAILURE_KNOWLEDGE"),
  falsifier="a solver-closure parent produces the same scoped terminal with the same accuracy",
  disposition="SPLIT", disposition_reason="research/donor saturation and cognitive saturation were one word for two mechanisms; they are separated here and only the cognitive one is a programme object",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="CALIBRATED",
  preserved_terminals=(
    "'Open-ended cognitive saturation is not established' (research/programme/ORION_CONCEPTS.md)",
    "TARGETED_SEARCH_ONLY_NOT_SATURATION (RCL_NOVELTY_SEARCH_AND_RESIDUAL_V0.json)",
    "AUDIT FINDING: every operative sense of saturation in ORION V1 and V2 is search-coverage saturation of a declared literature/donor universe (FOUNDATION_SATURATION_PROTOCOL_V1.md). Cognitive saturation is UNCLAIMED TERRITORY in both repositories; introducing it here is a new concept, not an ORION term, and must not be attributed to ORION."),
  signatures=("governed_representation_operator_evolution",),
  paper_role="P2 supporting mechanism",
  reopen_condition="if an independent generator produces worlds the policy has not seen and accuracy holds"),

C(concept_id="SEARCH_MORE_VS_JUMP", pilot_rank=2,
  source_repository="ORION-OCM + ORION-V2", source_artifact="#72 §6; kso/jump.py; kso/navigation.py KS-T19",
  formal_definition="SEARCH_MORE keeps representation, operator vocabulary and problem formulation fixed and adds budget, order or probes. A Jump changes representation, abstraction, operator vocabulary, problem formulation, measurement interface, control policy or framework, and requires incumbent closure, a witnessed obstruction, evidence that lower repair is insufficient, a candidate transformation, frozen predictions, preservation obligations, independent validation and external adoption authority.",
  explicit_nondefinition="Timeout, low score, repeated failure, uncertainty and failed retrieval are NOT Jump witnesses. Saturation alone is not a Jump witness.",
  strongest_parents=("CEGAR abstraction refinement", "CEGIS vocabulary extension", "version-space collapse policies", "active learning probe selection", "Soar impasse and chunking", "architecture search"),
  ocm_observable_state="diagnosed escalation level L0..L6 with an exhibited witness where one exists",
  trigger="the incumbent fails to identify",
  proposed_ocm_mechanism="exclude every cheaper explanation in order before proposing a more expensive one; require an exhibited witness for any level at or above the Jump threshold",
  information_available_to_mechanism="observed evidence, surviving version space, permitted probes, remaining budget. Never the ground-truth level.",
  positive_case_family="W3 local repair, W4 operator insufficiency, W5 representation non-identifying, W6 formulation defect",
  negative_twin="W7: the incumbent already identifies and any escalation is overreach",
  hostile_case="W1H budget exhaustion; W2 the evidence channel rather than the representation is binding",
  ablation="timeout parent, saturation parent, CEGAR parent given identical visible state",
  resource_coordinates=("search_expansions", "checker_calls", "revision_work"),
  cross_family_test="subtraction period defects and Nim combiner defects in one suite",
  cross_domain_test="the same level ladder over proof-tactic and controlled-language failures",
  interaction_dependencies=("COGNITIVE_SATURATION", "OBSTRUCTION_DIAGNOSIS", "REPRESENTATION_CHANGE"),
  falsifier="a fully-resourced verified-regime-revision parent matches minimum-sufficient-level accuracy AND false-escalation rate on an independently generated draw. Note this parent has ALREADY tied on the binary decision, so only the seven-level version is open.",
  disposition="ADAPT", disposition_reason="the BINARY jump/no-jump decision is already closed against a fully-resourced parent (ORION V1 zero-error Jump: protected incremental gap exactly zero). What replicated across ME-X2 V1 and V3 is narrower: the FALSE-ESCALATION ASYMMETRY (M 0 versus B5 21, then 0 versus 14) while overall accuracy was a loss and then a parity. The concept is therefore re-scoped to minimum-sufficient-level selection across seven levels, with false-escalation rate as the primary endpoint, because that is the only coordinate on which a residual has ever survived replication.",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="CALIBRATED",
  preserved_terminals=(
    "REGIME_INVENTION_WITHOUT_INCREMENTAL_VALUE (ORION/research/extensions/orion-jump-recursive-atoms/zero_error_jump/JUMP_PROGRAMME_CLOSURE_V1.md)",
    "REPRESENTATION_INVENTION_NO_INCREMENTAL_VALUE; VERIFIED_REGIME_REVISION_PARENT matched ORION on every protected metric; ORION's protected incremental gap is exactly zero (ZERO_ERROR_JUMP_CLOSURE_V2.md)",
    "ME-X2 PARENT_SUFFICIENT (B5_DOMINATES): M 0.963 vs B5 0.983, exact p=0.0032 - the parent WON",
    "ME-X2 V3 THRESHOLD_NULL: parity on a fresh seed (+0.0017, p=0.845); the V1 loss did not replicate as a loss",
    "ME-X2 and V3 replicated asymmetry: M false escalations 0 vs B5 21, then 0 vs 14",
    "M_ALWAYS_ESCALATE_WHEN_STUCK ablation: 848 false escalations, 115 specification damages",
    "M4_FINITE_GOVERNED_JUMP_GREEN, but the extension was AUTHORED not invented",
    "M11 S5/S6 SUPPORTED at n=1 only"),
  signatures=("governed_representation_operator_evolution", "bounded_recursive_self_improvement"),
  paper_role="P2 flagship discriminator",
  reopen_condition="a confirmatory result requires worlds generated by a process independent of the policy's author; the present generator shares the policy's theory of what the defect is, which is the FAILURE_LEDGER pattern STRUCTURALLY_DETERMINED_REGISTERED_CLAUSE and is recorded as such"),

C(concept_id="FIBRES_MULTISCALE_TRANSPORT", pilot_rank=3,
  source_repository="ORION-OCM", source_artifact="#8/#10 M8; organisation/; kso/abstraction.py; research/programme/ORION_CONCEPTS.md",
  formal_definition="Overlapping local knowledge spaces with typed correspondences, where transport composes warrants: Lambda(transported) = Lambda(source) tensor Lambda(correspondence).",
  explicit_nondefinition="NOT a mandatory topology. NOT retained because the mathematics is attractive. The V1 development fibre, the observational indistinguishability class and the OCM scope fibre are three different objects and must not be conflated.",
  strongest_parents=("ordinary database index", "flat graph", "hierarchical graph / lumpability (Kemeny-Snell)", "graph partitioning and label propagation", "modular planning", "learned routing", "neural memory / retrieval"),
  ocm_observable_state="k touched objects per query, index probes, transport records, stale transports after revocation",
  trigger="a query scoped to a family",
  proposed_ocm_mechanism="scoped local lookup with dependency links, so that revocation of shared support marks exactly the transports that went stale",
  information_available_to_mechanism="family identity and the dependency graph; never the answer",
  positive_case_family="local fibre competence with cross-fibre bridges and shared support",
  negative_twin="unrelated fibres that must be untouched and unaffected",
  hostile_case="a globally shared support whose revocation must NOT look local; an index built by scanning all N",
  ablation="global scan with no index; index parent with no dependency tracking; cache parent storing positions",
  resource_coordinates=("N_persistent_objects", "k_touched_objects", "index_probes", "index_bytes", "index_maintenance_work", "persistent_state_bytes", "query_cpu_seconds"),
  cross_family_test="query work under growing unrelated distractor competence",
  cross_domain_test="transport of a DISTINGUISH method from games to counterexample selection",
  interaction_dependencies=("SPARSE_ACTIVE_SUBSPACE", "REOPENING_LOCAL_REVISION", "CONSOLIDATION"),
  falsifier="an ordinary index matches k(N) and query work, and also matches stale-transport detection after revocation",
  disposition="ADAPT", disposition_reason="query-work sparsity is almost certainly PARENT_SUFFICIENT; the only defensible residual is stale-transport detection after revocation, so the claim is narrowed to that",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="PARENT_SUFFICIENT",
  preserved_terminals=(
    "M8_PARENT_SUFFICIENT_AT_THIS_SCALE (docs/provenance/M8_RECEIPT_V1.json)",
    "M8 language stream: fibres answered 6/18, 12 REFINE_REQUIRED, 0 transports",
    "P6_METHOD_FIBRE_FORMALISM_NARROWED (ORION/research/extensions/p6-method-fibres/)",
    "TOP_TIER_SUCCESSOR_NOT_SUPPORTED__BOUNDED_RETAINED (ORION-02 FiberGuard): the lexical control matched or beat the registered geometry in BOTH revival rounds",
    "MEG-09 multiscale navigation reduces to parent lumpability and intertwining (ORION-V2 ME_FRONTIER_F2_MULTISCALE_PARENT_REDUCTION_V1.md)",
    "KSO_REPRESENTATION_ABSTRACTION_V1.md §7: every organisation candidate's valid terminal is PARENT_SUFFICIENT"),
  signatures=("sparse_relevant_cognition", "local_revision"),
  paper_role="P3 supporting; not a headline",
  reopen_condition="only a new pre-registered held-out study may revisit M8; the old receipt is not reinterpretable"),

C(concept_id="SPARSE_ACTIVE_SUBSPACE",
  source_repository="ORION-OCM", source_artifact="#50/#62; kso/navigation_sparse.py; COGNITIVE_LADDER_SCALING_V1.md ME-SCALE-1",
  formal_definition="A query-conditioned working set K(q) whose whole-query cost tracks k rather than N after charging index build, maintenance, routing, materialisation, refinement, verification, storage and failed searches.",
  explicit_nondefinition="A sparse stored graph with dense all-row iteration is NOT sparse cognition. k is instrumented at the point of touch, never inferred from result-set size.",
  strongest_parents=("database indexes and materialised views", "personalised PageRank local partitioning (Andersen-Chung-Lang)", "approximate nearest neighbour", "neural retrieval"),
  ocm_observable_state="k, k/N, index_probes, index build and maintenance work, crossover query count",
  trigger="any query against a grown store",
  proposed_ocm_mechanism="scoped index with charged construction; report CANNOT_CHECK for any path that can scan uninstrumented",
  information_available_to_mechanism="family identity and index structure",
  positive_case_family="frozen probe families at scales 1x/3x/10x/30x",
  negative_twin="global-scan ablation whose k must track N",
  hostile_case="index construction that scanned all N; storage growth hiding cheap queries",
  ablation="global scan; unindexed store",
  resource_coordinates=("N_persistent_objects", "k_touched_objects", "index_probes", "index_bytes", "index_maintenance_work", "persistent_state_bytes"),
  cross_family_test="frozen probes held constant while unrelated competence grows",
  cross_domain_test="deferred to CL-10",
  interaction_dependencies=("FIBRES_MULTISCALE_TRANSPORT", "CONSOLIDATION"),
  falsifier="k grows near-linearly in N, or the crossover query count is never reached within the registered lifetime",
  disposition="ADAPT", disposition_reason="reframed around the crossover query count, which is the only form of the claim that survives the index-construction hostile",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="IMPLEMENTED_UNTESTED",
  preserved_terminals=("navigation_sparse.py is adjacency-sparse but its fixed point still updates every state row; it is not yet evidence for O(k) task cost", "default exact solve computes four dense restart fixed points"),
  signatures=("sparse_relevant_cognition",),
  paper_role="P3 primary",
  reopen_condition="if the indexed parent matches, report PARENT_SUFFICIENT on k(N) and keep only the revocation endpoint"),

C(concept_id="REUSABLE_METHOD_ACQUISITION",
  source_repository="ORION-OCM", source_artifact="#62; learning/methods.py; COGNITIVE_LADDER_PROTOCOL_V1.md CL-D1",
  formal_definition="A method is an object satisfying CL-D1: it compresses its source episodes strictly, its verified scope strictly exceeds its training support with certification beyond training magnitude, and the certifying checker is independent of it.",
  explicit_nondefinition="NOT an answer cache. NOT similarity retrieval. Presence in memory is not use; a reuse claim needs an execution-trace witness.",
  strongest_parents=("persistent memoisation across restarts", "DreamCoder / Stitch library learning", "Soar chunking", "skill libraries with embedding retrieval", "small neural model checkpointed across restarts"),
  ocm_observable_state="MethodRecordV1 with description_bits, admissibility verdict and bits accounting",
  trigger="a set of checked solved episodes",
  proposed_ocm_mechanism="induce the shortest consistent hypothesis in the registered language; admit only under CL-D1",
  information_available_to_mechanism="the checked episodes and the registered language; never held-out labels",
  positive_case_family="periodic Grundy rules over subtraction families",
  negative_twin="a decoy consistent with training and wrong beyond it",
  hostile_case="a matched-byte answer cache; a structural placebo drawn from the decoy pool",
  ablation="A_removed, A_revoked, A_placebo, A_cache; the primary estimand is placebo minus live",
  resource_coordinates=("search_expansions", "checker_calls", "persistent_state_bytes", "acquisition_cpu_seconds"),
  cross_family_test="a rule learned on one move set applied to another",
  cross_domain_test="deferred to CL-8",
  interaction_dependencies=("CONSOLIDATION", "SCOPED_FAILURE_KNOWLEDGE"),
  falsifier="the placebo arm reproduces the effect, or persistent memoisation matches on positions beyond training magnitude",
  disposition="KEEP", disposition_reason="this is the programme's base signature; without it nothing above it means anything",
  implementation_status="PILOT_IMPLEMENTED_THIS_TRANCHE",
  scientific_status="IMPLEMENTED_UNTESTED",
  preserved_terminals=("M9_CANNOT_CHECK_FOR_SUPPORTED_AT_THIS_N (n=9, OCM-authored environments)", "Stitch abstraction result was a checked primitive alias, not useful-operator acquisition", "inc/square search slots 35->15 and 37->19 is a small library-learning mechanism, not general cognitive growth"),
  signatures=("causal_reusable_method_acquisition", "persistent_restartable_competence"),
  paper_role="P1 primary",
  reopen_condition="none; this is the entry gate"),

C(concept_id="METHOD_COMPOSITION",
  source_repository="ORION-OCM", source_artifact="#143 CL-2",
  formal_definition="Two methods acquired from disjoint training families enable a fresh task requiring both, with no combined solution present in training.",
  explicit_nondefinition="NOT a single method that happens to cover both families.",
  strongest_parents=("meta-learning", "program synthesis over a learned library", "hierarchical planning"),
  ocm_observable_state="two ReuseEventV1 records with distinct method ids on one task",
  trigger="a task in the SUBNIM family requiring a per-heap rule and a combiner",
  proposed_ocm_mechanism="acquire the per-heap rule on one-heap subtraction and the combiner on Nim, then compose",
  information_available_to_mechanism="the two training streams, kept disjoint by construction",
  positive_case_family="SUBNIM(S,k): needs the SUB(S) Grundy rule and the XOR combiner",
  negative_twin="a family solvable by either method alone",
  hostile_case="training that leaks a combined example",
  ablation="remove A only, remove B only, remove both",
  resource_coordinates=("search_expansions", "checker_calls"),
  cross_family_test="new move sets not seen in either training stream",
  cross_domain_test="deferred",
  interaction_dependencies=("REUSABLE_METHOD_ACQUISITION",),
  falsifier="removing either method leaves performance unchanged, i.e. the task never needed the composition",
  disposition="KEEP", disposition_reason="SUBNIM makes composition structural rather than staged: neither training family contains the combined solution",
  implementation_status="GAME_FAMILY_READY_MECHANISM_PENDING",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("M7 RQ3 compositional_reuse CANNOT_CHECK (n below pre-registered minimum)",),
  signatures=("method_composition",),
  paper_role="P2 primary",
  reopen_condition="none"),

C(concept_id="REOPENING_LOCAL_REVISION",
  source_repository="ORION-OCM", source_artifact="kso/revocation.py KS-T09/T22",
  formal_definition="On a support change, exactly the dependency cone reopens; REOPEN is the liveness-changed part, RECHECK survives through alternative support, UNAFFECTED is the no-alarm control.",
  explicit_nondefinition="NOT global recomputation. Locality that is guaranteed by task design is not evidence of locality.",
  strongest_parents=("JTMS (Doyle 1979)", "ATMS label update (de Kleer 1986)", "self-adjusting computation (Acar)", "differential dataflow", "provenance semirings"),
  ocm_observable_state="cone size, stale survivors, collateral invalidations, recovery work",
  trigger="revocation or reinstatement of a support",
  proposed_ocm_mechanism="dependency-closed impact cone with three-valued liveness",
  information_available_to_mechanism="the dependency graph and the revoked set",
  positive_case_family="local support revocation with a small true cone",
  negative_twin="unrelated objects that must stay live",
  hostile_case="a genuinely global dependency cone, so locality is not guaranteed by task design",
  ablation="global recomputation; index parent with no dependency tracking",
  resource_coordinates=("revision_work", "recovery_work", "index_maintenance_work"),
  cross_family_test="revocation across families in one store",
  cross_domain_test="deferred",
  interaction_dependencies=("FIBRES_MULTISCALE_TRANSPORT", "SCOPED_FAILURE_KNOWLEDGE"),
  falsifier="a TMS parent matches cone exactness and cost, or the global-cone hostile shows locality was benchmark-imposed",
  disposition="KEEP", disposition_reason="mechanism is proved exact; what is unmeasured is whether it buys anything a TMS parent does not",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="PARENT_SUFFICIENT",
  preserved_terminals=("M7 RQ1 ocm-no_revocation PARENT_SUFFICIENT (52/54 vs 53/54)", "KS-P1 retraction law PARENT_PRODUCT_OWNED", "M12 F stale 0, dependents reopened 3/3 but DESCRIPTIVE"),
  signatures=("local_revision",),
  paper_role="P3 supporting",
  reopen_condition="a new pre-registered study with the global-cone hostile included"),

C(concept_id="RECURSIVE_DECOMPOSITION",
  source_repository="ORION-OCM + ORION V1", source_artifact="kso/abstraction.py; RECURSIVE_KSO_ARCHITECTURE_V1.md",
  formal_definition="A decomposition must declare subproblem identities, interfaces, shared assumptions, couplings, a recomposition rule, global obligations, and order or non-commutation constraints. Total solve work includes recomposition.",
  explicit_nondefinition="NOT rewarded for producing more subproblems. A macro cell is a routing accelerator, never an authority source.",
  strongest_parents=("dynamic programming", "AND/OR search", "hierarchical planning", "operads and hypergraph categories (Fong-Spivak)", "Soar chunking", "neural planning"),
  ocm_observable_state="subproblem records, recomposition cost, depth, fragmentation count",
  trigger="a task whose state space factors",
  proposed_ocm_mechanism="decompose only under a declared interface with a recomposition obligation",
  information_available_to_mechanism="the declared interfaces; never the global solution",
  positive_case_family="independent multi-heap games where per-heap decomposition is exact",
  negative_twin="coupled worlds where decomposition is harmful",
  hostile_case="local solutions that do not glue globally; over-fragmentation; unbounded recursion depth",
  ablation="flat search on the same task",
  resource_coordinates=("search_expansions", "composition_work", "checker_calls"),
  cross_family_test="decomposition learned on Nim applied to SUBNIM",
  cross_domain_test="proof decomposition at CL-8",
  interaction_dependencies=("METHOD_COMPOSITION", "LOCAL_TO_GLOBAL_OBSTRUCTION"),
  falsifier="total work including recomposition exceeds flat search, or a coupled world shows decomposition is harmful and the machine still decomposes",
  disposition="ADAPT", disposition_reason="must be scored on total work including recomposition, and must include a coupled world where the right answer is not to decompose",
  implementation_status="PARTIAL_IN_SRC_OCM",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("'learned recursive organisation remains unproved' (research/programme/ORION_CONCEPTS.md)",),
  signatures=("method_composition", "cross_family_transfer"),
  paper_role="P3 supporting",
  reopen_condition="none"),

C(concept_id="REPRESENTATION_CHANGE",
  source_repository="ORION-OCM", source_artifact="kso/jump.py L3; #143 CL-3; methods.py CombinerLanguage",
  formal_definition="Adoption of a new representation or operator vocabulary with transport, preservation obligations, an independent check and a measured benefit, driven by evidence rather than by benchmark identity. Requires a held-out world where the old and new representations disagree and the new one is correct.",
  explicit_nondefinition="NOT selection from a two-item hand-picked menu. NOT justified by a plateau.",
  strongest_parents=("learned embeddings and neural representation learners", "CEGAR", "version-space learning", "MDL model selection"),
  ocm_observable_state="RepresentationChangeV1 with held_out_discrimination and construction cost",
  trigger="a witnessed non-identifiability of the incumbent representation",
  proposed_ocm_mechanism="exhibit a colliding pair, then adopt the minimum representation that separates it",
  information_available_to_mechanism="observed labels and the registered representation menu with its size",
  positive_case_family="token-total representation collides on Nim; heap-tuple separates",
  negative_twin="a world where the incumbent already identifies",
  hostile_case="a deliberately misleading representation that fits training and fails held-out",
  ablation="charge representation search and construction cost; compare to a neural representation learner",
  resource_coordinates=("search_expansions", "acquisition_cpu_seconds", "persistent_state_bytes"),
  cross_family_test="the same menu across subtraction and Nim families",
  cross_domain_test="controlled-language interpretation at CL-9",
  interaction_dependencies=("SEARCH_MORE_VS_JUMP", "CONSOLIDATION"),
  falsifier="prior_bits shows the menu was small enough that the answer was given, not learned",
  disposition="KEEP", disposition_reason="the combiner language contains five decoys that are provably indistinguishable from XOR on binary Grundy values, so the discrimination is structural",
  implementation_status="LANGUAGE_IMPLEMENTED_MECHANISM_PENDING",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("M4 finite ceiling was reached with a SUPPLIED conjunction feature",),
  signatures=("governed_representation_operator_evolution",),
  paper_role="P2/P3",
  reopen_condition="none"),

C(concept_id="DISTINGUISH_DISCRIMINATING_QUERY",
  source_repository="ORION-OCM", source_artifact="#93 §7; dialogue/clarify.py; science/selection.py",
  formal_definition="Given live alternatives, allowed probes, a target decision and a budget, return a discriminating probe or CANNOT_CHECK.",
  explicit_nondefinition="NOT a clarification heuristic. The operator name DISTINGUISH is not implemented anywhere in src/ocm; the built things are clarification and experiment selection.",
  strongest_parents=("Bayesian experimental design", "value of information", "active learning", "entropy / information gain", "test cover and active diagnosis"),
  ocm_observable_state="ProbeEventV1 with the probe chosen and the version-space reduction achieved",
  trigger="more than one surviving hypothesis and a non-empty probe set",
  proposed_ocm_mechanism="choose the probe maximising guaranteed elimination net of cost",
  information_available_to_mechanism="the surviving set and probe costs",
  positive_case_family="version spaces where one probe halves the survivors",
  negative_twin="a probe set that cannot discriminate at any cost",
  hostile_case="misleading probes, unequal costs, budget exhaustion distinct from structural ambiguity",
  ablation="random probe; greedy confirmation",
  resource_coordinates=("checker_calls", "search_expansions", "tool_calls"),
  cross_family_test="Nim and subtraction probe families",
  cross_domain_test="counterexample selection in mathematics; clarification in language",
  interaction_dependencies=("SUBGOAL_FORMATION", "COGNITIVE_SATURATION"),
  falsifier="an entropy or Bayesian design parent matches",
  disposition="ADAPT", disposition_reason="expected to be PARENT_SUFFICIENT; retained only as the cross-domain transport vehicle, where the claim is that the same frozen method moves domains, not that it beats entropy",
  implementation_status="PARTIAL_IN_SRC_OCM",
  scientific_status="PARENT_SUFFICIENT",
  preserved_terminals=("M10: entropy parent ties OCM 4/4 on experiment selection", "M7 RQ1 ocm-no_clarification PARENT_SUFFICIENT (52/54)", "Bayesian experimental-design parent not built -> CANNOT_CHECK"),
  signatures=("cross_domain_cognitive_transfer",),
  paper_role="P5 transport vehicle",
  reopen_condition="only under a new pre-registered study against a built Bayesian design parent"),

C(concept_id="SUBGOAL_FORMATION",
  source_repository="ORION-OCM", source_artifact="#143 CL-4",
  formal_definition="A recurring intermediate objective learned from solved episodes, together with a learned refusal condition for when not to invoke it.",
  explicit_nondefinition="NOT a subgoal label supplied by the task representation. A method that never declines is a suspicious method.",
  strongest_parents=("BFS/A* and hierarchical planning", "options and hierarchical RL", "model-based RL", "Soar subgoaling plus chunking"),
  ocm_observable_state="SubgoalEventV1 including refusals, weighted equally with invocations",
  trigger="a task where the optimal immediate action is insufficient",
  proposed_ocm_mechanism="mine recurring intermediate states from solved traces; learn the invocation precondition",
  information_available_to_mechanism="solved traces; the exact planner is an oracle, never a policy donor",
  positive_case_family="key-door and bottleneck layouts sharing abstract structure",
  negative_twin="layouts where the old subgoal is unnecessary",
  hostile_case="layouts where the old subgoal is actively harmful",
  ablation="remove the subgoal; compare to A* and to model-based RL",
  resource_coordinates=("search_expansions", "wall_seconds", "checker_calls"),
  cross_family_test="same abstract structure, different geometry",
  cross_domain_test="proof decomposition at CL-8",
  interaction_dependencies=("DISTINGUISH_DISCRIMINATING_QUERY", "RECURSIVE_DECOMPOSITION"),
  falsifier="the subgoal is recoverable from state features alone",
  disposition="KEEP", disposition_reason="the refusal endpoint is what distinguishes it from options discovery",
  implementation_status="NOT_IMPLEMENTED",
  scientific_status="THEORY_ONLY",
  preserved_terminals=(),
  signatures=("method_composition", "cross_family_transfer"),
  paper_role="P2",
  reopen_condition="none"),

C(concept_id="NEGATIVE_TRANSFER_REFUSAL",
  source_repository="ORION-OCM", source_artifact="work/methods.py; science/transfer.py; M9",
  formal_definition="Refuse transport when the target role differs from the source role, when outside authority, when the source is revoked, or when short-horizon help causes final harm; require an adapter when a binding is missing.",
  explicit_nondefinition="NOT refusing everything difficult. Abstention rate is a reported endpoint, not an exclusion criterion.",
  strongest_parents=("case-based reasoning", "skill libraries with embedding retrieval", "continual-learning transfer gates"),
  ocm_observable_state="REFUSE_TRANSFER and ADAPTER_REQUIRED decisions with the role mismatch cited",
  trigger="a candidate transport into a new family",
  proposed_ocm_mechanism="typed correspondence check before transport",
  information_available_to_mechanism="declared roles and authority; never target labels",
  positive_case_family="superficially similar but role-incompatible families",
  negative_twin="genuinely compatible families where refusal would be a false negative",
  hostile_case="short-horizon benefit with final harm",
  ablation="similarity-only routing",
  resource_coordinates=("search_expansions", "checker_calls"),
  cross_family_test="the M9 transfer matrix extended to game families",
  cross_domain_test="game to language transport",
  interaction_dependencies=("SCOPED_FAILURE_KNOWLEDGE", "FIBRES_MULTISCALE_TRANSPORT"),
  falsifier="a similarity-routing parent achieves the same precision with no false refusals",
  disposition="KEEP", disposition_reason="harmful-transfer rate is mandatory in any transfer abstract, so this must be measured whether or not it is a residual",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CANNOT_CHECK",
  preserved_terminals=("M9 transfer matrix 14/14 as expected but milestone terminal is M9_CANNOT_CHECK_FOR_SUPPORTED_AT_THIS_N", "M7 RQ6 CANNOT_CHECK (n<40)", "M12 A negative transfer 7/7 vs 5/7 DESCRIPTIVE"),
  signatures=("safe_negative_transfer_refusal",),
  paper_role="P3 mandatory reported endpoint",
  reopen_condition="n at or above the pre-registered minimum in a fresh study"),

C(concept_id="CONSOLIDATION",
  source_repository="ORION-OCM", source_artifact="#70; kso/abstraction.py",
  formal_definition="Fast capture, replay and comparison, regularity discovery, consolidation into a schema, retention of surprising residuals, archival of detail. Hard invariant: compression may not launder an epistemic distinction.",
  explicit_nondefinition="NOT lossy summarisation. NOT permitted to mint warrant.",
  strongest_parents=("DreamCoder / Stitch / Babble", "e-graphs and egglog", "hash-consing", "Soar chunking", "MDL"),
  ocm_observable_state="mdl_delta, consolidation cost, rare-exception retention",
  trigger="accumulated episodes with a repeated fragment",
  proposed_ocm_mechanism="MDL-gated schema formation with residual retention",
  information_available_to_mechanism="stored episodes only",
  positive_case_family="repeated periodic structure across move sets",
  negative_twin="a family with no repeated structure, where consolidation must decline",
  hostile_case="a rare exception that consolidation would erase",
  ablation="no consolidation; unconditional consolidation",
  resource_coordinates=("index_maintenance_work", "persistent_state_bytes", "acquisition_cpu_seconds"),
  cross_family_test="consolidated schema reused on a new move set",
  cross_domain_test="deferred",
  interaction_dependencies=("REPRESENTATION_CHANGE", "SPARSE_ACTIVE_SUBSPACE"),
  falsifier="consolidation cost exceeds the search it saves, or a rare exception is lost",
  disposition="KEEP", disposition_reason="the rare-exception hostile is the part no library-learning parent currently reports",
  implementation_status="PARTIAL_IN_SRC_OCM",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("#70 deliverables AC-D1..D10 all unchecked", "KS-T12 lifecycle-safe consolidation stays OPEN"),
  signatures=("amortized_future_reasoning", "sparse_relevant_cognition"),
  paper_role="P3",
  reopen_condition="none"),

C(concept_id="OBSTRUCTION_DIAGNOSIS",
  source_repository="ORION-OCM", source_artifact="kso/navigation.py KS-T19; selfmodel/diagnose.py",
  formal_definition="A four-valued navigation outcome FOUND / GAP_NOT_FOUND / OBSTRUCTION_WITNESSED / CANNOT_CHECK, where an obstruction certificate requires every registered lower alternative to have been tried with live warrants and failed, plus a ceiling witness.",
  explicit_nondefinition="A timeout is never an obstruction. A missing retrieval is never an obstruction.",
  strongest_parents=("JTMS/ATMS composed with spreading activation", "CEGAR spurious-versus-real counterexample analysis"),
  ocm_observable_state="ObstructionCertificate with the tried alternatives enumerated",
  trigger="failure to identify after lower alternatives are exhausted",
  proposed_ocm_mechanism="require an exhibited witness before certifying an obstruction",
  information_available_to_mechanism="tried alternatives and their warrants",
  positive_case_family="the L4/L5 escalation worlds",
  negative_twin="the budget-exhaustion world",
  hostile_case="an untried alternative; a dead warrant on the path",
  ablation="certify obstruction on timeout instead",
  resource_coordinates=("search_expansions", "checker_calls"),
  cross_family_test="across the escalation suite",
  cross_domain_test="proof search obstruction",
  interaction_dependencies=("SEARCH_MORE_VS_JUMP", "COGNITIVE_SATURATION", "SCOPED_FAILURE_KNOWLEDGE"),
  falsifier="a CEGAR parent distinguishes spurious from real with equal accuracy",
  disposition="MERGE", disposition_reason="merged into SEARCH_MORE_VS_JUMP; it is that concept's witness condition rather than a separate mechanism",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CALIBRATED",
  preserved_terminals=("KS-T19 checked; M11 KS-T98 SUPPORTED (exact)", "discrimination benchmark NAV-E5 not built"),
  signatures=("governed_representation_operator_evolution",),
  paper_role="P2 within the escalation study",
  reopen_condition="none"),

C(concept_id="LOCAL_TO_GLOBAL_OBSTRUCTION",
  source_repository="ORION-OCM", source_artifact="KSO_REPRESENTATION_ABSTRACTION_V1.md §7; #93 GEF-E11",
  formal_definition="Local solutions consistent on overlaps that admit no global section; a global section requires an independent witness.",
  explicit_nondefinition="NOT a claim that sheaf language adds power; the terminal for every organisation candidate is PARENT_SUFFICIENT by rule.",
  strongest_parents=("CSP local consistency", "ATMS nogoods", "presheaves and sheaves (Robinson; Hansen-Ghrist)"),
  ocm_observable_state="overlap consistency records with no admissible global assembly",
  trigger="pairwise-consistent local solutions",
  proposed_ocm_mechanism="detect the obstruction and refuse the global claim",
  information_available_to_mechanism="local solutions and overlap constraints",
  positive_case_family="a decomposable game world with a genuine gluing failure",
  negative_twin="a world where local solutions do glue",
  hostile_case="a world where CSP arc-consistency already finds the failure",
  ablation="global search",
  resource_coordinates=("search_expansions", "composition_work"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("RECURSIVE_DECOMPOSITION",),
  falsifier="ordinary CSP consistency parents find every obstruction the mechanism finds",
  disposition="DROP", disposition_reason="dropped from the executable programme for now: #93 requires CSP parents to be exhausted first, and no positive case is yet distinguishable from arc consistency. Retained as theory backlog under the §19 decision filter.",
  implementation_status="NOT_IMPLEMENTED",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("KSO_REPRESENTATION_ABSTRACTION_V1.md §7: nothing in that document may be cited as a residual",),
  signatures=(),
  paper_role="none",
  reopen_condition="a positive case that arc consistency provably cannot detect"),

C(concept_id="SELF_MODEL_AND_FAILURE_DIAGNOSIS",
  source_repository="ORION-OCM", source_artifact="selfmodel/model.py; selfmodel/diagnose.py; M11",
  formal_definition="A distribution over responsible cognitive layers D0-D8 from counterfactual evidence, plus the minimum sufficient layer; self-statements carry self-model authority only and never raise object authority.",
  explicit_nondefinition="NOT metacognitive narration. The ablation channel is currently oracle-provided, so this is not yet the machine's own counterfactual reasoning.",
  strongest_parents=("parameter search over router and revocation", "reflection-retry over skills", "a learned failure classifier over traces with the same candidate channel (named, not yet built)", "fault localisation", "interventional causal inference"),
  ocm_observable_state="layer distribution, minimum sufficient layer, obstruction certificate",
  trigger="a diagnosed cognitive failure",
  proposed_ocm_mechanism="counterfactual ablation over layers with a minimum-sufficient rule",
  information_available_to_mechanism="ablation run outcomes",
  positive_case_family="S0-S7 planted causes",
  negative_twin="a failure with no architectural cause",
  hostile_case="historical failures replayed rather than re-executed",
  ablation="parameter search only; reflection-retry only",
  resource_coordinates=("wall_seconds", "search_expansions"),
  cross_family_test="all three M9 environments",
  cross_domain_test="deferred",
  interaction_dependencies=("SEARCH_MORE_VS_JUMP", "GOVERNED_SELF_REORGANIZATION"),
  falsifier="a learned trace classifier reaches the same layer accuracy",
  disposition="KEEP", disposition_reason="kept but explicitly gated: the oracle-provided ablation channel must be replaced by the machine's own counterfactual runs before any claim",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CANNOT_CHECK",
  preserved_terminals=("M11 diagnosis 7/7 but head-to-head row is DESCRIPTIVE (n=7, no pre-registered rate test)", "diagnostic accuracy on real historical failures CANNOT_CHECK", "M11_MIXED_CLAIM_BY_CLAIM"),
  signatures=("bounded_recursive_self_improvement",),
  paper_role="P7 only if earned",
  reopen_condition="machine-generated counterfactual channel, n>=40, all three environments"),

C(concept_id="GOVERNED_SELF_REORGANIZATION",
  source_repository="ORION-OCM", source_artifact="selfmodel/proposal.py; selfmodel/govern.py; M11",
  formal_definition="A self-change proposal at class C0-C6 with a pre-outcome prediction digest, shadow execution, independent assurance, external adoption, migration of affected state, monitoring and rollback. C6 is a recommendation packet only.",
  explicit_nondefinition="Self-modification is NOT itself success. The machine may propose C6 and may never self-authorize it. One successful edit is adaptation, not recursive improvement.",
  strongest_parents=("AutoML and NAS", "meta-learning", "program repair", "evolutionary search", "Soar chunking", "parameter search", "reflection-retry"),
  ocm_observable_state="proposal records with adopted flag, assurance outcomes, rollback artifacts",
  trigger="a diagnosed obstruction at an architectural layer",
  proposed_ocm_mechanism="minimum-sufficient change class with frozen predictions and external adoption",
  information_available_to_mechanism="its own failure records; never the held-out suite",
  positive_case_family="planted architectural faults",
  negative_twin="faults repairable at C0 where a broad rewrite must be refused",
  hostile_case="a proposer that has seen the held-out tasks; self-approval",
  ablation="AutoML-style configuration search with the same budget",
  resource_coordinates=("acquisition_cpu_seconds", "revision_work", "recovery_work"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("SELF_MODEL_AND_FAILURE_DIAGNOSIS", "SEARCH_MORE_VS_JUMP"),
  falsifier="an AutoML or NAS parent with the same budget produces the same improvement",
  disposition="ADAPT", disposition_reason="reframed as a LATE-STAGE DEPENDENT hypothesis requiring at least two generations F0->F1->F2 with disjoint development, acceptance, future-transfer and successor task sets; a single edit is explicitly not evidence",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CANNOT_CHECK",
  preserved_terminals=("M11_MIXED_CLAIM_BY_CLAIM", "adopted 7/7 and broad rewrites refused 2/2 but n=7 descriptive", "C6 constitutional self-change NOT ATTEMPTED by design", "#38 reopens all seven historical adoption cells", "'Our recursive research process is not evidence that OCM can improve itself'"),
  signatures=("bounded_recursive_self_improvement",),
  paper_role="P7 only if earned",
  reopen_condition="two generations with protected evaluation and an AutoML parent"),

C(concept_id="SHADOW_EVALUATION_AND_ROLLBACK",
  source_repository="ORION-OCM", source_artifact="selfmodel/govern.py; selfmodel/rollback_data.py",
  formal_definition="Object-level non-interference during shadow execution, verified on the ledger head as well as the object state hash; rollback restores the component table exactly and revokes stamped evidence while leaving the object digest unchanged.",
  explicit_nondefinition="NOT a canary that merely observes. Non-interference is checked, not assumed.",
  strongest_parents=("shadow and canary deployment", "transactional rollback", "sham-surgery controls"),
  ocm_observable_state="assurance outcomes, ledger head equality, rollback exactness",
  trigger="a self-change proposal awaiting adoption",
  proposed_ocm_mechanism="shadow run with head-and-state comparison and an owned rollback cache",
  information_available_to_mechanism="the proposal and the shadow environment",
  positive_case_family="S1-S7 proposals",
  negative_twin="a proposal that should be rejected",
  hostile_case="a runner that admits evidence during the shadow run",
  ablation="no shadow; adopt directly",
  resource_coordinates=("wall_seconds", "storage_writes", "recovery_work"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("GOVERNED_SELF_REORGANIZATION",),
  falsifier="ordinary transactional rollback provides the same guarantee at the same cost",
  disposition="MERGE", disposition_reason="merged into GOVERNED_SELF_REORGANIZATION as its assurance step; it has no independent scientific endpoint",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CAUSALLY_SUPPORTED",
  preserved_terminals=("assurance 7/7 across S1-S7", "rollback exact 7/7 and in M12 phase G in all three orderings"),
  signatures=("bounded_recursive_self_improvement",),
  paper_role="P7 method section",
  reopen_condition="none"),

C(concept_id="AUTHORITY_NON_AMPLIFICATION",
  source_repository="ORION-OCM", source_artifact="epistemics/authority.py; WLL-4",
  formal_definition="Without an additional bridge certificate, the sound authority scope of a composition is contained in the intersection of the component scopes; the meet never raises object authority.",
  explicit_nondefinition="NOT a security property. It is an epistemic conservation statement.",
  strongest_parents=("Blackwell sufficiency", "ATMS scoped justifications", "access-control lattices"),
  ocm_observable_state="authority lattice meets; refusal of self-approval",
  trigger="any composition or self-statement",
  proposed_ocm_mechanism="lattice meet with an explicit bridge requirement",
  information_available_to_mechanism="component authorities",
  positive_case_family="composition chains",
  negative_twin="a bridge certificate that legitimately widens scope",
  hostile_case="a self-description asserted as object authority",
  ablation="allow the join instead of the meet",
  resource_coordinates=(),
  cross_family_test="n/a",
  cross_domain_test="n/a",
  interaction_dependencies=("WARRANT_CONSERVATION",),
  falsifier="none; this is an invariant, not a hypothesis",
  disposition="KEEP", disposition_reason="an invariant the programme must not violate, not a competitive claim; it earns no paper of its own",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CAUSALLY_SUPPORTED",
  preserved_terminals=("'Self-statements never carry object authority' SUPPORTED (exact); mutant_self_description_as_authority caught",),
  signatures=(),
  paper_role="method section invariant",
  reopen_condition="none"),

C(concept_id="WARRANT_CONSERVATION",
  source_repository="ORION-OCM", source_artifact="OCM_LANE_201_TERMINAL_V1.md L4",
  formal_definition="Any saving from holding a coarser representation is a relocation of state into later access, never a free reduction. Aggregation, majority, similarity and compression never mint warrant.",
  explicit_nondefinition="NOT a claim that coarsening is useless; a claim that its cost reappears.",
  strongest_parents=("minimal sufficient statistic (Fisher; Lehmann-Scheffe; Blackwell)", "partition lattice (Birkhoff)", "Hartley 1928"),
  ocm_observable_state="resource vectors before and after coarsening",
  trigger="any abstraction or summarisation",
  proposed_ocm_mechanism="charge deferred access cost at the point it is incurred",
  information_available_to_mechanism="the resource ledger",
  positive_case_family="summarised stores re-queried at detail",
  negative_twin="a query family that genuinely needs no detail",
  hostile_case="reporting query savings while omitting later descent cost",
  ablation="omit the descent charge and observe the apparent free lunch",
  resource_coordinates=("persistent_state_bytes", "active_bytes_per_query", "index_maintenance_work"),
  cross_family_test="n/a",
  cross_domain_test="n/a",
  interaction_dependencies=("CONSOLIDATION", "SPARSE_ACTIVE_SUBSPACE"),
  falsifier="none; L4 already refutes the matched-resource reading",
  disposition="KEEP", disposition_reason="this is a constraint the scaling study must respect, and it is the reason the crossover query count exists",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="PARENT_SUFFICIENT",
  preserved_terminals=("OCM_LANE_201_TERMINAL_V1.md PARENT_SUFFICIENT; CERTIFIED_REPRESENTATION_RESIDUAL NOT_EARNED; L4 conservation refutes the matched-resource reading",),
  signatures=(),
  paper_role="method section constraint",
  reopen_condition="none"),

C(concept_id="RESOURCE_RESPONSIBILITY",
  source_repository="ORION-OCM", source_artifact="kso/resources.py; COGNITIVE_LADDER_SCALING_V1.md §7",
  formal_definition="A non-compensatory resource vector compared only by Pareto dominance, never collapsed to a scalar inside the core; cognitive productivity is reported per coordinate with the worst coordinate disclosed alongside any favourable one.",
  explicit_nondefinition="NOT a weighted score. There is no scalar OCM score and no scalar productivity score.",
  strongest_parents=("multi-objective dominance", "time-bounded Kolmogorov complexity / Levin's Kt"),
  ocm_observable_state="the full resource vector per arm per query",
  trigger="every measured comparison",
  proposed_ocm_mechanism="Pareto reporting with mandatory worst-coordinate disclosure",
  information_available_to_mechanism="the meter",
  positive_case_family="any arm comparison",
  negative_twin="an arm that wins one coordinate and loses another",
  hostile_case="one favourable coordinate hiding losses elsewhere",
  ablation="scalar collapse (planted mutant)",
  resource_coordinates=("all",),
  cross_family_test="n/a",
  cross_domain_test="n/a",
  interaction_dependencies=(),
  falsifier="none; an invariant",
  disposition="KEEP", disposition_reason="the worst-coordinate disclosure rule is the structural answer to the strongest presentation-level attack",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CAUSALLY_SUPPORTED",
  preserved_terminals=("OCM_LANE_202_TERMINAL_V1.md TRADEOFF_FRONTIER_ONLY; TRANSFORMER_EQUIVALENT_UNDER_MATCHED_RESOURCES CANNOT_CHECK", "mutant_scalar_collapse planted and caught"),
  signatures=(),
  paper_role="method section invariant",
  reopen_condition="none"),

C(concept_id="EPISTEMIC_HYSTERESIS",
  source_repository="ORION-OCM", source_artifact="selfmodel/diagnose.py batch-6 F4 lemma; M11 S5",
  formal_definition="Restoring withdrawn support restores exactly what is justified, and reinstatement at a lower layer is preferred to a rewrite that would also pass assurance.",
  explicit_nondefinition="The term hysteresis does not occur in the repository; the mechanism is reinstatement-versus-relearning and is named as such here to avoid importing a metaphor.",
  strongest_parents=("ATMS label recomputation", "belief revision (AGM)"),
  ocm_observable_state="reinstatement layer chosen versus the minimum available",
  trigger="restoration of a previously revoked support",
  proposed_ocm_mechanism="prefer the minimum layer that restores justification",
  information_available_to_mechanism="the dependency graph and the restored support",
  positive_case_family="revoke then restore a shared premise",
  negative_twin="a case where relearning genuinely is minimal",
  hostile_case="a D7 rewrite that passes assurance but is not minimum",
  ablation="always relearn",
  resource_coordinates=("recovery_work", "revision_work"),
  cross_family_test="across game families in one store",
  cross_domain_test="deferred",
  interaction_dependencies=("REOPENING_LOCAL_REVISION", "SCOPED_FAILURE_KNOWLEDGE"),
  falsifier="an ATMS parent recomputes labels at the same cost",
  disposition="ADAPT", disposition_reason="renamed away from the hysteresis metaphor to reinstatement-versus-relearning, which is what is actually measured",
  implementation_status="IMPLEMENTED_IN_SRC_OCM",
  scientific_status="CANNOT_CHECK",
  preserved_terminals=("M11 S5 SUPPORTED at n=1", "M12 A relearned 6/6 vs parent 3/6 DESCRIPTIVE", "M7 RQ3 relearned CANNOT_CHECK (n<40)"),
  signatures=("local_revision",),
  paper_role="P3 supporting",
  reopen_condition="n at or above the pre-registered minimum"),

C(concept_id="EPISTEMIC_TENSION_DETECTION",
  source_repository="ORION-OCM", source_artifact="kso/surprise.py",
  formal_definition="Query-specific reaction surprise relative to a background fixed point, so that generic hubs do not dominate.",
  explicit_nondefinition="NOT novelty seeking. The PROPAGATED model is registered but NOT adopted; the default stays UNIFORM.",
  strongest_parents=("Andersen-Chung-Lang contribution vectors", "inverse document frequency", "Bayesian surprise"),
  ocm_observable_state="per-query surprise scores",
  trigger="a query against a background",
  proposed_ocm_mechanism="query-conditioned surprise excluding teleport mass",
  information_available_to_mechanism="the graph and the query seeds",
  positive_case_family="the 12/50 EXTRACT misses in M2",
  negative_twin="hub-dominated queries where surprise must not fire",
  hostile_case="a generic hub masquerading as a surprise",
  ablation="uniform background",
  resource_coordinates=("navigation_work", "index_probes"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("DISTINGUISH_DISCRIMINATING_QUERY",),
  falsifier="IDF reproduces the ranking",
  disposition="DROP", disposition_reason="dropped from the executable ladder: the seed-count lemma proved a no-op, the default model is unadopted, and no positive case is distinguishable from IDF. Theory backlog under the §19 filter.",
  implementation_status="PARTIAL_IN_SRC_OCM",
  scientific_status="THEORY_ONLY",
  preserved_terminals=("the seed-count lemma proved a NO-OP; the lever the M2 receipt named changes nothing (check_seed_count_lemma)", "PROPAGATED model registered but not adopted"),
  signatures=(),
  paper_role="none",
  reopen_condition="a positive case IDF provably cannot rank"),

C(concept_id="THOUGHT_EXPERIMENT_COUNTERFACTUAL",
  source_repository="ORION-OCM + ORION V1", source_artifact="selfmodel/benchmark.py S0-S7",
  formal_definition="One-layer counterfactual ablation runs used as the evidence channel for diagnosis.",
  explicit_nondefinition="The channel is currently ORACLE-PROVIDED, not machine-generated. That is the whole gap.",
  strongest_parents=("interventional causal inference", "fault localisation", "ablation studies"),
  ocm_observable_state="ablation outcomes and the layer distribution they induce",
  trigger="a diagnosed failure",
  proposed_ocm_mechanism="the machine designs and runs its own ablations",
  information_available_to_mechanism="its own architecture description",
  positive_case_family="planted causes",
  negative_twin="a failure with no single responsible layer",
  hostile_case="the machine choosing ablations that confirm a prior diagnosis",
  ablation="oracle channel versus machine-generated channel",
  resource_coordinates=("wall_seconds", "search_expansions"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("SELF_MODEL_AND_FAILURE_DIAGNOSIS",),
  falsifier="machine-generated ablations do not reach oracle-channel accuracy",
  disposition="MERGE", disposition_reason="merged into SELF_MODEL_AND_FAILURE_DIAGNOSIS as its evidence channel; the open question is identical",
  implementation_status="PARTIAL_IN_SRC_OCM",
  scientific_status="CANNOT_CHECK",
  preserved_terminals=("M11 §5: the ablation channel is oracle-provided",),
  signatures=("bounded_recursive_self_improvement",),
  paper_role="P7",
  reopen_condition="machine-generated channel built"),

C(concept_id="CONCEPT_OPERATOR_INVENTION",
  source_repository="ORION-OCM + ORION V1", source_artifact="kso/jump.py L5; research/programme/PARENTS.md",
  formal_definition="Proposing an operator or concept not present in the registered basis.",
  explicit_nondefinition="Selecting from a registered menu is NOT invention. L5 is currently a level label with no mechanism.",
  strongest_parents=("DreamCoder library learning", "anti-unification and grammar induction", "program synthesis"),
  ocm_observable_state="none; not implemented",
  trigger="operator insufficiency witnessed at L4",
  proposed_ocm_mechanism="deferred",
  information_available_to_mechanism="deferred",
  positive_case_family="deferred",
  negative_twin="deferred",
  hostile_case="an invented operator that is a renaming of an existing primitive",
  ablation="deferred",
  resource_coordinates=(),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("SEARCH_MORE_VS_JUMP",),
  falsifier="every invented operator is expressible as a composition of registered primitives",
  disposition="DROP", disposition_reason="deferred by the programme's own parents document until a distinct obstruction, mechanism and parent-exceeding result exist; classified as a contingent extension not needed for a first paper",
  implementation_status="NOT_IMPLEMENTED",
  scientific_status="THEORY_ONLY",
  preserved_terminals=(
    "MULTIPLE_CONCEPT_ATOMS_REQUIRED (ORION/research/extensions/orion-jump-recursive-atoms/JUMP_ATOM_PILOT_CLOSURE_V1.md): 'system proposes a new named primitive' is not an ORION-specific discriminator",
    "MULTIPLE_TENSION_ATOMS_REQUIRED and MULTIPLE_IMAGINATION_ATOMS_REQUIRED (same file)",
    "RECURSIVE_ATOM_STUDY_CALCULUS_FROZEN: the programme ended with FEWER claimed primitives than it began with",
    "'autonomous representation invention has not been demonstrated'",
    "the Stitch result was a checked primitive alias",
    "PARENTS.md defers representation invention"),
  signatures=("governed_representation_operator_evolution",),
  paper_role="none",
  reopen_condition="an L4 witness the registered basis provably cannot repair"),

C(concept_id="PERSISTENT_RESTARTABLE_COMPETENCE",
  source_repository="ORION-OCM", source_artifact="COGNITIVE_LADDER_PROTOCOL_V1.md CL-T1; lifetime/machine.py",
  formal_definition="A scored reuse is admissible only after the acquiring OS process exited, a new process with a different PID read the serialized state, and the state digest matched.",
  explicit_nondefinition="In-process simulated restart is design evidence only and is never confirmatory.",
  strongest_parents=("checkpoint-and-reload of any learner, including a neural one", "crash-consistency testing in storage systems"),
  ocm_observable_state="pid before and after, state digest before and after, exit status",
  trigger="any reuse claim",
  proposed_ocm_mechanism="hardened subprocess boundary with digest comparison",
  information_available_to_mechanism="the serialized state only",
  positive_case_family="acquire in process A, reuse in process B",
  negative_twin="a no-invoke arm reaching the same status with zero reuses",
  hostile_case="an in-memory cache surviving the boundary; a fixture import in the reusing process",
  ablation="reset-between-task arm",
  resource_coordinates=("storage_reads", "storage_writes", "wall_seconds"),
  cross_family_test="every rung",
  cross_domain_test="every rung",
  interaction_dependencies=("REUSABLE_METHOD_ACQUISITION",),
  falsifier="a checkpointed neural learner shows the same acquire-restart-reuse profile",
  disposition="KEEP", disposition_reason="the custody discipline is what makes every other claim in the programme legible; a neural parent gets exactly the same boundary",
  implementation_status="TEMPLATE_EXISTS_IN_MATH_LANGUAGE_LEARNING_V1",
  scientific_status="CAUSALLY_SUPPORTED",
  preserved_terminals=("test_unary_method_restart.py asserts pid difference, reaping, group absence, and zero prior uses",),
  signatures=("persistent_restartable_competence",),
  paper_role="P1 method section",
  reopen_condition="none"),

C(concept_id="MULTI_GENERATION_IMPROVEMENT",
  source_repository="ORION-OCM", source_artifact="lifetime/machine.py; M12; steering §11",
  formal_definition="F0 learns from failures and proposes F1; F1 is evaluated on protected tasks and operates on fresh tasks; F1 then receives new failures and proposes F2, over disjoint development, acceptance, future-transfer, successor-generation and successor-acceptance task sets.",
  explicit_nondefinition="One successful architecture edit is adaptation, NOT recursive improvement. The research process that produced OCM is not evidence that OCM improves itself.",
  strongest_parents=("AutoML and NAS", "meta-learning", "evolutionary search", "recursive-improvement systems", "the matched WholeSystemParent"),
  ocm_observable_state="per-generation task quality, information required, search work, revision locality, k/N, failure recurrence, false-jump rate",
  trigger="accumulated failures at an architectural layer",
  proposed_ocm_mechanism="the governed self-reorganization lifecycle, iterated",
  information_available_to_mechanism="its own failure records; never the acceptance or successor-acceptance sets",
  positive_case_family="two generations with measured improvement",
  negative_twin="a generation that should not change anything",
  hostile_case="configuration search dressed as cognition",
  ablation="AutoML parent with the same budget and the same task sets",
  resource_coordinates=("acquisition_cpu_seconds", "query_cpu_seconds", "persistent_state_bytes", "revision_work"),
  cross_family_test="deferred",
  cross_domain_test="deferred",
  interaction_dependencies=("GOVERNED_SELF_REORGANIZATION", "SELF_MODEL_AND_FAILURE_DIAGNOSIS"),
  falsifier="an AutoML or NAS parent matches the generation-over-generation curve",
  disposition="ADAPT", disposition_reason="promoted to an explicit late-stage endpoint with a two-generation minimum and five disjoint task sets; not attemptable before Phases A-G produce stable measurements",
  implementation_status="NOT_IMPLEMENTED",
  scientific_status="THEORY_ONLY",
  preserved_terminals=(
    "INTERACTION_ONLY_RESIDUAL_FROZEN (ORION/research/extensions/meta-orion-recursive-scientific-evolution/): the residual is interaction correctness plus future value, NOT self-improvement",
    "RSE.T2 FINITE_INFORMATION_CEILING_VERIFIED: a current-summary-only policy is capped at 1/2; full history and compact typed lineage reach 1.0",
    "Self-ORION P5 NO_TERMINAL_UNDER_FROZEN_RULES: FULL_T7 at 12/96; ADAS, DGM and ADIAS unavailable and correctly NOT replaced by weak proxies",
    "FULL_OCM_RESIDUAL_SUPPORTED is scoped to one inferential family (A conversations, n=54); every other residual is descriptive",
    "CANNOT_CHECK_MATCHED_PARENT against a frontier foundation-model parent",
    "#143 §13: the standalone synthetic ladder is pilot/design evidence only"),
  signatures=("bounded_recursive_self_improvement",),
  paper_role="P7 only if earned",
  reopen_condition="Phases A-G complete with stable measurements"),
]
