"""Build m2p4_compile.py: the study compiler, whose bounds MATCH the registered spec.

Distinct from m2p2_compile_b34.py, which is kept unchanged because it is the artifact
that compiled the calibration worlds and is cited by GSURF_B34_CALIBRATION.md. That
variant deliberately admits a WIDER range (4..16 chunks, lengths 2..4) than the M2-P4
spec allows, so it would accept a band-2-3 world and could not serve as an exact
backstop for the registered grammar. This generator produces the compiler the STUDY
binds: chunk count 10..16 and chunk length 3..4, exactly the spec's hard bounds.

Equivalence is proven, not asserted: this file with its banner removed must be
byte-identical to the frozen m2p2_compile.py with exactly three substitutions applied."""
import io

SRC = "research/m2-traversal-capital-v1/m2p2/m2p2_compile.py"
DST = "research/m2-traversal-capital-v1/m2p4/m2p4_compile.py"

src = io.open(SRC, encoding="utf-8").read()

SUBS = [
    ('    if not isinstance(chunks, list) or not (4 <= len(chunks) <= 8):\n'
     '        problems.append("chunk count outside 4..8")',
     '    if not isinstance(chunks, list) or not (10 <= len(chunks) <= 16):\n'
     '        problems.append("chunk count outside 10..16")'),
    ('            if not isinstance(c, list) or not (2 <= len(c) <= 3):\n'
     '                problems.append(f"chunk {c} length outside 2..3")',
     '            if not isinstance(c, list) or not (3 <= len(c) <= 4):\n'
     '                problems.append(f"chunk {c} length outside 3..4")'),
    ('SCHEMA = "OCM_M2P2_COMPILED_WORLD_V1"',
     'SCHEMA = "OCM_M2P4_B34_COMPILED_WORLD_V1"'),
]

expected = src
for old, new in SUBS:
    assert expected.count(old) == 1, "anchor not found exactly once:\n%s" % old
    expected = expected.replace(old, new)

BANNER = (
    "M2-P4 STUDY COMPILER -- bounds match the registered spec exactly.\n"
    "Generated by m2p4/make_study_compiler.py, which asserts that this file with this\n"
    "banner removed is byte-identical to the frozen m2p2_compile.py with exactly three\n"
    "substitutions applied: chunk count 4..8 -> 10..16, chunk length 2..3 -> 3..4, and\n"
    "the emitted schema string. Unlike m2p2_compile_b34.py (the wider-bounded variant\n"
    "used for instrument calibration), this compiler rejects any world outside the\n"
    "M2-P4 grammar, so it is an exact backstop for the spec's hard bounds.\n"
    "NEVER use for an M2-P2/M2-P3 package.\n\n"
)

i = expected.index('"""')
variant = expected[:i + 3] + BANNER + expected[i + 3:]
io.open(DST, "w", encoding="utf-8").write(variant)

check = io.open(DST, encoding="utf-8").read()
assert check.count(BANNER) == 1, "banner not present exactly once"
assert check.replace(BANNER, "", 1) == expected, "differs from frozen source beyond the three substitutions"
import ast; ast.parse(check)
print("OK  m2p4_compile.py == frozen m2p2_compile.py + 3 substitutions (byte-identical after banner removal)")
print("OK  parses")
for _, new in SUBS:
    print("   ", new.strip().splitlines()[0][:78])
