"""Build m2p4_check.py: the study's stage-2 orchestrator.

m2p3_check_v2.py (the V2 orchestrator this study's freeze first bound) hard-imports
`m2p2_compile`, whose bounds are 4..8 chunks of length 2..3. Run against an M2-P4
package it would reject EVERY band-3-4 world at validate_world, before compilation --
so it cannot execute this study as written. This generator produces the orchestrator
that can: m2p3_check_v2.py with the compiler import repointed at m2p4_compile (whose
bounds match the M2-P4 spec exactly), the sibling-module search path widened to
the canonical m2p2/ and m2p3/v2/ directories (so no sha-bound file is duplicated),
and the receipt schema relabelled.

The V2 static guard is UNCHANGED and still used: the fix that made guard_v2 correct
(ledger row 59) is preserved in full. Equivalence is proven, not asserted."""
import io

SRC = "research/m2-traversal-capital-v1/m2p3/v2/m2p3_check_v2.py"
DST = "research/m2-traversal-capital-v1/m2p4/m2p4_check.py"

src = io.open(SRC, encoding="utf-8").read()

SUBS = [
    # The orchestrator resolves every sibling module from HERE (its own directory).
    # M2-P3 got away with that because copies sat beside it in m2p3/v2/. From m2p4/,
    # m2p2_gsurf, m2p2_taxa and guard_v2 do NOT resolve, so the canonical directories
    # are added to sys.path instead of duplicating four sha-bound files.
    ("HERE = Path(__file__).resolve().parent\nsys.path.insert(0, str(HERE))",
     "HERE = Path(__file__).resolve().parent\nLANE_ROOT = HERE.parent\n"
     "for _p in (HERE, LANE_ROOT / \"m2p2\", LANE_ROOT / \"m2p3\" / \"v2\"):\n"
     "    sys.path.insert(0, str(_p))"),
    ("import m2p2_compile as C      # noqa: E402",
     "import m2p4_compile as C      # noqa: E402"),
    ('SCHEMA = "OCM_M2P2_STAGE2_RECEIPT_V1"',
     'SCHEMA = "OCM_M2P4_STAGE2_RECEIPT_V1"'),
    # G-SURF is SPAWNED as a subprocess by path, not imported, so widening the import
    # search path does not reach it. HERE is m2p4/, which does not contain m2p2_gsurf.py:
    # every G-SURF run failed rc=2 "can't open file" until this was repointed.
    ('            r = subprocess.run([sys.executable, str(HERE / "m2p2_gsurf.py"),',
     '            r = subprocess.run([sys.executable, str(LANE_ROOT / "m2p2" / "m2p2_gsurf.py"),'),
]
expected = src
for old, new in SUBS:
    assert expected.count(old) == 1, "anchor not found exactly once:\n%s" % old
    expected = expected.replace(old, new)

# the orchestrator adds its own directory to sys.path; m2p4_compile lives beside it
assert "LANE_ROOT / \"m2p2\"" in expected, "sibling search path not widened"

BANNER = (
    "M2-P4 STUDY ORCHESTRATOR -- generated by m2p4/make_study_orchestrator.py.\n"
    "Identical to m2p3_check_v2.py except that the compiler import points at\n"
    "m2p4_compile (bounds 10..16 chunks of length 3..4, matching the M2-P4 spec),\n"
    "resolves m2p2_gsurf / m2p2_taxa / guard_v2 from their canonical directories,\n"
    "and the receipt schema is relabelled. The V2 static guard is unchanged and\n"
    "still used. The generator asserts byte-identity after banner removal.\n"
    "Rationale: m2p2_compile's 4..8 / 2..3 bounds would reject every band-3-4\n"
    "world at validate_world, so the V2 orchestrator cannot run this study.\n\n"
)
i = expected.index('"""')
out = expected[:i + 3] + BANNER + expected[i + 3:]
io.open(DST, "w", encoding="utf-8").write(out)

check = io.open(DST, encoding="utf-8").read()
assert check.count(BANNER) == 1
assert check.replace(BANNER, "", 1) == expected, "differs beyond the two substitutions"
import ast; ast.parse(check)
print("OK  m2p4_check.py == m2p3_check_v2.py + %d substitutions (byte-identical after banner removal)" % len(SUBS))
print("OK  parses")
for _, new in SUBS:
    print("   ", new[:70])
