"""Build m2p2_compile_b34.py: the frozen compiler with EXACTLY THREE edits.

The frozen m2p2_compile.py is never modified. This writes a clearly-named sibling and
PROVES equivalence: the variant with its banner removed must be byte-identical to the
frozen source with the three substitutions applied. Anything else aborts."""
import io

SRC = "research/m2-traversal-capital-v1/m2p2/m2p2_compile.py"
DST = "research/m2-traversal-capital-v1/m2p4/m2p2_compile_b34.py"

src = io.open(SRC, encoding="utf-8").read()

SUBS = [
    ('    if not isinstance(chunks, list) or not (4 <= len(chunks) <= 8):\n'
     '        problems.append("chunk count outside 4..8")',
     '    if not isinstance(chunks, list) or not (4 <= len(chunks) <= 16):\n'
     '        problems.append("chunk count outside 4..16")'),
    ('            if not isinstance(c, list) or not (2 <= len(c) <= 3):\n'
     '                problems.append(f"chunk {c} length outside 2..3")',
     '            if not isinstance(c, list) or not (2 <= len(c) <= 4):\n'
     '                problems.append(f"chunk {c} length outside 2..4")'),
    ('SCHEMA = "OCM_M2P2_COMPILED_WORLD_V1"',
     'SCHEMA = "OCM_M2P4_B34_COMPILED_WORLD_V1"'),
]

expected = src
for old, new in SUBS:
    assert expected.count(old) == 1, "anchor not found exactly once:\n%s" % old
    expected = expected.replace(old, new)

BANNER = (
    "VARIANT OF THE FROZEN m2p2_compile.py -- NEVER USE FOR AN M2-P2/M2-P3 PACKAGE.\n"
    "Generated by m2p4/make_compile_variant.py, which asserts that this file with this\n"
    "banner removed is byte-identical to the frozen compiler with exactly three\n"
    "substitutions applied: chunk-count bound 4..8 -> 4..16, per-chunk length bound\n"
    "2..3 -> 2..4, and the emitted schema string. It exists only to compile\n"
    "lane-authored band-3-4 worlds for INSTRUMENT CALIBRATION (does G-SURF false-fire\n"
    "outside the band it was calibrated on?). It gates nothing.\n\n"
)

# insert the banner INSIDE the existing module docstring, so `from __future__` stays first
i = expected.index('"""')
variant = expected[:i + 3] + BANNER + expected[i + 3:]

io.open(DST, "w", encoding="utf-8").write(variant)

# prove it: strip the banner back out, require byte-identity with `expected`
check = io.open(DST, encoding="utf-8").read()
assert check.count(BANNER) == 1, "banner not present exactly once"
stripped = check.replace(BANNER, "", 1)
assert stripped == expected, "variant differs from the frozen source beyond the three substitutions"
import ast; ast.parse(check)
print("OK  variant == frozen + 3 substitutions (byte-identical after banner removal)")
print("OK  variant parses")
for old, new in SUBS:
    print("   changed: %s" % new.strip().splitlines()[0][:80])
