"""Fixed explicit typed registrations; no source-derived audit at replay time."""
SOURCE_PATHS = (
    "research/gmi-1068-foundation-repair-v5/AdmissibilityV5.lean",
    "research/gmi-1068-partial-context-v15/PartialContextV15.lean",
    "research/gmi-1068-scalarization-v12/ScalarLawsV12.lean",
    "research/gmi-1068-scalarization-v12/FiniteSumsV12.lean",
    "research/gmi-1068-reference-envelope-v18/PrefixWrapperV18.lean",
    "research/gmi-1068-reference-envelope-v18/ShortestCodesV18.lean",
    "research/gmi-1068-reference-envelope-v18/FiniteMarginsV18.lean",
    "research/gmi-1068-reference-envelope-v18/LowerFiniteV18.lean",
    "research/gmi-1068-reference-envelope-v18/ExpectationContextsV18.lean",
    "research/gmi-1068-reference-envelope-v18/FreeMonotonesV18.lean",
)
SOURCE_NAMES = tuple(p.rsplit("/", 1)[-1] for p in SOURCE_PATHS)
ENTRIES = (
    ("PrefixWrapperV18.pad_binding", "(L : Nat) (p : Program) : pad L p=List.replicate L true++p := @PrefixWrapperV18.pad_binding L p"),
    ("PrefixWrapperV18.wrapper_binding", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (p : Program) : wrapper U z L p=(if p=[false] then some z else (stripOnes L p).bind U) := @PrefixWrapperV18.wrapper_binding α U z L p"),
    ("PrefixWrapperV18.strip_iff", "(L : Nat) (p q : Program) : stripOnes L p = some q ↔ p = pad L q := @PrefixWrapperV18.strip_iff L p q"),
    ("PrefixWrapperV18.pad_length", "(L : Nat) (p : Program) : (pad L p).length=L+p.length := @PrefixWrapperV18.pad_length L p"),
    ("PrefixWrapperV18.pad_ne_target", "(L : Nat) (hL : 0<L) (p : Program) : pad L p ≠ [false] := @PrefixWrapperV18.pad_ne_target L hL p"),
    ("PrefixWrapperV18.wrapper_target", "{α : Type u} (U : Machine α) (z : α) (L : Nat) : wrapper U z L [false] = some z := @PrefixWrapperV18.wrapper_target α U z L"),
    ("PrefixWrapperV18.wrapper_simulates", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (hL : 0<L) (p : Program) : wrapper U z L (pad L p) = U p := @PrefixWrapperV18.wrapper_simulates α U z L hL p"),
    ("PrefixWrapperV18.wrapper_empty", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (hL : 0<L) : wrapper U z L [] = none := @PrefixWrapperV18.wrapper_empty α U z L hL"),
    ("PrefixWrapperV18.success_iff", "{α : Type u} (U : Machine α) (z y : α) (L : Nat) (hL : 0<L) (p : Program) : wrapper U z L p = some y ↔ (p=[false] ∧ y=z) ∨ ∃ q, p=pad L q ∧ U q=some y := @PrefixWrapperV18.success_iff α U z y L hL p"),
    ("PrefixWrapperV18.pad_prefix_iff", "(L : Nat) (p q : Program) : IsPrefix (pad L p) (pad L q) ↔ IsPrefix p q := @PrefixWrapperV18.pad_prefix_iff L p q"),
    ("PrefixWrapperV18.target_not_prefix_pad", "(L : Nat) (hL : 0<L) (p : Program) : ¬ IsPrefix [false] (pad L p) := @PrefixWrapperV18.target_not_prefix_pad L hL p"),
    ("PrefixWrapperV18.pad_not_prefix_target", "(L : Nat) (hL : 0<L) (p : Program) : ¬ IsPrefix (pad L p) [false] := @PrefixWrapperV18.pad_not_prefix_target L hL p"),
    ("PrefixWrapperV18.wrapper_prefix_free", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (hL : 0<L) (hU : PrefixFree U) : PrefixFree (wrapper U z L) := @PrefixWrapperV18.wrapper_prefix_free α U z L hL hU"),
    ("ShortestCodesV18.shortest_iff", "{α : Type u} (U : Machine α) (x : α) (p : Program) : IsShortest U x p ↔ U p=some x ∧ ∀ q, U q=some x → p.length≤q.length := @ShortestCodesV18.shortest_iff α U x p"),
    ("ShortestCodesV18.minimum_iff", "{α : Type u} (U : Machine α) (x : α) (k : Nat) : MinimumLength U x k ↔ ∃ p, IsShortest U x p ∧ p.length=k := @ShortestCodesV18.minimum_iff α U x k"),
    ("ShortestCodesV18.minimum_exists", "{α : Type u} (U : Machine α) (x : α) (hp : ∃ p, U p=some x) : ∃ k, MinimumLength U x k := @ShortestCodesV18.minimum_exists α U x hp"),
    ("ShortestCodesV18.minimum_unique", "{α : Type u} (U : Machine α) (x : α) {j k : Nat} (hj : MinimumLength U x j) (hk : MinimumLength U x k) : j=k := @ShortestCodesV18.minimum_unique α U x j k hj hk"),
    ("ShortestCodesV18.target_shortest", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (hL : 0<L) : IsShortest (wrapper U z L) z [false] := @ShortestCodesV18.target_shortest α U z L hL"),
    ("ShortestCodesV18.target_minimum", "{α : Type u} (U : Machine α) (z : α) (L : Nat) (hL : 0<L) : MinimumLength (wrapper U z L) z 1 := @ShortestCodesV18.target_minimum α U z L hL"),
    ("ShortestCodesV18.nontarget_success", "{α : Type u} (U : Machine α) (z x : α) (L : Nat) (hL : 0<L) (hx : x≠z) (p : Program) : wrapper U z L p=some x ↔ ∃ q, p=pad L q ∧ U q=some x := @ShortestCodesV18.nontarget_success α U z x L hL hx p"),
    ("ShortestCodesV18.nontarget_exists", "{α : Type u} (U : Machine α) (z x : α) (L : Nat) (hL : 0<L) (hx : x≠z) : (∃ p, wrapper U z L p=some x) ↔ ∃ q, U q=some x := @ShortestCodesV18.nontarget_exists α U z x L hL hx"),
    ("ShortestCodesV18.shortest_forward", "{α : Type u} (U : Machine α) (z x : α) (L : Nat) (hL : 0<L) (hx : x≠z) (p : Program) (hp : IsShortest U x p) : IsShortest (wrapper U z L) x (pad L p) := @ShortestCodesV18.shortest_forward α U z x L hL hx p hp"),
    ("ShortestCodesV18.shortest_backward", "{α : Type u} (U : Machine α) (z x : α) (L : Nat) (hL : 0<L) (hx : x≠z) (q : Program) (hq : IsShortest (wrapper U z L) x q) : ∃ p, q=pad L p ∧ IsShortest U x p := @ShortestCodesV18.shortest_backward α U z x L hL hx q hq"),
    ("ShortestCodesV18.nontarget_minimum_iff", "{α : Type u} (U : Machine α) (z x : α) (L : Nat) (hL : 0<L) (hx : x≠z) (k : Nat) : MinimumLength (wrapper U z L) x k ↔ ∃ j, k=L+j ∧ MinimumLength U x j := @ShortestCodesV18.nontarget_minimum_iff α U z x L hL hx k"),
    ("FiniteMarginsV18.score_constant", "{n : Nat} (w : Fin n → Int) (c : Int) : score w (fun _ => c)=c*sum w := @FiniteMarginsV18.score_constant n w c"),
    ("FiniteMarginsV18.score_monotone", "{n : Nat} (w u v : Fin n → Int) (hw : ∀ i, 0≤w i) (huv : ∀ i, u i≤v i) : score w u≤score w v := @FiniteMarginsV18.score_monotone n w u v hw huv"),
    ("FiniteMarginsV18.score_bounds", "{n : Nat} (w v : Fin n → Int) (B : Int) (hw : ∀ i, 0≤w i) (hv : ∀ i, 0≤v i ∧ v i≤B) : 0≤score w v ∧ score w v≤B*sum w := @FiniteMarginsV18.score_bounds n w v B hw hv"),
    ("FiniteMarginsV18.score_mask_split", "{n : Nat} (w v : Fin n → Int) (keep : Fin n → Bool) : score w v=score (mask keep w) v+score (mask (fun i => !(keep i)) w) v := @FiniteMarginsV18.score_mask_split n w v keep"),
    ("FiniteMarginsV18.mask_nonnegative", "{n : Nat} (w : Fin n → Int) (keep : Fin n → Bool) (hw : ∀ i, 0≤w i) : ∀ i, 0≤mask keep w i := @FiniteMarginsV18.mask_nonnegative n w keep hw"),
    ("FiniteMarginsV18.omitted_bound", "{n : Nat} (w v : Fin n → Int) (keep : Fin n → Bool) (B : Int) (hw : ∀ i, 0≤w i) (hv : ∀ i, 0≤v i ∧ v i≤B) : 0≤score w v-score (mask keep w) v ∧ score w v-score (mask keep w) v≤B*sum (mask (fun i => !(keep i)) w) := @FiniteMarginsV18.omitted_bound n w v keep B hw hv"),
    ("FiniteMarginsV18.score_split", "{n : Nat} (w v : Fin n → Int) (z : Fin n) : score w v=w z*v z+score (without w z) v := @FiniteMarginsV18.score_split n w v z"),
    ("FiniteMarginsV18.without_nonnegative", "{n : Nat} (w : Fin n → Int) (z : Fin n) (hw : ∀ i, 0≤w i) : ∀ i, 0≤without w z i := @FiniteMarginsV18.without_nonnegative n w z hw"),
    ("FiniteMarginsV18.target_window", "{n : Nat} (w v : Fin n → Int) (z : Fin n) (B : Int) (hw : ∀ i, 0≤w i) (hv : ∀ i, 0≤v i ∧ v i≤B) : w z*v z≤score w v ∧ score w v≤w z*v z+B*sum (without w z) := @FiniteMarginsV18.target_window n w v z B hw hv"),
    ("FiniteMarginsV18.strict_separation", "{n : Nat} (w u v : Fin n → Int) (z : Fin n) (B : Int) (hw : ∀ i, 0≤w i) (hu : ∀ i, 0≤u i ∧ u i≤B) (hv : ∀ i, 0≤v i ∧ v i≤B) (hgap : B*sum (without w z)<w z*(v z-u z)) : score w u<score w v := @FiniteMarginsV18.strict_separation n w u v z B hw hu hv hgap"),
    ("LowerFiniteV18.meet_le_left", "{α : Type u} [inst : Scalar α] (a b : α) : meet a b≤a := @LowerFiniteV18.meet_le_left α inst a b"),
    ("LowerFiniteV18.meet_le_right", "{α : Type u} [inst : Scalar α] (a b : α) : meet a b≤b := @LowerFiniteV18.meet_le_right α inst a b"),
    ("LowerFiniteV18.le_meet", "{α : Type u} [inst : Scalar α] {a b c : α} (ha : c≤a) (hb : c≤b) : c≤meet a b := @LowerFiniteV18.le_meet α inst a b c ha hb"),
    ("LowerFiniteV18.lower_le", "{α : Type u} [inst : Scalar α] {m : Nat} (f : Fin (m+1) → α) (i : Fin (m+1)) : lower f≤f i := @LowerFiniteV18.lower_le α inst m f i"),
    ("LowerFiniteV18.le_lower", "{α : Type u} [inst : Scalar α] {m : Nat} (f : Fin (m+1) → α) (c : α) (h : ∀ i, c≤f i) : c≤lower f := @LowerFiniteV18.le_lower α inst m f c h"),
    ("LowerFiniteV18.lower_monotone", "{α : Type u} [inst : Scalar α] {m : Nat} (f g : Fin (m+1) → α) (h : ∀ i, f i≤g i) : lower f≤lower g := @LowerFiniteV18.lower_monotone α inst m f g h"),
    ("LowerFiniteV18.lower_constant", "{α : Type u} [inst : Scalar α] (m : Nat) (c : α) : lower (fun _ : Fin (m+1) => c)=c := @LowerFiniteV18.lower_constant α inst m c"),
    ("LowerFiniteV18.lower_singleton", "{α : Type u} [inst : Scalar α] (f : Fin 1 → α) : lower f=f 0 := @LowerFiniteV18.lower_singleton α inst f"),
    ("LowerFiniteV18.lower_attained", "{α : Type u} [inst : Scalar α] {m : Nat} (f : Fin (m+1) → α) : ∃ i, lower f=f i := @LowerFiniteV18.lower_attained α inst m f"),
    ("ExpectationContextsV18.expected_monotone", "{α : Type v} [inst : Scalar α] {n : Nat} (w : Probability α n) (f g : Fin n → α) (h : ∀ i, f i≤g i) : expected w f≤expected w g := @ExpectationContextsV18.expected_monotone α inst n w f g h"),
    ("ExpectationContextsV18.expected_constant", "{α : Type v} [inst : Scalar α] {n : Nat} (w : Probability α n) (c : α) : expected w (fun _ => c)=c := @ExpectationContextsV18.expected_constant α inst n w c"),
    ("ExpectationContextsV18.no_empty_probability", "{α : Type v} [inst : Scalar α] : ¬ Nonempty (Probability α 0) := @ExpectationContextsV18.no_empty_probability α inst"),
    ("ExpectationContextsV18.expectation_defined", "{α : Type v} [inst : Scalar α] {H : Type u} {n : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) : (expectation E f w).defined=E := @ExpectationContextsV18.expectation_defined α inst H n E f w"),
    ("ExpectationContextsV18.expectation_value", "{α : Type v} [inst : Scalar α] {H : Type u} {n : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) (h : {h // E h}) : (expectation E f w).eval h=sum (fun i => w.weight i*f h i) := @ExpectationContextsV18.expectation_value α inst H n E f w h"),
    ("ExpectationContextsV18.expectation_active", "{α : Type v} [inst : Scalar α] {H : Type u} {n : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) (h : H) : (relativeDomain P (expectation E f w)).defined h ↔ P h ∧ E h := @ExpectationContextsV18.expectation_active α inst H n P E f w h"),
    ("ExpectationContextsV18.expectation_comparison", "{α : Type v} [inst : Scalar α] {H : Type u} {n : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) (a b : Active P (expectation E f w)) : (activeOrder P (expectation E f w)).le a b ↔ expected w (f ⟨a.val,a.property.2⟩)≤expected w (f ⟨b.val,b.property.2⟩) := @ExpectationContextsV18.expectation_comparison α inst H n P E f w a b"),
    ("ExpectationContextsV18.expectation_observe", "{α : Type v} [inst : Scalar α] {H : Type u} {n : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) (h : H) : observe P (expectation E f w) h = (by classical exact if P h then if he : E h then Outcome.value (expected w (f ⟨h,he⟩)) else .undefined else .illegal) := @ExpectationContextsV18.expectation_observe α inst H n P E f w h"),
    ("ExpectationContextsV18.envelope_monotone", "{α : Type v} [inst : Scalar α] {n m : Nat} (ws : Fin (m+1) → Probability α n) (f g : Fin n → α) (h : ∀ i, f i≤g i) : envelope ws f≤envelope ws g := @ExpectationContextsV18.envelope_monotone α inst n m ws f g h"),
    ("ExpectationContextsV18.envelope_constant", "{α : Type v} [inst : Scalar α] {n m : Nat} (ws : Fin (m+1) → Probability α n) (c : α) : envelope ws (fun _ => c)=c := @ExpectationContextsV18.envelope_constant α inst n m ws c"),
    ("ExpectationContextsV18.envelope_singleton", "{α : Type v} [inst : Scalar α] {n : Nat} (ws : Fin 1 → Probability α n) (v : Fin n → α) : envelope ws v=expected (ws 0) v := @ExpectationContextsV18.envelope_singleton α inst n ws v"),
    ("ExpectationContextsV18.envelope_attained", "{α : Type v} [inst : Scalar α] {n m : Nat} (ws : Fin (m+1) → Probability α n) (v : Fin n → α) : ∃ j, envelope ws v=expected (ws j) v := @ExpectationContextsV18.envelope_attained α inst n m ws v"),
    ("ExpectationContextsV18.lower_defined", "{α : Type v} [inst : Scalar α] {H : Type u} {n m : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) : (lowerContext E f ws).defined=E := @ExpectationContextsV18.lower_defined α inst H n m E f ws"),
    ("ExpectationContextsV18.lower_value", "{α : Type v} [inst : Scalar α] {H : Type u} {n m : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) (h : {h // E h}) : (lowerContext E f ws).eval h=lower (fun j => sum (fun i => (ws j).weight i*f h i)) := @ExpectationContextsV18.lower_value α inst H n m E f ws h"),
    ("ExpectationContextsV18.lower_active", "{α : Type v} [inst : Scalar α] {H : Type u} {n m : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) (h : H) : (relativeDomain P (lowerContext E f ws)).defined h ↔ P h ∧ E h := @ExpectationContextsV18.lower_active α inst H n m P E f ws h"),
    ("ExpectationContextsV18.lower_comparison", "{α : Type v} [inst : Scalar α] {H : Type u} {n m : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) (a b : Active P (lowerContext E f ws)) : (activeOrder P (lowerContext E f ws)).le a b ↔ envelope ws (f ⟨a.val,a.property.2⟩)≤envelope ws (f ⟨b.val,b.property.2⟩) := @ExpectationContextsV18.lower_comparison α inst H n m P E f ws a b"),
    ("ExpectationContextsV18.lower_observe", "{α : Type v} [inst : Scalar α] {H : Type u} {n m : Nat} (P E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) (h : H) : observe P (lowerContext E f ws) h = (by classical exact if P h then if he : E h then Outcome.value (envelope ws (f ⟨h,he⟩)) else .undefined else .illegal) := @ExpectationContextsV18.lower_observe α inst H n m P E f ws h"),
    ("ExpectationContextsV18.int_dirac_value", "(n : Nat) (z : Fin n) (v : Fin n → Int) : expected (intDirac n z) v=v z := @ExpectationContextsV18.int_dirac_value n z v"),
    ("FreeMonotonesV18.can_iff", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (a b : C.Obj) : Can C F a b ↔ ∃ f : C.Hom a b, F f := @FreeMonotonesV18.can_iff C F a b"),
    ("FreeMonotonesV18.can_refl", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (hF : Closed C F) (a : C.Obj) : Can C F a a := @FreeMonotonesV18.can_refl C F hF a"),
    ("FreeMonotonesV18.can_trans", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (hF : Closed C F) {a b c : C.Obj} (hab : Can C F a b) (hbc : Can C F b c) : Can C F a c := @FreeMonotonesV18.can_trans C F hF a b c hab hbc"),
    ("FreeMonotonesV18.target_true", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (z a : C.Obj) : target C F z a=true ↔ Can C F a z := @FreeMonotonesV18.target_true C F z a"),
    ("FreeMonotonesV18.target_context_defined", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (z a : C.Obj) : (targetContext C F z).defined a := @FreeMonotonesV18.target_context_defined C F z a"),
    ("FreeMonotonesV18.target_context_value", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (z a : C.Obj) : (targetContext C F z).eval ⟨a,True.intro⟩=true ↔ ∃ f : C.Hom a z, F f := @FreeMonotonesV18.target_context_value C F z a"),
    ("FreeMonotonesV18.target_context_observe", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (z a : C.Obj) : observe (fun _ => True) (targetContext C F z) a=.value (target C F z a) := @FreeMonotonesV18.target_context_observe C F z a"),
    ("FreeMonotonesV18.target_monotone", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (hF : Closed C F) {a b : C.Obj} (hab : Can C F a b) (z : C.Obj) : boolOrder.le (target C F z b) (target C F z a) := @FreeMonotonesV18.target_monotone C F hF a b hab z"),
    ("FreeMonotonesV18.target_family_complete", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (hF : Closed C F) (a b : C.Obj) : Can C F a b ↔ ∀ z, boolOrder.le ((targetContext C F z).eval ⟨b,True.intro⟩) ((targetContext C F z).eval ⟨a,True.intro⟩) := @FreeMonotonesV18.target_family_complete C F hF a b"),
    ("ScalarV12.intScalar", ": Scalar Int := ScalarV12.intScalar"),
    ("ExpectationContextsV18.Probability", "{α : Type v} [Scalar α] (n : Nat) : Type v := Probability α n"),
    ("ExpectationContextsV18.expectation", "{α : Type v} [Scalar α] {H : Type u} {n : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (w : Probability α n) : Context H α := expectation E f w"),
    ("ExpectationContextsV18.lowerContext", "{α : Type v} [Scalar α] {H : Type u} {n m : Nat} (E : H → Prop) (f : {h // E h} → Fin n → α) (ws : Fin (m+1) → Probability α n) : Context H α := lowerContext E f ws"),
    ("FreeMonotonesV18.targetContext", "(C : ProcCategory.{u,v}) (F : {a b : C.Obj} → C.Hom a b → Prop) (z : C.Obj) : Context C.Obj Bool := targetContext C F z"),
)

def audit_source():
    header = "".join(f"import {name[:-5]}\n" for name in SOURCE_NAMES)
    header += ("open FoundationV5 PartialContextV15 ScalarV12 PrefixWrapperV18\n"
               "open ShortestCodesV18 FiniteMarginsV18 LowerFiniteV18\n"
               "open ExpectationContextsV18 FreeMonotonesV18\nuniverse u v w x\n")
    return header + "\n".join(
        f"noncomputable def registered_{i} {statement}\n#print axioms registered_{i}\n"
        for i, (_, statement) in enumerate(ENTRIES)
    )
