#!/usr/bin/env python3
"""TTAC-D10 blockers B1+B2 builder: REPLAY_RECEIPTS_V1 + PARENT_BINDING_V1 + d2_overrides_e.

Consumes the frozen replay receipts in receipts/d10/*.jsonl (one JSON object
per checker execution; produced by the two-host campaign at merge sha
a70c2f7a) and binds them to atoms:

  B2-PARENT-BIND  : faithful parent rerun of each exact checker on the
                    MATCHED host (billy-laptop -- the host of the original
                    REGISTRY_PATCH_C run_receipt), exit 0 => P 1->3 (E3-class).
  B1-IND-REPLAY   : disjoint host (billy-old), exit 0 AND stdout sha256
                    byte-identical to the matched-host run => R 2->4
                    (E4-class independent replication; determinism verified
                    across hosts AND interpreter generations).

Checker->atom map is semantic, not regex-derived: registry rows T14/T15/T16
carry checker=null (verified against HST_THEOREM_REGISTRY_V1), so no replay
can bind them; the shared REGISTRY_PATCH_C run_receipt cites three checkers
across six rows and must NOT be read as six-way coverage.

FAIL-CLOSED: a checker absent from a host's receipts, a non-zero exit, or a
stdout sha mismatch grants nothing; the atom is listed as residual with the
failing condition named.
"""
import json
from collections import Counter
from pathlib import Path

BASE = Path(__file__).resolve().parent
REC = BASE / "receipts" / "d10"
SHA = "a70c2f7a"  # merge sha the campaign replays against (PR #311 head)

# Semantic checker scope map (HST lane). T14/T15/T16: checker=null in registry.
HST_SCOPE = {
    "exact/check_core_v1.py": ["01", "03", "05", "06", "07", "18"],
    "exact/run_all_v1.py": ["02", "04", "08", "10", "11"],
    "exact/check_t12_v1.py": ["12"],
    "exact/check_t13_v1.py": ["13"],
    "exact/check_t17_v1.py": ["17"],
}
# SEM lane (agent receipts land as sem_replay_*.jsonl): entry points rerun.
# Map verified against ATOM_REGISTRY_V1 current_evidence citations:
# SEM finite-certified atoms cite D17/D18 results (regenerated by run_all);
# PRV-01 cites D19_RESULTS (verdict EXACT_AGREEMENT) -> run_d19.
SEM_ENTRY = {
    "run_all.py": ["ATOM-SEM-01", "ATOM-SEM-02", "ATOM-SEM-04", "ATOM-SEM-05",
                   "ATOM-SEM-06", "ATOM-SEM-08", "ATOM-SEM-10"],
    "run_d19.py": ["ATOM-PRV-01"],
}
# Geometry lane: D10 sparse-donor search replay -> HSG-04 R.
# D10_SPARSE_DONOR_SEARCH itself holds theorem rows + proofs only (no
# executable); the lane's exact checker is geometry_dynamics_check_v1.py.
GEO_ENTRY = {"exact/geometry_dynamics_check_v1.py": ["ATOM-HSG-04"]}

MATCHED_HOST = "billy-laptop"   # original REGISTRY_PATCH_C run host -> P3
DISJOINT_HOST = "billy-old"     # disjoint host -> R4


def load(prefix: str):
    """Return {host: {checker_relpath: receipt}} for a receipt-file prefix."""
    out = {}
    for f in sorted(REC.glob(f"{prefix}_*.jsonl")):
        host = f.stem[len(prefix) + 1:]
        per = {}
        for line in f.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                per[r["checker_relpath"]] = r
        out[host] = per
    return out


def verdicts(rec):
    return " ".join(rec.get("tails") or [])


def by_basename(per, rel_suffix):
    """Find receipt whose checker_relpath ends with the exact/... suffix."""
    return next((r for p, r in per.items() if p.endswith(rel_suffix)), None)


def bind_hst(hst):
    """Yield (atom_id, grants, checker, determinism) for HST atoms.

    P3 gate: matched-host faithful rerun, exit 0 (independent of cross-host
    stdout comparison). R4 gate: disjoint-host exit 0 AND byte-identical
    stdout sha. run_all_v1.py's summary line embeds elapsed seconds and the
    interpreter version, so its raw stdout is NOT byte-identical across
    hosts even though the verdict content (RUN_ALL OK + witness file list)
    is identical; this is recorded as verdict_content_identical, and R4 is
    never claimed for it.
    """
    matched, disjoint = hst.get(MATCHED_HOST, {}), hst.get(DISJOINT_HOST, {})
    if not matched and not disjoint:
        return
    for chk, ids in HST_SCOPE.items():
        m = by_basename(matched, chk)
        d = by_basename(disjoint, chk)
        if not m or m["exit_code"] != 0:
            continue
        byte_ident = bool(d) and d["exit_code"] == 0 and m["stdout_sha256"] == d["stdout_sha256"]
        verdict_ident = byte_ident or (bool(d) and d["exit_code"] == 0
                                       and "RUN_ALL OK" in " ".join(d.get("stdout_tail_last_5_lines", []))
                                       and "RUN_ALL OK" in " ".join(m.get("stdout_tail_last_5_lines", []))
                                       and m.get("repo_sha") == d.get("repo_sha"))
        det = "byte_identical" if byte_ident else ("verdict_content_identical" if verdict_ident else "divergent")
        for n in ids:
            aid = f"ATOM-HST-{n}"
            grants = {}
            # P3: FINITE_CERTIFIED/PROVED atoms whose profile needs P3.
            if n not in ("04", "08"):  # T04/T08 are PARENT_SUFFICIENT P4->P5 (B5, not this campaign)
                grants["P"] = 3
            # R4: only PROVED atoms carry R, and only on byte-identical replay.
            if n not in ("02", "04", "08", "10", "11") and byte_ident:
                grants["R"] = 4
            yield aid, grants, chk, det


def main():
    hst = load("hst_replay")
    sem = load("sem_replay")
    geo = {**load("sem_replay"), **load("geo_replay")}  # geometry checker rows ride the sem receipt files

    rows, overrides = [], {}
    residuals = []

    for aid, grants, chk, det in bind_hst(hst):
        rows.append({"atom_id": aid, "lane": "HST", "checker": chk,
                     "matched_host_exit": 0,
                     "disjoint_host_exit": 0 if det != "matched_only" else None,
                     "determinism": det, "repo_sha": SHA, "grants": grants})
        if grants:
            det_note = ("stdout sha byte-identical across hosts -> R4"
                        if det == "byte_identical" else
                        "run_all summary line embeds elapsed_s+interpreter version: verdict content identical, raw stdout not byte-identical; no R4 claimed")
            overrides[aid] = {
                "R": grants,
                "cls": "E4" if grants.get("R") == 4 else "E3",
                "note": (f"B1+B2 replay campaign @ {SHA}: faithful parent rerun on {MATCHED_HOST} "
                         f"(exit 0, E3-class -> P3); checker {chk}; {det_note}"),
            }

    # SEM lane: entry-point rerun on matched host -> P3 for FINITE_CERTIFIED atoms.
    sem_matched = sem.get(MATCHED_HOST, {})
    for entry, aids in SEM_ENTRY.items():
        hit = next((r for p, r in sem_matched.items() if p.endswith(entry)), None)
        if not hit or hit["exit_code"] != 0:
            if sem_matched:
                residuals.append(f"SEM {entry}: no matched-host exit-0 receipt")
            continue
        for aid in aids:
            grants = {"P": 3} if aid not in ("ATOM-SEM-11", "ATOM-SEM-12", "ATOM-SEM-13") else {}
            # SEM-11/12/13 PARENT_SUFFICIENT P4->P5 = B5; rerun alone grants nothing.
            if not grants:
                residuals.append(f"{aid}: rerun recorded, P5 not grantable by replay (B5)")
                continue
            rows.append({"atom_id": aid, "lane": "SEM", "checker": hit["checker_relpath"],
                         "matched_host_exit": 0, "disjoint_host_exit": None,
                         "stdout_identical": None, "repo_sha": hit.get("repo_sha", ""), "grants": grants})
            overrides[aid] = {
                "R": grants, "cls": "E3",
                "note": f"B2 faithful parent rerun of SEM entry point on {MATCHED_HOST} (exit 0, E3-class -> P3); checker {hit['checker_relpath']}",
            }

    # Geometry lane: disjoint-host replay -> R4 for HSG-04.
    geo_dis = geo.get(DISJOINT_HOST, {})
    for entry, aids in GEO_ENTRY.items():
        hit = next((r for p, r in geo_dis.items() if p.endswith(entry)), None)
        if hit and hit["exit_code"] == 0:
            matched_geo = next((r for p, r in geo.get(MATCHED_HOST, {}).items() if p.endswith(entry)), None)
            byte_ident = matched_geo and matched_geo["stdout_sha256"] == hit["stdout_sha256"]
            for aid in aids:
                grants = {"R": 4} if byte_ident else {}
                rows.append({"atom_id": aid, "lane": "GEOMETRY", "checker": hit["checker_relpath"],
                             "matched_host_exit": 0 if matched_geo else None,
                             "disjoint_host_exit": 0,
                             "determinism": "byte_identical" if byte_ident else "exit0_only",
                             "repo_sha": hit.get("repo_sha", ""), "grants": grants})
                if grants:
                    overrides[aid] = {
                        "R": grants, "cls": "E4",
                        "note": f"B1 disjoint-host replay of geometry lane on {DISJOINT_HOST} (exit 0, stdout sha byte-identical across hosts, E4-class -> R4); checker {hit['checker_relpath']}",
                    }
        elif geo_dis:
            residuals.append(f"GEOMETRY {entry}: no disjoint-host exit-0 receipt")

    residuals += [
        "DEFECT (provenance, lane SEM): committed RV_B1_RESULTS.json carries a post-emission manual amendment (correction_C1 block + amended where_the_positive_lives text, self-dated 2026-09-10) that `python3 -m exact.run_rv_b1` does NOT reproduce; measurements/verdicts unchanged but the artifact is not byte-reproducible from its checker; flagged to lane owner, recorded here so the binding ledger carries it",
        "ENV (lane SEM): run_d21_d22 first pass exits 1 on both hosts under system python (sympy hard import); parent env per D21_D22_PROTOCOL_V1 = python>=3.10 + egglog 13.2.0 + sympy 1.14.0; failed rows retained verbatim in receipts, exit-0 rerun in the parent-equivalent env is the granted row",
        "JITTER (lane SEM): D18/D21 emitted results differ from committed artifacts only in cpu-timing fields (packed_cpu_s, shared_cpu_s, per_query_ordered_cpu_s); byte-identical after stripping; recorded as timing jitter, not divergence",
        "ATOM-SEM-11/12/13 P4->5: parents are P5 proof_class registry rows (parent theorem reconstruction); rerun grants nothing (B5-PARENT-DEEPEN)",
        "ATOM-HST-14/15/16 R1->4: checker=null (B4-NULL-CHECKER owns: author checker or prove impossibility)",
        "ATOM-HST-15 P1->3: parent artifact is a proof, not a runnable checker; not grantable by replay (B4-coupled)",
        "PARENT_SUFFICIENT atoms P4->5 (HST-04/08, SEM-11/12/13, HSG-01, GEF-03, OPA-01): B5-PARENT-DEEPEN",
        "DEV-01/PAR-02/PAR-03 P2->4: parent artifacts are external empirical parents; needs disjoint verification of those artifacts, not checker replay",
    ]

    rr = {
        "schema": "TTAC_REPLAY_RECEIPTS", "version": "V1", "d_step": "TTAC-D10",
        "blockers": ["B1-IND-REPLAY", "B2-PARENT-BIND"], "owner_issue": 277,
        "built_utc": "2026-09-10", "replayed_merge_sha": SHA,
        "receipt_files": [str(p.relative_to(BASE)) for p in sorted(REC.glob("*.jsonl"))],
        "hosts": {"matched": MATCHED_HOST, "disjoint": DISJOINT_HOST},
        "grant_rule": "matched-host exit 0 -> P3 (E3); disjoint-host exit 0 + byte-identical stdout sha -> R4 (E4); anything else grants nothing",
        "bindings": rows,
        "residual_gaps": residuals,
        "census": {"atoms_bound": len(rows),
                   "p3_grants": sum(1 for r in rows if r["grants"].get("P") == 3),
                   "r4_grants": sum(1 for r in rows if r["grants"].get("R") == 4),
                   "by_lane": dict(Counter(r["lane"] for r in rows))},
        "non_final": "EXPLICITLY_NON_FINAL",
    }
    (BASE / "REPLAY_RECEIPTS_V1.json").write_text(json.dumps(rr, indent=1) + "\n")

    pb = {
        "schema": "TTAC_PARENT_BINDING", "version": "V1", "d_step": "TTAC-D10",
        "blocker": "B2-PARENT-BIND", "owner_issue": 277, "built_utc": "2026-09-10",
        "receipts_ref": "REPLAY_RECEIPTS_V1.json",
        "binding_question": "for each atom: which concrete parent artifact does its evidence chain rest on, at what sha, verified on which host(s), at what evidence class?",
        "bindings": [{"atom_id": r["atom_id"], "parent_artifact": r["checker"],
                      "replayed_at_sha": r["repo_sha"] or SHA,
                      "matched_host": MATCHED_HOST if r["matched_host_exit"] == 0 else None,
                      "disjoint_host": DISJOINT_HOST if r["disjoint_host_exit"] == 0 else None,
                      "evidence_class": "E4" if r["grants"].get("R") == 4 else "E3",
                      "grants": r["grants"]} for r in rows],
        "schema_note": "per READINESS_SCHEMA_V1: P3 = faithful parent run at matched information/resources/checker access; NOT_RUN stays 1. Archival sha binding alone never fills P3 (cause of DAG-AMD-1).",
        "non_final": "EXPLICITLY_NON_FINAL",
    }
    (BASE / "PARENT_BINDING_V1.json").write_text(json.dumps(pb, indent=1) + "\n")
    (BASE / "d2_overrides_e.json").write_text(json.dumps(overrides, indent=1, sort_keys=True) + "\n")

    print(f"atoms_bound={len(rows)} p3={rr['census']['p3_grants']} r4={rr['census']['r4_grants']} lanes={rr['census']['by_lane']}")
    for x in residuals:
        print("  RESIDUAL:", x)
    assert rows and overrides
    print("VALIDATION OK")


if __name__ == "__main__":
    main()
