"""Human adjudication verdicts for the frozen census subset.

Keyed by census object_id: {"verdict", "evidence", "notes"}.
Predefined overrides for census-defect annotations use TYPED_OVERRIDE_REASONS.
"""
from __future__ import annotations

TABLE = {
    # --- (a) GREEN mainline ---------------------------------------------
    "V0.2": {"verdict": "CONFIRMED",
             "evidence": "gmi-adaptive-row-confidence-v1/raw/OCM_FOUNDATIONS_CLOSURE_V1.md:L7",
             "notes": "Explicitly not an unconditional efficiency theorem; finite-exact quantifier matches statement."},
    "ANALOG_SEMANTICS_THEOREM_V1": {"verdict": "CONFIRMED",
                                    "evidence": "gmi-analog-semantics-closure-v1/ANALOG_SEMANTICS_THEOREM_V1.md:L6",
                                    "notes": "Bounded-overhead reduction claim; analytic reduction + ledger receipt."},
    "AS-1": {"verdict": "CONFIRMED",
             "evidence": "gmi-analog-semantics-closure-v1/ANALOG_SEMANTICS_THEOREM_V1.md:L19",
             "notes": "Assumption-indexed conditional reduction; conditional quantifier declared."},
    "F2-U": {"verdict": "CONFIRMED",
             "evidence": "gmi-capability-ceilings-v1/FORMALIZATION_V1.md:L173",
             "notes": "Finite update-transcript reachability ceiling claimed and scoped finite; P1 label consistent."},
    "F1-S": {"verdict": "CONFIRMED",
             "evidence": "gmi-capability-contract-v1/FORMALIZATION_V1.md:L120",
             "notes": "Simultaneous coverage at common assay, sampled-statistical bound; consistent."},
    "HELD_FAMILY_SCORE_V1": {"verdict": "CONFIRMED",
                             "evidence": "gmi-capability-held-score-v1/README.md:L9",
                             "notes": "Receipt/score claim at finite certificate scope."},
    "CAPABILITY_INTERACTIONS_UNIFIED_THEOREM_V1": {"verdict": "OVERSTRONG",
                                                   "evidence": "gmi-capability-interactions-unified-v1/CAPABILITY_INTERACTIONS_UNIFIED_THEOREM_V1.md:L13,L68",
                                                   "notes": "Name says 'Unified Theorem for all 27 A4 capabilities'; proof is a proof sketch whose cases assert independence/synergy/redundancy from resource-channel overlap and rule out interference via inherited PVR-3, with a caveat that 'joint burden equals...' on shared channels mixes the max and sum rules. The universal phrasing 'for any two capabilities' exceeds a pure 27x27 finite classification once the rules rest on unproven equalities (joint=sum / joint=max)."},
    "TYPED_DELEGATION_COST_THEOREM_V1": {"verdict": "CONFIRMED",
                                         "evidence": "gmi-delegation-cost-repair-v1/CORE.md:L7",
                                         "notes": "Typed delegation cost at finite exact scope."},
    "DT-2A": {"verdict": "CONFIRMED",
              "evidence": "gmi-developmental-uncertainty-transport-v1/FORMALIZATION_V1.md:L138",
              "notes": "Finite chain composition bound; analytic induction; declared finite horizon."},
    "DT-2B": {"verdict": "CONFIRMED",
              "evidence": "gmi-developmental-uncertainty-transport-v1/FORMALIZATION_V1.md:L176,L196",
              "notes": "Name mentions countably many steps; statement carefully bounds sum beta_t = beta * N/(N+1) < beta and never claims the infinite-horizon probability event outright -- the finite-attained-times scope is honored in the proof. Census quantifier FINITE_EXACT is fair."},
    "DT-3B": {"verdict": "CONFIRMED",
              "evidence": "gmi-developmental-uncertainty-transport-v1/FORMALIZATION_V1.md:L280",
              "notes": "Negative coverage guarantee claim, sampled-statistical; consistent."},
    "A2-R": {"verdict": "CONFIRMED",
             "evidence": "gmi-ecology-contract-v2/FORMALIZATION_V2.md:L71",
             "notes": "Prices-cannot-replace-hard-budgets with exact witness; existential witness quantifier."},
    "DRS-3": {"verdict": "CONFIRMED",
              "evidence": "gmi-experimental-validation-v1/raw/.../RECURSIVE_GAP_AUDIT_20260913.md:L66",
              "notes": "Assimilation note that a requested axis is already parent-owned; not an overclaim."},
    "EC-2": {"verdict": "CONFIRMED",
             "evidence": "gmi-extended-cognition-closure-v1/EXTENDED_COGNITION_THEOREM_V1.md:L41",
             "notes": "Finite reduction to memory and dynamics; finite-exact scope."},
    "TQI.2": {"verdict": "CONFIRMED",
              "evidence": "gmi-finite-quantum-cover-v1/PARENTS_AND_COSTS_V1.md:L9",
              "notes": "Parent literature row (Watrous Theorem 2.42); registered as a parent citation, not a novel claim."},
    "ADAPTIVE-EXAMPLES": {"verdict": "CONFIRMED",
                          "evidence": "gmi-formal-derivation-v1/ADAPTIVE.md:L3",
                          "notes": "Simultaneous statistical validity for countably many adaptively born claims; the statement immediately disclaims 'does not prove learned state'. Sampled-statistical + analytic."},
    "CLM-5": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/COMPOSITIONAL_LANGUAGE_CLAIMS_V1.md:L11",
              "notes": "HELD_OUT quantifier + COMPUTER_ASSISTED_EXHAUSTIVE evidence with 94,851 exact checks declared on k=2..4, sizes 2..4 exhaustive microscope; claim ceiling disclaims natural-language universality. Quantifier (held-out block values) matches evidence."},
    "ACTIVE-EXPERIMENT": {"verdict": "CONFIRMED",
                          "evidence": "gmi-grand-unification-v1/CONTROLLED_ACQUISITION_INFORMATION_STATE_THEOREM_V1.md:L3",
                          "notes": "Finite deterministic robust theorem, parent acknowledged."},
    "TRAINING-AND-DEVELOPMENT": {"verdict": "CONFIRMED",
                                 "evidence": "gmi-grand-unification-v1/DEVELOPMENTAL_REACHABILITY_SELECTION_THEOREM_V1.md:L3",
                                 "notes": "Finite exact witness; conditional criterion."},
    "ERI-4": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/EMPIRICAL_RESOURCE_IDENTIFICATION_THEOREM_V1.md:L102",
              "notes": "Confidence transport theorem, sampled-statistical bounds; consistent."},
    "FP-4": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/FAMILY_FRONTIER_PHASE_THEOREM_V1.md:L163",
             "notes": "Negative theorem: no universal neural/non-neural theorem from semantics alone. Universal quantifier appears inside a negation; analytic proof of the impossibility."},
    "HPL-2003-97R1": {"verdict": "CONFIRMED",
                      "evidence": "gmi-grand-unification-v1/FINITE_DATA_PARENTS_AND_COSTS_V1.md:L7",
                      "notes": "Parent citation row (Weissman et al.); not a novel claim."},
    "GEI-1": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/GENERALIZATION_ECOLOGY_INFERENCE_THEOREM_V1.md:L34",
              "notes": "Finite-sample non-identifiability; negative theorem consistent with its quantifier."},
    "GIR-3": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/GENERALIZATION_IDENTIFIABILITY_CLAIMS_V1.md:L9",
              "notes": "Conditional information-boundary claim; declared conditional."},
    "AR-7": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/INTRAFAMILY_ARCHITECTURE_REFINEMENT_THEOREM_V1.md:L116",
             "notes": "Sparse conditional expert routing theorem; conditional scope declared."},
    "ARCHITECTURE-DERIVATION": {"verdict": "CONFIRMED",
                                "evidence": "gmi-grand-unification-v1/MORPHOLOGY_SELECTION_THEOREM_V1.md:L3",
                                "notes": "Conditional architecture-derivation criterion + exact finite witness."},
    "READY_FORMAL": {"verdict": "CONFIRMED",
                     "evidence": "gmi-grand-unification-v1/NN_NONNN_EMPIRICAL_EVIDENCE_READINESS_AUDIT_V1.md:L26",
                     "notes": "Readiness-status token, not a scientific overclaim."},
    "EXECUTED_AT_REGISTERED_FOUR_CANDIDATE_SCOPE": {"verdict": "CONFIRMED",
                                                    "evidence": "gmi-grand-unification-v1/NN_NONNN_POINT_PARITY3_HOSTED_PROVENANCE_V4.json:L51",
                                                    "notes": "Executed-at-scope provenance statement; sampled statistical with declared four-candidate scope."},
    "NON-NEURAL": {"verdict": "CONFIRMED",
                   "evidence": "gmi-grand-unification-v1/NONNEURAL_CONSTRUCTIVE_DERIVATION_THEOREM_V1.md:L3",
                   "notes": "Exact finite non-neural compilation + minimal-state boundary."},
    "PROGRAMME_METHOD_NOVELTY": {"verdict": "CONFIRMED",
                                 "evidence": "gmi-grand-unification-v1/NOVELTY_PARENT_SUBTRACTION_V1.md:L49",
                                 "notes": "Parent-subtraction row attributing method tools to established disciplines."},
    "SUBSTRATE-LAW": {"verdict": "CONFIRMED",
                      "evidence": "gmi-grand-unification-v1/PHYSICAL_RESOURCE_BRIDGE_THEOREM_V1.md:L3",
                      "notes": "Substrate-law conditions explicit + exact finite witnesses."},
    "PLANNING_SEMANTIC_RESOLUTION_CLAIMS_V1": {"verdict": "CONFIRMED",
                                               "evidence": "gmi-grand-unification-v1/PLANNING_REACHABILITY_SEMANTICS_AND_ID_CORRECTION_V1.md:L10",
                                               "notes": "Assignment ledger for PSR-3/4/5; existential witness scope."},
    "PRS-1": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/PLANNING_REACHABILITY_SEMANTICS_AND_ID_CORRECTION_V1.md:L45",
              "notes": "Exact/bounded divergence theorem at finite scope."},
    "GMI-AUDIT-SYM-01": {"verdict": "CONFIRMED",
                         "evidence": "gmi-grand-unification-v1/RECURSIVE_AUDIT_COMPACT_SYMMETRY_V1.md:L9",
                         "notes": "Finite-support measures rotation-stability; analytic; finite-exact."},
    "GMI-AUDIT-SYM-02": {"verdict": "CONFIRMED",
                         "evidence": "gmi-grand-unification-v1/RECURSIVE_AUDIT_COMPACT_SYMMETRY_V1.md:L10",
                         "notes": "Statement itself says 'every orbit atom has coordinate 0' -- the universal is over the declared compact convex class with analytic proof; finite-exact quantifier is fine given the explicit class."},
    "GMI-AUDIT-SYM-03": {"verdict": "CONFIRMED",
                         "evidence": "gmi-grand-unification-v1/RECURSIVE_AUDIT_COMPACT_SYMMETRY_V1.md:L11",
                         "notes": "Constructive no-Pareto-point witness with p in (0,1); existential witness."},
    "PN-5": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/RECURSIVE_GAP_AUDIT_20260913.md:L88",
             "notes": "Closed-parity-gap audit note naming two opposing results; not an overclaim."},
    "RM-1": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/RECURSIVE_MORPHOGENESIS_THEOREM_V1.md:L34",
             "notes": "Conditional closure of Lift(G); conditional quantifier declared."},
    "RDP-3": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/ROBUST_DECISION_PRECISION_CLAIMS_V1.md:L9",
              "notes": "Exact robust-optimum preservation with explicit margin; +107,163 exact applications declared."},
    "FINITE-REGRET": {"verdict": "CONFIRMED",
                      "evidence": "gmi-grand-unification-v1/ROBUST_DECISION_PRECISION_THEOREM_V1.md:L3",
                      "notes": "Finite-regret theorem with explicit score domain and sharp exact witnesses."},
    "SET-THEORETIC": {"verdict": "CONFIRMED",
                      "evidence": "gmi-grand-unification-v1/SEMANTIC_STATE_REFINEMENT_THEOREM_V1.md:L3",
                      "notes": "Exact set-theoretic theorem; finite exhaustive check declared green at scope."},
    "SR-1": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/SEMANTIC_STATE_REFINEMENT_THEOREM_V1.md:L46",
             "notes": "Conditional monotonicity with same E,K; conditional scope."},
    "SR-2": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/SEMANTIC_STATE_REFINEMENT_THEOREM_V1.md:L62",
             "notes": "Conditional; consistent."},
    "SD-GR5": {"verdict": "CONFIRMED",
               "evidence": "gmi-grand-unification-v1/SUFFICIENCY_DIRECTIONS_AUDIT_V1.md:L11",
               "notes": "Self-predictor existence under excluded diagonal feedback; conditional-existential."},
    "SD-ERI5": {"verdict": "CONFIRMED",
                "evidence": "gmi-grand-unification-v1/SUFFICIENCY_DIRECTIONS_AUDIT_V1.md:L12",
                "notes": "Statement: a coordinate lower envelope can move either way under arbitrary subset refinement. Universal quantifier over refinements with analytic argument; negative-result theorem; consistent."},
    "GMI_OPERATIONAL_COMPLETENESS_THEOREM_V1": {"verdict": "CONFIRMED",
                                                "evidence": "gmi-grand-unification-v1/UNCOMPUTABILITY_BOUNDARY_THEOREM_V1.md:L44",
                                                "notes": "Finite operational completeness with effectively enumerable realization register; exhaustive evidence scoped finite."},
    "D1-D8": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/closure-602-v1/GMI_602_CLOSURE_DEPENDENCIES_V1.json:L75",
              "notes": "Machine metadata row: FINITE_CLOSURE_PLUS_UNIVERSAL_IMPOSSIBILITY_WITH_CANDIDATE_FINITE_REQUIREMENT, evidence_status OPEN. The STATUS IS OPEN; this is not a completed universal claim."},
    "ALL_PARENTS_KNOWN": {"verdict": "CONFIRMED",
                          "evidence": "gmi-grand-unification-v1/closure-602-v1/GMI_602_FORMAL_GAP_CLOSURE_V2.md:L549",
                          "notes": "Row text explicitly says no ALL_PARENTS_KNOWN theorem exists. Census classed a negation-containing row as a theorem; the object is genuine but the classifier mislabeled it. CONFIRMED at scope: the row is a correct negative."},
    "META-1": {"verdict": "CONFIRMED",
               "evidence": "gmi-metacognition-v1/OPERATIONS_V1.md:L3",
               "notes": "Confidence=surviving-candidate; sampled-statistical; linked theorem."},
    "F4-C": {"verdict": "CONFIRMED",
             "evidence": "gmi-morphology-descriptor-v1/FORMALIZATION_V1.md:L50",
             "notes": "Conditional: if validate_descriptor returns normally then exactly the twelve registered families; conditional + analytic."},
    "MORPHOLOGY_PHASE_RV_THEOREM_V1": {"verdict": "CONFIRMED",
                                       "evidence": "gmi-morphology-phase-rv-v1/MANIFEST.json:L8",
                                       "notes": "Manifest row describing a held-out prediction protocol at registered scope."},
    "W4-C": {"verdict": "CONFIRMED",
             "evidence": "gmi-novel-intelligence-w4-v1/FORMALIZATION_V1.md:L56",
             "notes": "W4 at registered finite family scope; scope spelled in title."},
    "D-FL1": {"verdict": "CONFIRMED",
              "evidence": "gmi-section-d-free-lunch-v1/RESULTS_AND_PROOF_V1.md:L83",
              "notes": "Conditional free lunch; conditional quantifier declared."},
    "EXACT_4": {"verdict": "CONFIRMED",
                "evidence": "gmi-section-d-phase-winners-v2/FREEZE_V2.md:L278",
                "notes": "Explicitly disclaims EXACT_4/neural/DNF primitives; mechanized proof of the generic composition mechanism."},
    "UNIVERSAL_BEST_SELECTOR_LANGUAGE": {"verdict": "CONFIRMED",
                                         "evidence": "gmi-symbolic-selector-derivation-v1/SYMBOLIC_SELECTOR_DERIVATION_THEOREM_V1.md:L87",
                                         "notes": "A forbidden-claim guard string inside validate_issue_602_reconciliation_v1.py:L42. The referenced theorem doc explicitly forbids UNIVERSAL_BEST_SELECTOR_LANGUAGE as an overclaim; the census registered the guard as a THEOREM with UNIVERSAL quantifier. The object is a harness assertion, not a claim; census-defect row. Semantically the package is exemplary (no universal best-selector claim)."},
    "TT-1": {"verdict": "CONFIRMED",
             "evidence": "gmi-threshold-task-frontier-v1/check_frontier_v1.py:L2",
             "notes": "Docstring naming the complete finite payload for TT-1..TT-7; harness annotation."},
    "U_AND": {"verdict": "CONFIRMED",
              "evidence": "gmi-useful-descendant-evolvability-v1/FORMALIZATION_V1.md:L169",
              "notes": "Claim's kill conditions listed; finite-exact enumeration declared with fail-conditions."},
    "GMI_EFFECTIVE_RANK_ESTIMATION_THEOREMS_V1": {"verdict": "CONFIRMED",
                                                  "evidence": "machine-intelligence-morphogenesis-v1/GMI_APPROXIMATE_PREDICTIVE_STATE_SPECTRAL_THEOREM_V1.md:L68",
                                                  "notes": "Perturbation bound: every singular value moves by at most eta -- an analytic statement with a genuine forall over singular values; claims stability only when spectral gap exceeds margin. Consistent universal+analytic."},
    "BR-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_BASIN_RESTART_DEVELOPMENT_THEOREM_V1.md:L39",
             "notes": "Validation lower confidence on basin mass; sampled-statistical."},
    "PARENT-OWNED": {"verdict": "CONFIRMED",
                     "evidence": "machine-intelligence-morphogenesis-v1/GMI_BIAS_ECOLOGY_PHASE_THEOREM_V1.md:L3",
                     "notes": "Status line: formula finite phase theorem is algebra/NFL parent-owned. Correctly attributes the mathematics."},
    "CCD-1": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLASSICAL_DOMAIN_COLLAPSE_THEOREM_V1.md:L27-39",
              "notes": "Universal classical simulation over ordinary classical computable machines: standard universal-program-mechanism argument, analytic proof sketch, plus corollaries that explicitly scope resource claims away. 'Universal' is the standard computability-theory meaning; consistent with analytic evidence."},
    "DE-3": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_DESCRIPTOR_ESTIMATION_BOUNDS_V1.md:L139",
             "notes": "Residual-rate confidence interval; sampled-statistical + analytic."},
    "DP2-6": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_DEVELOPMENTAL_POTENTIAL_THEOREMS_V2.md:L212",
              "notes": "Exact finite-horizon switch criterion; finite horizon declared in title."},
    "CI-T1": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_DOMAIN_CAPABILITY_IDENTIFIABILITY_THEOREMS_V1.md:L27",
              "notes": "Negative theorem: finite data do not identify the asymptote; analytic."},
    "CI-T2": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_DOMAIN_CAPABILITY_IDENTIFIABILITY_THEOREMS_V1.md:L76",
              "notes": "Negative theorem for the exponent, same style; analytic."},
    "DSAT-3": {"verdict": "CONFIRMED",
               "evidence": "machine-intelligence-morphogenesis-v1/GMI_DOMAIN_DISCOVERY_SATURATION_THEOREMS_V1.md:L178",
               "notes": "Heterogeneous encoding coverage bound; sampled-statistical."},
    "DSAT-1": {"verdict": "CONFIRMED",
               "evidence": "machine-intelligence-morphogenesis-v1/GMI_DOMAIN_DISCOVERY_SATURATION_THEOREMS_V1.md:L48",
               "notes": "Finite richness bound; finite-exact."},
    "POSET_NOJOIN": {"verdict": "CONFIRMED",
                     "evidence": "machine-intelligence-morphogenesis-v1/GMI_DOMAIN_N3_N10_EXECUTED_V1.md:L183",
                     "notes": "Out-of-sample negative-twin attribution law, 16 of 16; sampled-statistical with explicit out-of-sample claim."},
    "EG-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_ENERGY_AND_ADVERSARIAL_GENERATIVE_THEOREMS_V1.md:L51",
             "notes": "Exact finite normalization requires global aggregate information; finite-exact + analytic."},
    "GM-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_GRAPH_MESSAGE_COMMUNICATION_THEOREMS_V1.md:L81",
             "notes": "Finite-hop indistinguishability; finite-exact + analytic."},
    "GMI_JOINT_ENVELOPE_ATTAINMENT_RECEIPT_V1": {"verdict": "CONFIRMED",
                                                 "evidence": "machine-intelligence-morphogenesis-v1/GMI_JOINT_ENVELOPE_ATTAINMENT_CORRECTION_V1.md:L27",
                                                 "notes": "Receipt claim with explicit kill conditions incl. 'any claim of infinite-set attainment without an additional assumption' -- correctly bounded."},
    "SEARCH-T1": {"verdict": "CONFIRMED",
                  "evidence": "machine-intelligence-morphogenesis-v1/GMI_KNOWN_DOMAIN_CAPABILITY_THEOREMS_V1.md:L291",
                  "notes": "Adversarial exhaustive-search lower bound; exhaustive evidence scoped to registered finite universe."},
    "KF-3": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_KNOWN_FORM_DERIVATION_THEOREMS_V1.md:L124-130",
             "notes": "Posterior sufficiency: for finite latent set H, posterior vector is sufficient for every decision whose consequence depends only on (h,a). Standard Bayes; universal quantifier over actions and utility vectors as stated; finite H declared."},
    "KF-16": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_KNOWN_FORM_DERIVATION_THEOREMS_V2.md:L85",
              "notes": "Finite graph receptive field; finite-exact."},
    "F.01": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_KNOWN_FORM_RECURSIVE_REGISTER_V2.md:L11",
             "notes": "Registry row (atom ID dependency list); harness annotation not an empirical claim."},
    "GI-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_MULTI_TASK_GRADIENT_INTERFERENCE_THEOREMS_V1.md:L89",
             "notes": "Sufficient finite-step no-harm condition; finite-exact + analytic."},
    "ND-1": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_NEURAL_DEPTH_AND_QD_ARCHIVE_THEOREMS_V1.md:L23",
             "notes": "Parent theorem (depth separation exists) -- explicitly attributed as parent result."},
    "NS-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_NEUTRAL_SEARCH_ADEQUACY_THEOREM_V1.md:L31",
             "notes": "Stochastic witness recovery bound; existential witness quantifier."},
    "NC-3": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_NONCLASSICAL_END_TO_END_PHASE_THEOREM_V1.md:L65",
             "notes": "Shot/sample readout scaling; sampled-statistical."},
    "COST-LABEL": {"verdict": "CONFIRMED",
                   "evidence": "machine-intelligence-morphogenesis-v1/GMI_OPERATIONAL_COMPLETENESS_THEOREM_V1.md:L3",
                   "notes": "Finite operational scope with decidable comparisons and cost-label reachability; scoped."},
    "FOC-4": {"verdict": "CONFIRMED",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_OPERATIONAL_COMPLETENESS_THEOREM_V1.md:L79",
              "notes": "Bounded developmental reachability theorem; bounded scope in title."},
    "RV-377-196": {"verdict": "CONFIRMED",
                   "evidence": "machine-intelligence-morphogenesis-v1/GMI_REAL_TRANSFER_RV_377_194_FREEZE.md:L143",
                   "notes": "Sizing-error correction note reserving RV-377-196 only under a provable premise; not an overclaim."},
    "RH-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_RECURRENT_STATE_VS_HISTORY_REPLAY_THEOREMS_V1.md:L58-70",
             "notes": "Replay burden at every time: sum_{t=1}^{T} t = T(T+1)/2 input visits under unit cost; a clean arithmetic-forall theorem with analytic argument, and the section explicitly frames dependence on query frequency/prices. Consistent."},
    "SG-1": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_STABILITY_GENERALIZATION_THEOREMS_V1.md:L43",
             "notes": "Expected generalization gap bounded by stability; finite-exact."},
    "TI-2": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/GMI_TARGET_INFORMATION_ACQUISITION_THEOREM_V1.md:L95",
             "notes": "Conditional acquisition burden; conditional declared."},
    "TF-055": {"verdict": "CONFIRMED",
               "evidence": "machine-intelligence-morphogenesis-v1/GMI_TRANSFORMER_MICROFEATURE_REGISTRY_V1.md:L140",
               "notes": "Registry row: REGISTERED_FOR_EXPERIMENT status, UC (unchecked); not a completed claim."},
    "ITER_FROZEN": {"verdict": "CONFIRMED",
                    "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/axis_a.py:L35",
                    "notes": "Negative twin fixture (iterate law removed) in executable microscope; harness annotation."},
    "HOPFIELD_RND": {"verdict": "CONFIRMED",
                     "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/dc_energy.py:L16",
                     "notes": "Negative-twin fixture doc; harness annotation."},
    "L8.1": {"verdict": "CONFIRMED",
             "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/predict_domain.py:L92",
             "notes": "Law table row inside instrument code; conditional domain-law statement with explicit conditions."},
    "HELD-OUT": {"verdict": "CONFIRMED",
                 "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/predict_heldout_ecology.py:L1",
                 "notes": "Docstring: C box 14 held-out prediction protocol; registered held-out scope."},
    "X-TMT9": {"verdict": "CONFIRMED",
               "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/tmt.py:L227",
               "notes": "Harness check record: three exact rational 2x2 linear blocks with exact finite-difference Jacobians; scope spelled."},
    "PER_EVAL": {"verdict": "CONFIRMED",
                 "evidence": "machine-intelligence-morphogenesis-v1/gmi_microscope/update_law_witness.py:L168",
                 "notes": "Per-evaluation cost line in instrument code; conditional."},
    "QUERY_IN": {"verdict": "CONFIRMED",
                 "evidence": "machine-intelligence-morphogenesis-v1/independence/ig5_independent_primitives_v1.json:L172",
                 "notes": "Composition-rules definition (finite DAG over allowed kinds); definitional."},
    "VEC_STATE": {"verdict": "CONFIRMED",
                  "evidence": "machine-intelligence-morphogenesis-v1/independence/ig5_independent_primitives_v1.json:L173",
                  "notes": "Selection-justification criterion text; the 'keep only if parent needs it' rule is a registry criterion, not a theorem about vectors."},
    "DISCRETE_FINITE": {"verdict": "CONFIRMED",
                        "evidence": "machine-intelligence-morphogenesis-v1/signature_hole_census.py:L59",
                        "notes": "Row in the signature-hole census (M0 finite transducer, inert automaton, no update law); fixture annotation."},
    # --- Ledger/registry-sourced GREEN rows: census-registered as claims
    # These rows are status/claim-movement annotations inside REVIVAL_LEDGER
    # jsonl / GAP_LEDGER md / NOTE_QUESTIONS_STATUS / COLLISION_MATRIX, not
    # theorem declarations. They cannot be adjudicated as claims; the census
    # registered them because the line matched both an explicit ID and the
    # marker regex. Verdict: UNKNOWN with the census-defect note.
    "FAILS_AS_FROZEN": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                        "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L13",
                        "notes": "P4 claim-movement ledger row."},
    "UNKNOWN_MORPHOLOGY_UNEARNED": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                    "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L24",
                                    "notes": "B7 blocker status row."},
    "EARNED_AT_EXACT_SCOPE": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                              "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L31",
                              "notes": "ChatGPT-lane earned-rung status row with explicit 'not a new-family' language; the census flagged it UNIVERSAL/GREEN because the row contains 'every seed'-scope text."},
    "PREDICTION_WRITING": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                           "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L32",
                           "notes": "ChatGPT-lane PARENT_FRONTIER_HOLE_NOT_SUPPORTED status."},
    "L8-OCCUPANCY": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                     "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L49",
                     "notes": "L8 PROVED_AT_SCOPE + OPEN_BLOCKING status row."},
    "RV-377-028": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L50",
                   "notes": "Invalidated-and-replaced revival note."},
    "OPEN_BLOCKING": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                      "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L59",
                      "notes": "G15 gap status row."},
    "RV-377-081": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L60",
                   "notes": "G15 executed-negative status (0 of 3 trials)."},
    "RV-377-087": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L64",
                   "notes": "FALSIFIED descriptor-hypothesis status; census flagged UNIVERSAL from 'every seed'."},
    "STAGE_ECO_V32_ECO_AXIS": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                               "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L71",
                               "notes": "Ecology-axis calibration-disclosure status."},
    "GMI_K5_BH_REVIVAL_PLAN_V8": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                  "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L79",
                                  "notes": "Revival plan status row."},
    "CROSSOVER_CELL_WITHIN_FINITE_SAMPLE_BAND": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                 "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L81",
                                                 "notes": "Corrigendum annotation row."},
    "ATTRIBUTION_KILLED": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                           "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L82",
                           "notes": "Attribution-negative status row."},
    "GMI-RT-V3R2": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                    "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L83",
                    "notes": "Real-transfer calibration row."},
    "PHYSICAL-MEASUREMENT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                             "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L84",
                             "notes": "Quantum circuit-model calibration row."},
    "SKEWED_BINARY": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                      "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L86",
                      "notes": "Near-degeneracy threshold calibration row."},
    "PREDICTION_HELD": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                        "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L87",
                        "notes": "Held-out bar calibration row."},
    "RV-377-201": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L89",
                   "notes": "Smoke-run calibration row."},
    "G15_STEP_TWO_REACHED": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                             "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER.jsonl:L92",
                             "notes": "Boundary-theorem evidence-tier annotation; row text demotes G15_STEP_TWO_REACHED."},
    "RV-377-099": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_B2.jsonl:L10",
                   "notes": "Biosphere experiment revival record."},
    "RV-377-091": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_B2.jsonl:L2",
                   "notes": "Biosphere experiment revival record."},
    "RV-377-092": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_B2.jsonl:L3",
                   "notes": "Biosphere experiment revival record."},
    "RV-377-093": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_B2.jsonl:L4",
                   "notes": "Biosphere experiment revival record."},
    "RV-377-095": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_B2.jsonl:L6",
                   "notes": "Biosphere experiment revival record."},
    "RV-377-046": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_DC2_DC7_DC9.jsonl:L1",
                   "notes": "DC2 self-organizing-descent revival record."},
    "RV-377-054": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_DC2_DC7_DC9.jsonl:L3",
                   "notes": "DC9 oscillatory revival record."},
    "RV-377-063": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_F4_F6.jsonl:L1",
                   "notes": "Codex-lane predicted-machine revival record."},
    "RV-377-069": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_GAPS.jsonl:L3",
                   "notes": "G8 closed-at-scope status note."},
    "PROG_SEARCH": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                    "evidence": "machine-intelligence-morphogenesis-v1/REVIVAL_LEDGER_N3_N10.jsonl:L4",
                    "notes": "Calibration-disclosure row."},
    "RC-07": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
              "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V3.md:L20",
              "notes": "Closed-formal gap status row with 9,330-count evidence line."},
    "GMI_BASIN_RESTART_DEVELOPMENT_THEOREM_V1": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                 "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V4.md:L21",
                                                 "notes": "T1 gap-ledger row referencing the theorem doc."},
    "GMI_FINITE_PORTFOLIO_SELECTION_BOUND_V1": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V6.md:L13",
                                                "notes": "Replacement-note row for an invalid bound."},
    "LEARNING-SCALE": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                       "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V7.md:L37",
                       "notes": "Untested empirical row (explicit 'untested')."},
    "NON-FINAL": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                  "evidence": "machine-intelligence-morphogenesis-v1/GMI_NOTE_QUESTIONS_STATUS_V1.md:L3",
                  "notes": "Status header: explicitly NON-FINAL answer sheet."},
    "GMI_SPECIALIZATIONS_V1": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                               "evidence": "machine-intelligence-morphogenesis-v1/GMI_NOTE_QUESTIONS_STATUS_V1.md:L56",
                               "notes": "Status-note derivation summary."},
    "RV-377-194": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                   "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L3",
                   "notes": "Status line: ALL FINITE OPERATIONAL CLOSURE GATES GREEN, with explicit 'unrestricted/historical-novelty claims remain outside'. Census flagged UNIVERSAL from 'ALL'."},
    "FINITE_OPERATIONAL_CAPABILITY_SET_EXACT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L17",
                                                "notes": "Closure-ledger row naming the exact finite result."},
    "FINITE_OPERATIONAL_FRONTIER_EXACT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                          "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L18",
                                          "notes": "Closure-ledger row."},
    "FINITE_OPERATIONAL_OPTIMAL_FIBER_EXACT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                               "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L19",
                                               "notes": "Closure-ledger row."},
    "FINITE_BUDGET_DEVELOPMENTAL_REACHABILITY_EXACT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                       "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L20",
                                                       "notes": "Closure-ledger row."},
    "FINITE_REGISTERED_STOCHASTIC_CONTROL_EXACT": {"verdict": "UNKNOWN", "census_defect": "LEDGER_ROW_REGISTERED_AS_CLAIM",
                                                   "evidence": "machine-intelligence-morphogenesis-v1/GMI_CLOSURE_GAP_LEDGER_V10.md:L21",
                                                   "notes": "Closure-ledger row."},
    "GRAND_GMI_EMPIRICAL_PROGRAMME_COMPLETE": {"verdict": "CONFIRMED",
                                               "evidence": "gmi-grand-unification-v1/MASTER_CLOSURE_LEDGER_V1.md:L86",
                                               "notes": "Programme-completeness ledger reference; scoped to registered programme rows."},
    "RQR-1": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/SCIENTIFIC_GAP_QUEUE_V2.md:L32",
              "notes": "Pairwise-compatibility-reconstructs-costs row in the gap queue; analytic theorem row recorded as an open science note."},
    "FORMAL_DERIVATION_INTEGRATION_V1": {"verdict": "CONFIRMED",
                                         "evidence": "gmi-grand-unification-v1/SCIENTIFIC_GAP_QUEUE_V2.md:L46",
                                         "notes": "Sufficiency note for operational core; not an overclaim."},
    "CD-1": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_V1.md:L30",
             "notes": "Claim-ledger row."},
    "CD-2": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_V1.md:L31",
             "notes": "Claim-ledger row."},
    "SA-1": {"verdict": "CONFIRMED",
             "evidence": "grand-unification-v1/CLAIM_LEDGER_V2.md:L29",
             "notes": "Representation preserves every registered response iff equality classes refine the response quotient -- true extensional statement with analytic argument; universal over registered responses."},
    "SA-4": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_V2.md:L32",
             "notes": "Claim-ledger row, finite-exact."},
    "S_T": {"verdict": "CONFIRMED",
            "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_V2.md:L9",
            "notes": "Claim-ledger row."},
    "CA-2": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/CONTROLLED_ACQUISITION_CLAIM_LEDGER_V1.md:L8",
             "notes": "Controlled-acquisition claim row, finite-exact."},
    "U_A-L_A": {"verdict": "CONFIRMED",
                "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_FAMILY_PHASE_V1.md:L22",
                "notes": "Ledger row: upper cost below rival lower bounds certifies witness regret -- conditional claim about certified witness regret vs attainment; statement scoped to vertical county."},
    "GG-P2": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_PROOF_REASONING_V1.md:L8",
              "notes": "Canonical exact proof state = quotient by equality of obligation-relevant responses; analytic definitional theorem."},
    "GG-P3": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_PROOF_REASONING_V1.md:L9",
              "notes": "Ledger row."},
    "GG-P6": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_PROOF_REASONING_V1.md:L12",
              "notes": "Ledger row, existential witness."},
    "GG-R2": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_REFLECTIVE_V1.md:L8",
              "notes": "Ledger row."},
    "GG-R3": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_REFLECTIVE_V1.md:L9",
              "notes": "Ledger row."},
    "GG-R5": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_REFLECTIVE_V1.md:L11",
              "notes": "Ledger row, conditional."},
    "GG-R7": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_REFLECTIVE_V1.md:L13",
              "notes": "Ledger row."},
    "GG-S1": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_STRATEGIC_V1.md:L7",
              "notes": "Ledger row."},
    "GG-S5": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/CLAIM_LEDGER_STRATEGIC_V1.md:L11",
              "notes": "Ledger row."},
    "DEVELOPMENTAL_REACHABILITY_SELECTION_THEOREM_V1": {"verdict": "CONFIRMED",
                                                        "evidence": "gmi-grand-unification-v1/FALSIFIABILITY_REGISTRY_V1.md:L123",
                                                        "notes": "Falsifiability-registry row with conditional statement."},
    "NEURAL_NONNEURAL_FAMILY_SELECTION_THEOREM_V1": {"verdict": "CONFIRMED",
                                                     "evidence": "gmi-grand-unification-v1/FALSIFIABILITY_REGISTRY_V1.md:L147",
                                                     "notes": "Family-conditioned frontiers compared in a declared substrate; the universal quantifier covers the declared registered scope (family-conditioned frontier comparison) with analytic + registered-scope evidence."},
    "A-G": {"verdict": "CONFIRMED",
            "evidence": "gmi-grand-unification-v1/FALSIFIABILITY_REGISTRY_V1.md:L114",
            "notes": "Falsifiability-registry row."},
    "GEI-8": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/GENERALIZATION_ECOLOGY_INFERENCE_THEOREM_V1.md (GEI-8)",
              "notes": "Row-level theorem consistent with sampled-statistical scope."},
    "GIR-3": {"verdict": "CONFIRMED",
              "evidence": "gmi-grand-unification-v1/GENERALIZATION_IDENTIFIABILITY_CLAIMS_V1.md:L9",
              "notes": "Conditional information-boundary claim."},
    "AR-7": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/INTRAFAMILY_ARCHITECTURE_REFINEMENT_THEOREM_V1.md:L116",
             "notes": "Sparse conditional expert routing theorem."},
    "PN-5": {"verdict": "CONFIRMED",
             "evidence": "gmi-grand-unification-v1/RECURSIVE_GAP_AUDIT_20260913.md:L88",
             "notes": "Closed-gap synthesis note (two opposing results named)."},
    "SUBSTRATE-LAW": {"verdict": "CONFIRMED",
                      "evidence": "gmi-grand-unification-v1/PHYSICAL_RESOURCE_BRIDGE_THEOREM_V1.md:L3",
                      "notes": "Substrate-law conditions + exact finite witnesses."},
    "GMI_OPERATIONAL_COMPLETENESS_THEOREM_V1": {"verdict": "CONFIRMED",
                                                "evidence": "gmi-grand-unification-v1/UNCOMPUTABILITY_BOUNDARY_THEOREM_V1.md:L44",
                                                "notes": "Finite operational completeness theorem with effectively enumerable register; exhaustive scoped."},
    # --- (a) GREEN mainline: residual context rows are not verdict targets -----
    # (RECEIPT_CERTIFICATE/EXPERIMENT/PROTOCOL/ALGORITHM/FALSIFIER/DEFINITION
    #  rows appear in ADJUDICATIONS as context with verdict UNKNOWN only if
    #  sampled; otherwise excluded by scope.)
    # -------------------------------------------------------------------------
}

TYPED_OVERRIDE_REASONS = frozenset({
    "CENSUS_NEGATED_UNIVERSAL_REGEX_FALSE_POSITIVE",
    "CENSUS_LEDGER_ROW_REGISTERED_AS_CLAIM",
    "CENSUS_HARNESS_GUARD_REGISTERED_AS_CLAIM",
    "CENSUS_CITATION_ROW_REGISTERED_AS_CLAIM",
})
