"""Frozen explicit types for actual context constructors and their mathematical laws."""
SOURCE_PATHS = (
    "research/gmi-1068-partial-context-v15/PartialContextV15.lean",
    "research/gmi-1068-context-specializations-v17/ContextMapsV17.lean",
    "research/gmi-1068-context-specializations-v17/ProductContextsV17.lean",
    "research/gmi-1068-context-specializations-v17/SpecializationsV17.lean",
    "research/gmi-1068-context-specializations-v17/ConfidenceV17.lean",
    "research/gmi-1068-context-specializations-v17/ViabilityV17.lean",
    "research/gmi-1068-context-specializations-v17/CountdownV17.lean",
)
SOURCE_NAMES = tuple(path.rsplit("/", 1)[1] for path in SOURCE_PATHS)
ENTRIES = (
    ("ContextMapsV17.identity", """{W : Type v} (r : PreorderSpec W) : OrderMap r r := @ContextMapsV17.identity W r"""),
    ("ContextMapsV17.compose", """{W : Type v} {Z : Type w} {Y : Type x} {r : PreorderSpec W} {s : PreorderSpec Z} {t : PreorderSpec Y} (g : OrderMap s t) (f : OrderMap r s) : OrderMap r t := @ContextMapsV17.compose W Z Y r s t g f"""),
    ("ContextMapsV17.map_ext", """{W : Type v} {Z : Type w} {r : PreorderSpec W} {s : PreorderSpec Z} (f g : OrderMap r s) (h : f.fn = g.fn) : f=g := @ContextMapsV17.map_ext W Z r s f g h"""),
    ("ContextMapsV17.compose_identity", """{W : Type v} {Z : Type w} {r : PreorderSpec W} {s : PreorderSpec Z} (f : OrderMap r s) : compose (identity s) f = f ∧ compose f (identity r) = f := @ContextMapsV17.compose_identity W Z r s f"""),
    ("ContextMapsV17.compose_assoc", """{A : Type u} {B : Type v} {C : Type w} {D : Type x} {r : PreorderSpec A} {s : PreorderSpec B} {t : PreorderSpec C} {z : PreorderSpec D} (f : OrderMap r s) (g : OrderMap s t) (h : OrderMap t z) : compose h (compose g f) = compose (compose h g) f := @ContextMapsV17.compose_assoc A B C D r s t z f g h"""),
    ("ContextMapsV17.outcomeMap", """{W : Type v} {Z : Type w} (f : W → Z) : Outcome W → Outcome Z := @ContextMapsV17.outcomeMap W Z f"""),
    ("ContextMapsV17.postcompose", """{H : Type u} {W : Type v} {Z : Type w} (k : Context H W) (s : PreorderSpec Z) (f : W → Z) : Context H Z := @ContextMapsV17.postcompose H W Z k s f"""),
    ("ContextMapsV17.post_defined", """{H : Type u} {W : Type v} {Z : Type w} (k : Context H W) (s : PreorderSpec Z) (f : W → Z) : (postcompose k s f).defined = k.defined := @ContextMapsV17.post_defined H W Z k s f"""),
    ("ContextMapsV17.post_value", """{H : Type u} {W : Type v} {Z : Type w} (k : Context H W) (s : PreorderSpec Z) (f : W → Z) (h : {h // k.defined h}) : (postcompose k s f).eval h = f (k.eval h) := @ContextMapsV17.post_value H W Z k s f h"""),
    ("ContextMapsV17.post_identity", """{H : Type u} {W : Type v} (k : Context H W) : postcompose k k.order id = k := @ContextMapsV17.post_identity H W k"""),
    ("ContextMapsV17.post_comp", """{H : Type u} {W : Type v} {Z : Type w} {Y : Type x} (k : Context H W) (s : PreorderSpec Z) (t : PreorderSpec Y) (f : W → Z) (g : Z → Y) : postcompose (postcompose k s f) t g = postcompose k t (fun a => g (f a)) := @ContextMapsV17.post_comp H W Z Y k s t f g"""),
    ("ContextMapsV17.post_observe", """{H : Type u} {W : Type v} {Z : Type w} (P : H → Prop) (k : Context H W) (s : PreorderSpec Z) (f : W → Z) (h : H) : observe P (postcompose k s f) h = outcomeMap f (observe P k h) := @ContextMapsV17.post_observe H W Z P k s f h"""),
    ("ContextMapsV17.post_comparison", """{H : Type u} {W : Type v} {Z : Type w} (P : H → Prop) (k : Context H W) (s : PreorderSpec Z) (f : OrderMap k.order s) (a b : Active P k) (h : (activeOrder P k).le a b) : (activeOrder P (postcompose k s f.fn)).le a b := @ContextMapsV17.post_comparison H W Z P k s f a b h"""),
    ("ContextMapsV17.post_comparison_iff", """{H : Type u} {W : Type v} {Z : Type w} (P : H → Prop) (k : Context H W) (s : PreorderSpec Z) (f : OrderMap k.order s) (reflect : ∀ a b, s.le (f.fn a) (f.fn b) → k.order.le a b) (a b : Active P k) : (activeOrder P (postcompose k s f.fn)).le a b ↔ (activeOrder P k).le a b := @ContextMapsV17.post_comparison_iff H W Z P k s f reflect a b"""),
    ("ContextMapsV17.dualOrder", """{W : Type v} (r : PreorderSpec W) : PreorderSpec W := @ContextMapsV17.dualOrder W r"""),
    ("ContextMapsV17.dual", """{H : Type u} {W : Type v} (k : Context H W) : Context H W := @ContextMapsV17.dual H W k"""),
    ("ContextMapsV17.dual_defined", """{H : Type u} {W : Type v} (k : Context H W) : (dual k).defined = k.defined := @ContextMapsV17.dual_defined H W k"""),
    ("ContextMapsV17.dual_value", """{H : Type u} {W : Type v} (k : Context H W) (h : {h // k.defined h}) : (dual k).eval h = k.eval h := @ContextMapsV17.dual_value H W k h"""),
    ("ContextMapsV17.dual_comparison", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (a b : Active P k) : (activeOrder P (dual k)).le a b ↔ (activeOrder P k).le b a := @ContextMapsV17.dual_comparison H W P k a b"""),
    ("ContextMapsV17.dual_twice", """{H : Type u} {W : Type v} (k : Context H W) : dual (dual k) = k := @ContextMapsV17.dual_twice H W k"""),
    ("ContextMapsV17.dual_observe", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (h : H) : observe P (dual k) h = observe P k h := @ContextMapsV17.dual_observe H W P k h"""),
    ("ContextMapsV17.identity_apply", """{W : Type v} (r : PreorderSpec W) (a : W) : (identity r).fn a = a := @ContextMapsV17.identity_apply W r a"""),
    ("ContextMapsV17.compose_apply", """{W : Type v} {Z : Type w} {Y : Type x} {r : PreorderSpec W} {s : PreorderSpec Z} {t : PreorderSpec Y} (g : OrderMap s t) (f : OrderMap r s) (a : W) : (compose g f).fn a = g.fn (f.fn a) := @ContextMapsV17.compose_apply W Z Y r s t g f a"""),
    ("ContextMapsV17.post_order", """{H : Type u} {W : Type v} {Z : Type w} (k : Context H W) (s : PreorderSpec Z) (f : W → Z) : (postcompose k s f).order = s := @ContextMapsV17.post_order H W Z k s f"""),
    ("ProductContextsV17.productOrder", """{n : Nat} {W : Fin n → Type v} (r : (i : Fin n) → PreorderSpec (W i)) : PreorderSpec ((i : Fin n) → W i) := @ProductContextsV17.productOrder n W r"""),
    ("ProductContextsV17.shared", """{H : Type u} {n : Nat} {W : Fin n → Type v} (E : H → Prop) (r : (i : Fin n) → PreorderSpec (W i)) (f : (i : Fin n) → {h // E h} → W i) : Context H ((i : Fin n) → W i) := @ProductContextsV17.shared H n W E r f"""),
    ("ProductContextsV17.independent", """{H : Type u} {n : Nat} {W : Fin n → Type v} (k : (i : Fin n) → Context H (W i)) : Context H ((i : Fin n) → W i) := @ProductContextsV17.independent H n W k"""),
    ("ProductContextsV17.shared_defined", """{H : Type u} {n : Nat} {W : Fin n → Type v} (E : H → Prop) (r : (i : Fin n) → PreorderSpec (W i)) (f : (i : Fin n) → {h // E h} → W i) : (shared E r f).defined = E := @ProductContextsV17.shared_defined H n W E r f"""),
    ("ProductContextsV17.shared_projection", """{H : Type u} {n : Nat} {W : Fin n → Type v} (E : H → Prop) (r : (i : Fin n) → PreorderSpec (W i)) (f : (i : Fin n) → {h // E h} → W i) (h : {h // E h}) (i : Fin n) : (shared E r f).eval h i = f i h := @ProductContextsV17.shared_projection H n W E r f h i"""),
    ("ProductContextsV17.shared_comparison", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P E : H → Prop) (r : (i : Fin n) → PreorderSpec (W i)) (f : (i : Fin n) → {h // E h} → W i) (a b : Active P (shared E r f)) : (activeOrder P (shared E r f)).le a b ↔ ∀ i, (r i).le (f i ⟨a.val,a.property.2⟩) (f i ⟨b.val,b.property.2⟩) := @ProductContextsV17.shared_comparison H n W P E r f a b"""),
    ("ProductContextsV17.independent_defined", """{H : Type u} {n : Nat} {W : Fin n → Type v} (k : (i : Fin n) → Context H (W i)) (h : H) : (independent k).defined h ↔ ∀ i, (k i).defined h := @ProductContextsV17.independent_defined H n W k h"""),
    ("ProductContextsV17.independent_projection", """{H : Type u} {n : Nat} {W : Fin n → Type v} (k : (i : Fin n) → Context H (W i)) (h : {h // (independent k).defined h}) (i : Fin n) : (independent k).eval h i = (k i).eval ⟨h.val,h.property i⟩ := @ProductContextsV17.independent_projection H n W k h i"""),
    ("ProductContextsV17.independent_comparison", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P : H → Prop) (k : (i : Fin n) → Context H (W i)) (a b : Active P (independent k)) : (activeOrder P (independent k)).le a b ↔ ∀ i, (k i).order.le ((k i).eval ⟨a.val,a.property.2 i⟩) ((k i).eval ⟨b.val,b.property.2 i⟩) := @ProductContextsV17.independent_comparison H n W P k a b"""),
    ("ProductContextsV17.shared_observe", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P E : H → Prop) (r : (i : Fin n) → PreorderSpec (W i)) (f : (i : Fin n) → {h // E h} → W i) (h : H) : observe P (shared E r f) h = (by classical exact if P h then if he : E h then Outcome.value (fun i => f i ⟨h,he⟩) else .undefined else .illegal) := @ProductContextsV17.shared_observe H n W P E r f h"""),
    ("ProductContextsV17.independent_observe", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P : H → Prop) (k : (i : Fin n) → Context H (W i)) (h : H) : observe P (independent k) h = (by classical exact if P h then if he : ∀ i, (k i).defined h then Outcome.value (fun i => (k i).eval ⟨h,he i⟩) else .undefined else .illegal) := @ProductContextsV17.independent_observe H n W P k h"""),
    ("ProductContextsV17.independent_has_value", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P : H → Prop) (k : (i : Fin n) → Context H (W i)) (h : H) : (∃ v, observe P (independent k) h = .value v) ↔ P h ∧ ∀ i, (k i).defined h := @ProductContextsV17.independent_has_value H n W P k h"""),
    ("ProductContextsV17.independent_undefined", """{H : Type u} {n : Nat} {W : Fin n → Type v} (P : H → Prop) (k : (i : Fin n) → Context H (W i)) (h : H) : observe P (independent k) h = .undefined ↔ P h ∧ ¬ ∀ i, (k i).defined h := @ProductContextsV17.independent_undefined H n W P k h"""),
    ("ProductContextsV17.independent_empty_defined", """{H : Type u} {W : Fin 0 → Type v} (k : (i : Fin 0) → Context H (W i)) (h : H) : (independent k).defined h := @ProductContextsV17.independent_empty_defined H W k h"""),
    ("ProductContextsV17.independent_empty_observe", """{H : Type u} {W : Fin 0 → Type v} (P : H → Prop) (k : (i : Fin 0) → Context H (W i)) (h : H) : observe P (independent k) h = (by classical exact if P h then Outcome.value (fun i => Fin.elim0 i) else .illegal) := @ProductContextsV17.independent_empty_observe H W P k h"""),
    ("SpecializationsV17.utility", """{H : Type u} {W : Type v} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → W) : Context H W := @SpecializationsV17.utility H W E r f"""),
    ("SpecializationsV17.utility_defined", """{H : Type u} {W : Type v} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → W) : (utility E r f).defined = E := @SpecializationsV17.utility_defined H W E r f"""),
    ("SpecializationsV17.utility_value", """{H : Type u} {W : Type v} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → W) (h : {h // E h}) : (utility E r f).eval h = f h := @SpecializationsV17.utility_value H W E r f h"""),
    ("SpecializationsV17.utility_comparison", """{H : Type u} {W : Type v} (P E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → W) (a b : Active P (utility E r f)) : (activeOrder P (utility E r f)).le a b ↔ r.le (f ⟨a.val,a.property.2⟩) (f ⟨b.val,b.property.2⟩) := @SpecializationsV17.utility_comparison H W P E r f a b"""),
    ("SpecializationsV17.intUtility", """{H : Type u} (E : H → Prop) (f : {h // E h} → Int) : Context H Int := @SpecializationsV17.intUtility H E f"""),
    ("SpecializationsV17.int_comparison", """(a b : Int) : intOrder.le a b ↔ a ≤ b := @SpecializationsV17.int_comparison a b"""),
    ("SpecializationsV17.bit_order_iff", """(a b : Bool) : boolOrder.le a b ↔ bitScore a ≤ bitScore b := @SpecializationsV17.bit_order_iff a b"""),
    ("SpecializationsV17.bitEmbedding", """: OrderMap boolOrder intOrder := @SpecializationsV17.bitEmbedding"""),
    ("SpecializationsV17.acceptance", """{H : Type u} (E : H → Prop) (A : {h // E h} → Prop) : Context H Bool := @SpecializationsV17.acceptance H E A"""),
    ("SpecializationsV17.acceptance_defined", """{H : Type u} (E : H → Prop) (A : {h // E h} → Prop) : (acceptance E A).defined = E := @SpecializationsV17.acceptance_defined H E A"""),
    ("SpecializationsV17.acceptance_true", """{H : Type u} (E : H → Prop) (A : {h // E h} → Prop) (h : {h // E h}) : (acceptance E A).eval h = true ↔ A h := @SpecializationsV17.acceptance_true H E A h"""),
    ("SpecializationsV17.acceptance_comparison", """{H : Type u} (P E : H → Prop) (A : {h // E h} → Prop) (a b : Active P (acceptance E A)) : (activeOrder P (acceptance E A)).le a b ↔ (A ⟨a.val,a.property.2⟩ → A ⟨b.val,b.property.2⟩) := @SpecializationsV17.acceptance_comparison H P E A a b"""),
    ("SpecializationsV17.vector", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) : Context H (Fin n → W) := @SpecializationsV17.vector H W n E r f"""),
    ("SpecializationsV17.cost", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) : Context H (Fin n → W) := @SpecializationsV17.cost H W n E r f"""),
    ("SpecializationsV17.vector_defined", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) : (vector E r f).defined = E := @SpecializationsV17.vector_defined H W n E r f"""),
    ("SpecializationsV17.vector_value", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) (h : {h // E h}) : (vector E r f).eval h = f h := @SpecializationsV17.vector_value H W n E r f h"""),
    ("SpecializationsV17.pareto_comparison", """{H : Type u} {W : Type v} {n : Nat} (P E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) (a b : Active P (vector E r f)) : (activeOrder P (vector E r f)).le a b ↔ ∀ i, r.le (f ⟨a.val,a.property.2⟩ i) (f ⟨b.val,b.property.2⟩ i) := @SpecializationsV17.pareto_comparison H W n P E r f a b"""),
    ("SpecializationsV17.cost_defined", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) : (cost E r f).defined = E := @SpecializationsV17.cost_defined H W n E r f"""),
    ("SpecializationsV17.cost_value", """{H : Type u} {W : Type v} {n : Nat} (E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) (h : {h // E h}) : (cost E r f).eval h = f h := @SpecializationsV17.cost_value H W n E r f h"""),
    ("SpecializationsV17.cost_comparison", """{H : Type u} {W : Type v} {n : Nat} (P E : H → Prop) (r : PreorderSpec W) (f : {h // E h} → Fin n → W) (a b : Active P (cost E r f)) : (activeOrder P (cost E r f)).le a b ↔ ∀ i, r.le (f ⟨b.val,b.property.2⟩ i) (f ⟨a.val,a.property.2⟩ i) := @SpecializationsV17.cost_comparison H W n P E r f a b"""),
    ("SpecializationsV17.intUtility_binding", """{H : Type u} (E : H → Prop) (f : {h // E h} → Int) : intUtility E f = utility E intOrder f := @SpecializationsV17.intUtility_binding H E f"""),
    ("ConfidenceV17.precision_iff", """{X : Type v} (a b : Region X) : precision.le a b ↔ ∀ x, b.val x → a.val x := @ConfidenceV17.precision_iff X a b"""),
    ("ConfidenceV17.precision_antisymm", """{X : Type v} {a b : Region X} (hab : precision.le a b) (hba : precision.le b a) : a=b := @ConfidenceV17.precision_antisymm X a b hab hba"""),
    ("ConfidenceV17.confidence", """{H : Type u} {X : Type v} (E : H → Prop) (f : {h // E h} → Region X) : Context H (Region X) := @ConfidenceV17.confidence H X E f"""),
    ("ConfidenceV17.confidence_defined", """{H : Type u} {X : Type v} (E : H → Prop) (f : {h // E h} → Region X) : (confidence E f).defined = E := @ConfidenceV17.confidence_defined H X E f"""),
    ("ConfidenceV17.confidence_value", """{H : Type u} {X : Type v} (E : H → Prop) (f : {h // E h} → Region X) (h : {h // E h}) : (confidence E f).eval h = f h := @ConfidenceV17.confidence_value H X E f h"""),
    ("ConfidenceV17.confidence_nonempty", """{H : Type u} {X : Type v} (E : H → Prop) (f : {h // E h} → Region X) (h : {h // E h}) : ∃ x, ((confidence E f).eval h).val x := @ConfidenceV17.confidence_nonempty H X E f h"""),
    ("ConfidenceV17.confidence_comparison", """{H : Type u} {X : Type v} (P E : H → Prop) (f : {h // E h} → Region X) (a b : Active P (confidence E f)) : (activeOrder P (confidence E f)).le a b ↔ ∀ x, (f ⟨b.val,b.property.2⟩).val x → (f ⟨a.val,a.property.2⟩).val x := @ConfidenceV17.confidence_comparison H X P E f a b"""),
    ("ViabilityV17.step_monotone", """{X : Type u} (K : X → Prop) (R : X → X → Prop) {I J : X → Prop} (h : ∀ x, I x → J x) {x : X} (hx : step K R I x) : step K R J x := @ViabilityV17.step_monotone X K R I J h x hx"""),
    ("ViabilityV17.viable_greatest", """{X : Type u} (K : X → Prop) (R : X → X → Prop) (I : X → Prop) (h : Postfixed K R I) {x : X} (hx : I x) : Viable K R x := @ViabilityV17.viable_greatest X K R I h x hx"""),
    ("ViabilityV17.viable_postfixed", """{X : Type u} (K : X → Prop) (R : X → X → Prop) : Postfixed K R (Viable K R) := @ViabilityV17.viable_postfixed X K R"""),
    ("ViabilityV17.viable_safe", """{X : Type u} (K : X → Prop) (R : X → X → Prop) {x : X} (h : Viable K R x) : K x := @ViabilityV17.viable_safe X K R x h"""),
    ("ViabilityV17.viable_fixedpoint", """{X : Type u} (K : X → Prop) (R : X → X → Prop) (x : X) : Viable K R x ↔ step K R (Viable K R) x := @ViabilityV17.viable_fixedpoint X K R x"""),
    ("ViabilityV17.next_related", """{X : Type u} (K : X → Prop) (R : X → X → Prop) (x : {x // Viable K R x}) : R x.val (next K R x).val := @ViabilityV17.next_related X K R x"""),
    ("ViabilityV17.viable_to_trajectory", """{X : Type u} (K : X → Prop) (R : X → X → Prop) {x : X} (h : Viable K R x) : Trajectory K R x := @ViabilityV17.viable_to_trajectory X K R x h"""),
    ("ViabilityV17.trajectory_to_viable", """{X : Type u} (K : X → Prop) (R : X → X → Prop) {x : X} (h : Trajectory K R x) : Viable K R x := @ViabilityV17.trajectory_to_viable X K R x h"""),
    ("ViabilityV17.viable_iff_trajectory", """{X : Type u} (K : X → Prop) (R : X → X → Prop) (x : X) : Viable K R x ↔ Trajectory K R x := @ViabilityV17.viable_iff_trajectory X K R x"""),
    ("ViabilityV17.viabilityContext", """{X : Type u} {H : Type v} (E : H → Prop) (endpoint : {h // E h} → X) (K : X → Prop) (R : X → X → Prop) : Context H Bool := @ViabilityV17.viabilityContext X H E endpoint K R"""),
    ("ViabilityV17.viability_defined", """{X : Type u} {H : Type v} (E : H → Prop) (endpoint : {h // E h} → X) (K : X → Prop) (R : X → X → Prop) : (viabilityContext E endpoint K R).defined = E := @ViabilityV17.viability_defined X H E endpoint K R"""),
    ("ViabilityV17.viability_value", """{X : Type u} {H : Type v} (E : H → Prop) (endpoint : {h // E h} → X) (K : X → Prop) (R : X → X → Prop) (h : {h // E h}) : (viabilityContext E endpoint K R).eval h = true ↔ Viable K R (endpoint h) := @ViabilityV17.viability_value X H E endpoint K R h"""),
    ("ViabilityV17.viability_comparison", """{X : Type u} {H : Type v} (P E : H → Prop) (endpoint : {h // E h} → X) (K : X → Prop) (R : X → X → Prop) (a b : Active P (viabilityContext E endpoint K R)) : (activeOrder P (viabilityContext E endpoint K R)).le a b ↔ (Viable K R (endpoint ⟨a.val,a.property.2⟩) → Viable K R (endpoint ⟨b.val,b.property.2⟩)) := @ViabilityV17.viability_comparison X H P E endpoint K R a b"""),
    ("ViabilityV17.viability_observe", """{X : Type u} {H : Type v} (P E : H → Prop) (endpoint : {h // E h} → X) (K : X → Prop) (R : X → X → Prop) (h : H) : observe P (viabilityContext E endpoint K R) h = (by classical exact if P h then if he : E h then Outcome.value (if Viable K R (endpoint ⟨h,he⟩) then true else false) else .undefined else .illegal) := @ViabilityV17.viability_observe X H P E endpoint K R h"""),
    ("CountdownV17.chain_step", """{n : Nat} {y : State} (h : relation (.chain n) y) : ∃ m, n=m+1 ∧ y=.chain m := @CountdownV17.chain_step n y h"""),
    ("CountdownV17.root_step", """{y : State} (h : relation .root y) : ∃ m, y=.chain m := @CountdownV17.root_step y h"""),
    ("CountdownV17.tail_run", """(g : Nat → State) (h : ∀ n, safe (g n) ∧ relation (g n) (g (n+1))) : Trajectory safe relation (g 1) := @CountdownV17.tail_run g h"""),
    ("CountdownV17.chain_no_trajectory", """(n : Nat) : ¬ Trajectory safe relation (.chain n) := @CountdownV17.chain_no_trajectory n"""),
    ("CountdownV17.root_no_trajectory", """: ¬ Trajectory safe relation .root := @CountdownV17.root_no_trajectory"""),
    ("CountdownV17.every_finite_horizon", """(N : Nat) : FiniteRun N .root := @CountdownV17.every_finite_horizon N"""),
    ("CountdownV17.root_not_viable", """: ¬ Viable safe relation .root := @CountdownV17.root_not_viable"""),
    ("CountdownV17.finite_horizons_do_not_imply_viability", """: (∀ N, FiniteRun N .root) ∧ ¬ Viable safe relation .root := @CountdownV17.finite_horizons_do_not_imply_viability"""),
    ("SpecializationsV17.bit_embedding_apply", """(b : Bool) : bitEmbedding.fn b = bitScore b := bit_embedding_apply b"""),
    ("PartialContextV15.observe_illegal", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (h : H) (hp : ¬P h) : observe P k h=.illegal := observe_illegal P k h hp"""),
    ("PartialContextV15.observe_undefined", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (h : H) (hp : P h) (he : ¬k.defined h) : observe P k h=.undefined := observe_undefined P k h hp he"""),
    ("PartialContextV15.observe_value", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (h : H) (hp : P h) (he : k.defined h) : observe P k h=.value (k.eval ⟨h,he⟩) := observe_value P k h hp he"""),
    ("PartialContextV15.observe_has_value", """{H : Type u} {W : Type v} (P : H → Prop) (k : Context H W) (h : H) : (∃ w, observe P k h=.value w) ↔ P h ∧ k.defined h := observe_has_value P k h"""),
    ("PartialContextV15.value_ne_undefined", """{W : Type v} (w : W) : Outcome.value w ≠ Outcome.undefined := value_ne_undefined w"""),
    ("PartialContextV15.value_ne_illegal", """{W : Type v} (w : W) : Outcome.value w ≠ Outcome.illegal := value_ne_illegal w"""),
    ("PartialContextV15.illegal_ne_undefined", """{W : Type v} : (Outcome.illegal : Outcome W) ≠ Outcome.undefined := illegal_ne_undefined"""),
)


def audit_source():
    header = "".join(f"import {name[:-5]}\n" for name in SOURCE_NAMES)
    header += ("open PartialContextV15 ContextMapsV17 ProductContextsV17\n"
               "open SpecializationsV17 ConfidenceV17 ViabilityV17 CountdownV17\n"
               "universe u v w x\n")
    return header + "\n".join(
        f"noncomputable def registered_{i} {statement}\n#print axioms registered_{i}\n"
        for i, (_, statement) in enumerate(ENTRIES)
    )
