"""Frozen explicit Lean types: no type extraction occurs during replay."""
SOURCE_PATHS = (
    'research/gmi-1068-r0-foundation-repair-v9/RecoverabilityV9.lean',
    'research/gmi-1068-typed-foundation-v11/TypedPathsV11.lean',
    'research/gmi-1068-corrected-targets-v16/GroupLawsV16.lean',
    'research/gmi-1068-arrows-only-v19/PartialUnitsV19.lean',
    'research/gmi-1068-arrows-only-v19/ReconstructedV19.lean',
    'research/gmi-1068-arrows-only-v19/BundledCategoryV19.lean',
    'research/gmi-1068-arrows-only-v19/ArrowRoundtripV19.lean',
    'research/gmi-1068-arrows-only-v19/CategoryRoundtripV19.lean',
    'research/gmi-1068-arrows-only-v19/TableTransportV19.lean',
    'research/gmi-1068-arrows-only-v19/ResponsesV19.lean',
    'research/gmi-1068-arrows-only-v19/RoundtripResponsesV19.lean',
    'research/gmi-1068-arrows-only-v19/CountermodelsV19.lean',
    'research/gmi-1068-arrows-only-v19/InformationControlsV19.lean',
)
SOURCE_NAMES = tuple(path.rsplit("/", 1)[1] for path in SOURCE_PATHS)
ENTRIES = (
    ('RecoverabilityV9.recoverable_iff_fiber_constant', '∀ {M : Sort u_1} {P : Sort u_2} {O : Sort u_3} (p : M → P) (o : M → O), RecoverabilityV9.Recoverable p o ↔ RecoverabilityV9.FiberConstant p o'),
    ('RecoverabilityV9.recovery_unique', '∀ {M : Sort u_1} {P : Sort u_2} {O : Sort u_3} {p : M → P} {o : M → O} (d e : RecoverabilityV9.Image p → O), (∀ (m : M), d (RecoverabilityV9.encoded p m) = o m) → (∀ (m : M), e (RecoverabilityV9.encoded p m) = o m) → d = e'),
    ('PartialUnitsV19.unit_definition', '∀ {A : Type u_1} (m : A → A → Option A) (e : A), PartialUnitsV19.IsUnit m e ↔ m e e = Option.some e ∧ (∀ (x y : A), m e x = Option.some y → y = x) ∧ ∀ (x y : A), m x e = Option.some y → y = x'),
    ('PartialUnitsV19.Algebra.units_equal', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f z : A}, PartialUnitsV19.IsUnit P.mul e → PartialUnitsV19.IsUnit P.mul f → P.mul e f = Option.some z → e = f'),
    ('PartialUnitsV19.Algebra.left_unique', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f x : A}, PartialUnitsV19.IsUnit P.mul e → PartialUnitsV19.IsUnit P.mul f → P.mul e x = Option.some x → P.mul f x = Option.some x → e = f'),
    ('PartialUnitsV19.Algebra.right_unique', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f x : A}, PartialUnitsV19.IsUnit P.mul e → PartialUnitsV19.IsUnit P.mul f → P.mul x e = Option.some x → P.mul x f = Option.some x → e = f'),
    ('PartialUnitsV19.Algebra.left_mul', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x : A), P.mul (P.left x).val x = Option.some x'),
    ('PartialUnitsV19.Algebra.mul_right', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x : A), P.mul x (P.right x).val = Option.some x'),
    ('PartialUnitsV19.Algebra.left_of', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e x : A}, PartialUnitsV19.IsUnit P.mul e → P.mul e x = Option.some x → (P.left x).val = e'),
    ('PartialUnitsV19.Algebra.right_of', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e x : A}, PartialUnitsV19.IsUnit P.mul e → P.mul x e = Option.some x → (P.right x).val = e'),
    ('PartialUnitsV19.Algebra.left_unit', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (e : P.Unit), P.left e.val = e'),
    ('PartialUnitsV19.Algebra.right_unit', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (e : P.Unit), P.right e.val = e'),
    ('PartialUnitsV19.Algebra.left_product', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y z : A}, P.mul x y = Option.some z → P.left z = P.left x'),
    ('PartialUnitsV19.Algebra.right_product', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y z : A}, P.mul x y = Option.some z → P.right z = P.right y'),
    ('PartialUnitsV19.Algebra.matched_of_product', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y z : A}, P.mul x y = Option.some z → P.right x = P.left y'),
    ('PartialUnitsV19.Algebra.product_of_matched', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y : A}, P.right x = P.left y → ∃ z, P.mul x y = Option.some z'),
    ('PartialUnitsV19.Algebra.defined_iff_matched', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x y : A), (∃ z, P.mul x y = Option.some z) ↔ P.right x = P.left y'),
    ('PartialUnitsV19.Algebra.matching_contract', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x y : A), (∃ z, P.mul x y = Option.some z) ↔ P.right x = P.left y'),
    ('ReconstructedV19.compose_binding', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f g : P.Unit} (x : ReconstructedV19.Hom P e f) (y : ReconstructedV19.Hom P f g), P.mul x.val y.val = Option.some (ReconstructedV19.compose P x y).val'),
    ('ReconstructedV19.compose_value', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f g : P.Unit} (x : ReconstructedV19.Hom P e f) (y : ReconstructedV19.Hom P f g) {z : A}, P.mul x.val y.val = Option.some z → (ReconstructedV19.compose P x y).val = z'),
    ('ReconstructedV19.compose_assoc', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f g h : P.Unit} (x : ReconstructedV19.Hom P e f) (y : ReconstructedV19.Hom P f g) (z : ReconstructedV19.Hom P g h), ReconstructedV19.compose P (ReconstructedV19.compose P x y) z = ReconstructedV19.compose P x (ReconstructedV19.compose P y z)'),
    ('ReconstructedV19.identity_left', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f : P.Unit} (x : ReconstructedV19.Hom P e f), ReconstructedV19.compose P (ReconstructedV19.identity P e) x = x'),
    ('ReconstructedV19.identity_right', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f : P.Unit} (x : ReconstructedV19.Hom P e f), ReconstructedV19.compose P x (ReconstructedV19.identity P f) = x'),
    ('ReconstructedV19.category_hom', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (e f : P.Unit), (ReconstructedV19.category P).Hom e f = { x // P.left x = e ∧ P.right x = f }'),
    ('ReconstructedV19.category_identity', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (e : P.Unit), ((ReconstructedV19.category P).id e).val = e.val'),
    ('ReconstructedV19.category_composition', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {e f g : P.Unit} (x : (ReconstructedV19.category P).Hom e f) (y : (ReconstructedV19.category P).Hom f g), P.mul x.val y.val = Option.some ((ReconstructedV19.category P).comp x y).val'),
    ('BundledCategoryV19.aligned', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b c : V} (f : C.Hom a b) (g : C.Hom b c), BundledCategoryV19.mul C ⟨a, ⟨b, f⟩⟩ ⟨b, ⟨c, g⟩⟩ = Option.some ⟨a, ⟨c, C.comp f g⟩⟩'),
    ('BundledCategoryV19.not_aligned', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b c d : V} (f : C.Hom a b) (g : C.Hom c d), b ≠ c → BundledCategoryV19.mul C ⟨a, ⟨b, f⟩⟩ ⟨c, ⟨d, g⟩⟩ = Option.none'),
    ('BundledCategoryV19.defined_iff', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x y : BundledCategoryV19.Arrow C), (∃ z, BundledCategoryV19.mul C x y = Option.some z) ↔ x.snd.fst = y.fst'),
    ('BundledCategoryV19.associative', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x y z : BundledCategoryV19.Arrow C), ((BundledCategoryV19.mul C x y).bind fun p => BundledCategoryV19.mul C p z) = (BundledCategoryV19.mul C y z).bind fun p => BundledCategoryV19.mul C x p'),
    ('BundledCategoryV19.coherent', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x y z p q : BundledCategoryV19.Arrow C), BundledCategoryV19.mul C x y = Option.some p → BundledCategoryV19.mul C y z = Option.some q → ∃ w, BundledCategoryV19.mul C p z = Option.some w'),
    ('BundledCategoryV19.left_identity', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), BundledCategoryV19.mul C (BundledCategoryV19.identity C x.fst) x = Option.some x'),
    ('BundledCategoryV19.right_identity', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), BundledCategoryV19.mul C x (BundledCategoryV19.identity C x.snd.fst) = Option.some x'),
    ('BundledCategoryV19.identity_unit', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), PartialUnitsV19.IsUnit (BundledCategoryV19.mul C) (BundledCategoryV19.identity C a)'),
    ('BundledCategoryV19.algebra_mul', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x y : BundledCategoryV19.Arrow C), (BundledCategoryV19.algebra C).mul x y = BundledCategoryV19.mul C x y'),
    ('BundledCategoryV19.identity_binding', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), BundledCategoryV19.identity C a = ⟨a, ⟨a, C.id a⟩⟩'),
    ('BundledCategoryV19.unit_iff_identity', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), PartialUnitsV19.IsUnit (BundledCategoryV19.mul C) x ↔ ∃ a, x = BundledCategoryV19.identity C a'),
    ('BundledCategoryV19.left_binding', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), ((BundledCategoryV19.algebra C).left x).val = BundledCategoryV19.identity C x.fst'),
    ('BundledCategoryV19.right_binding', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), ((BundledCategoryV19.algebra C).right x).val = BundledCategoryV19.identity C x.snd.fst'),
    ('ArrowRoundtripV19.unpack_pack', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x : A), ArrowRoundtripV19.unpack P (ArrowRoundtripV19.pack P x) = x'),
    ('ArrowRoundtripV19.pack_unpack', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x : ArrowRoundtripV19.Bundled P), ArrowRoundtripV19.pack P (ArrowRoundtripV19.unpack P x) = x'),
    ('ArrowRoundtripV19.unpack_injective', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y : ArrowRoundtripV19.Bundled P}, ArrowRoundtripV19.unpack P x = ArrowRoundtripV19.unpack P y → x = y'),
    ('ArrowRoundtripV19.unpack_product', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) {x y z : ArrowRoundtripV19.Bundled P}, BundledCategoryV19.mul (ReconstructedV19.category P) x y = Option.some z → P.mul (ArrowRoundtripV19.unpack P x) (ArrowRoundtripV19.unpack P y) = Option.some (ArrowRoundtripV19.unpack P z)'),
    ('ArrowRoundtripV19.packed_mul', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x y : A), BundledCategoryV19.mul (ReconstructedV19.category P) (ArrowRoundtripV19.pack P x) (ArrowRoundtripV19.pack P y) = Option.map (ArrowRoundtripV19.pack P) (P.mul x y)'),
    ('ArrowRoundtripV19.unpacked_mul', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (x y : ArrowRoundtripV19.Bundled P), Option.map (ArrowRoundtripV19.unpack P) (BundledCategoryV19.mul (ReconstructedV19.category P) x y) = P.mul (ArrowRoundtripV19.unpack P x) (ArrowRoundtripV19.unpack P y)'),
    ('CategoryRoundtripV19.object_backward_forward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), CategoryRoundtripV19.objectBackward C (CategoryRoundtripV19.objectForward C a) = a'),
    ('CategoryRoundtripV19.object_forward_backward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (e : (CategoryRoundtripV19.P C).Unit), CategoryRoundtripV19.objectForward C (CategoryRoundtripV19.objectBackward C e) = e'),
    ('CategoryRoundtripV19.object_injective', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V}, CategoryRoundtripV19.objectForward C a = CategoryRoundtripV19.objectForward C b → a = b'),
    ('CategoryRoundtripV19.object_surjective', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (e : (CategoryRoundtripV19.P C).Unit), ∃ a, CategoryRoundtripV19.objectForward C a = e'),
    ('CategoryRoundtripV19.object_value', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), (CategoryRoundtripV19.objectForward C a).val = BundledCategoryV19.identity C a'),
    ('CategoryRoundtripV19.hom_forward_value', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} (f : C.Hom a b), (CategoryRoundtripV19.homForward C f).val = ⟨a, ⟨b, f⟩⟩'),
    ('CategoryRoundtripV19.hom_source', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} (f : (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b)), f.val.fst = a'),
    ('CategoryRoundtripV19.hom_target', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} (f : (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b)), f.val.snd.fst = b'),
    ('CategoryRoundtripV19.hom_backward_forward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} (f : C.Hom a b), CategoryRoundtripV19.homBackward C (CategoryRoundtripV19.homForward C f) = f'),
    ('CategoryRoundtripV19.hom_forward_backward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} (f : (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b)), CategoryRoundtripV19.homForward C (CategoryRoundtripV19.homBackward C f) = f'),
    ('CategoryRoundtripV19.hom_forward_injective', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b : V} {f g : C.Hom a b}, CategoryRoundtripV19.homForward C f = CategoryRoundtripV19.homForward C g → f = g'),
    ('CategoryRoundtripV19.forward_identity', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), CategoryRoundtripV19.homForward C (C.id a) = (CategoryRoundtripV19.Rebuilt C).id (CategoryRoundtripV19.objectForward C a)'),
    ('CategoryRoundtripV19.forward_comp', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b c : V} (f : C.Hom a b) (g : C.Hom b c), CategoryRoundtripV19.homForward C (C.comp f g) = (CategoryRoundtripV19.Rebuilt C).comp (CategoryRoundtripV19.homForward C f) (CategoryRoundtripV19.homForward C g)'),
    ('CategoryRoundtripV19.backward_identity', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (a : V), CategoryRoundtripV19.homBackward C ((CategoryRoundtripV19.Rebuilt C).id (CategoryRoundtripV19.objectForward C a)) = C.id a'),
    ('CategoryRoundtripV19.backward_comp', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) {a b c : V} (f : (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b)) (g : (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C b) (CategoryRoundtripV19.objectForward C c)), CategoryRoundtripV19.homBackward C ((CategoryRoundtripV19.Rebuilt C).comp f g) = C.comp (CategoryRoundtripV19.homBackward C f) (CategoryRoundtripV19.homBackward C g)'),
    ('TableTransportV19.TableIso.forward_injective', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) {x y : A}, I.forward x = I.forward y → x = y'),
    ('TableTransportV19.TableIso.backward_mul', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) (x y : B), m (I.backward x) (I.backward y) = Option.map I.backward (n x y)'),
    ('TableTransportV19.TableIso.reflect_product', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) {x y z : A}, n (I.forward x) (I.forward y) = Option.some (I.forward z) → m x y = Option.some z'),
    ('TableTransportV19.TableIso.unit_forward', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) {e : A}, PartialUnitsV19.IsUnit m e → PartialUnitsV19.IsUnit n (I.forward e)'),
    ('TableTransportV19.TableIso.unit_iff', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) (e : A), PartialUnitsV19.IsUnit n (I.forward e) ↔ PartialUnitsV19.IsUnit m e'),
    ('ResponsesV19.run_nil', '∀ {A : Type u_1} (m : A → A → Option A) (x : A), ResponsesV19.run m x [] = Option.some x'),
    ('ResponsesV19.run_cons', '∀ {A : Type u_1} (m : A → A → Option A) (x y : A) (ys : List A), ResponsesV19.run m x (y :: ys) = (m x y).bind fun z => ResponsesV19.run m z ys'),
    ('ResponsesV19.query_map_word', '∀ {A : Type u_1} {B : Type u_2} (f : A → B) (x : A) (xs : List A), ResponsesV19.Query.map f (ResponsesV19.Query.word x xs) = ResponsesV19.Query.word (f x) (List.map f xs)'),
    ('ResponsesV19.query_map_empty', '∀ {A : Type u_1} {B : Type u_2} (f : A → B) (x : A), ResponsesV19.Query.map f (ResponsesV19.Query.empty x) = ResponsesV19.Query.empty (f x)'),
    ('ResponsesV19.word_binding', '∀ {A : Type u_1} (m : A → A → Option A) (x : A) (xs : List A), ResponsesV19.response m (ResponsesV19.Query.word x xs) = ResponsesV19.run m x xs'),
    ('ResponsesV19.empty_binding', '∀ {A : Type u_1} (m : A → A → Option A) (e : A), ResponsesV19.response m (ResponsesV19.Query.empty e) = Option.some e ↔ PartialUnitsV19.IsUnit m e'),
    ('ResponsesV19.empty_illegal', '∀ {A : Type u_1} (m : A → A → Option A) (e : A), ResponsesV19.response m (ResponsesV19.Query.empty e) = Option.none ↔ ¬PartialUnitsV19.IsUnit m e'),
    ('ResponsesV19.singleton_binding', '∀ {A : Type u_1} (m : A → A → Option A) (x : A), ResponsesV19.response m (ResponsesV19.Query.word x []) = Option.some x'),
    ('ResponsesV19.pair_binding', '∀ {A : Type u_1} (m : A → A → Option A) (x y : A), ResponsesV19.response m (ResponsesV19.Query.word x [y]) = m x y'),
    ('ResponsesV19.run_transport', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) (x : A) (xs : List A), ResponsesV19.run n (I.forward x) (List.map I.forward xs) = Option.map I.forward (ResponsesV19.run m x xs)'),
    ('ResponsesV19.response_transport', '∀ {A : Type u_1} {B : Type u_2} {m : A → A → Option A} {n : B → B → Option B} (I : TableTransportV19.TableIso m n) (q : ResponsesV19.Query A), ResponsesV19.response n (ResponsesV19.Query.map I.forward q) = Option.map I.forward (ResponsesV19.response m q)'),
    ('ResponsesV19.responses_eq_iff_tables_eq', '∀ {A : Type u_1} (m n : A → A → Option A), ResponsesV19.response m = ResponsesV19.response n ↔ m = n'),
    ('ResponsesV19.response_recovery_iff_table_recovery', '∀ {A : Type u_1} {M : Type u_2} {Z : Type u_3} (table : M → A → A → Option A) (code : M → Z), (RecoverabilityV9.Recoverable code fun m => ResponsesV19.response (table m)) ↔ RecoverabilityV9.Recoverable code table'),
    ('RoundtripResponsesV19.pack_response', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (q : ResponsesV19.Query A), ResponsesV19.response (BundledCategoryV19.mul (ReconstructedV19.category P)) (ResponsesV19.Query.map (ArrowRoundtripV19.pack P) q) = Option.map (ArrowRoundtripV19.pack P) (ResponsesV19.response P.mul q)'),
    ('RoundtripResponsesV19.unpack_response', '∀ {A : Type u_1} (P : PartialUnitsV19.Algebra A) (q : ResponsesV19.Query (ArrowRoundtripV19.Bundled P)), ResponsesV19.response P.mul (ResponsesV19.Query.map (ArrowRoundtripV19.unpack P) q) = Option.map (ArrowRoundtripV19.unpack P) (ResponsesV19.response (BundledCategoryV19.mul (ReconstructedV19.category P)) q)'),
    ('RoundtripResponsesV19.categoryForward_eq_pack', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), RoundtripResponsesV19.categoryForward C x = ArrowRoundtripV19.pack (BundledCategoryV19.algebra C) x'),
    ('RoundtripResponsesV19.category_backward_forward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow C), RoundtripResponsesV19.categoryBackward C (RoundtripResponsesV19.categoryForward C x) = x'),
    ('RoundtripResponsesV19.category_forward_backward', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (x : BundledCategoryV19.Arrow (CategoryRoundtripV19.Rebuilt C)), RoundtripResponsesV19.categoryForward C (RoundtripResponsesV19.categoryBackward C x) = x'),
    ('RoundtripResponsesV19.category_forward_response', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (q : ResponsesV19.Query (BundledCategoryV19.Arrow C)), ResponsesV19.response (BundledCategoryV19.mul (CategoryRoundtripV19.Rebuilt C)) (ResponsesV19.Query.map (RoundtripResponsesV19.categoryForward C) q) = Option.map (RoundtripResponsesV19.categoryForward C) (ResponsesV19.response (BundledCategoryV19.mul C) q)'),
    ('RoundtripResponsesV19.category_backward_response', '∀ {V : Type u_1} (C : TypedPathsV11.Category V) (q : ResponsesV19.Query (BundledCategoryV19.Arrow (CategoryRoundtripV19.Rebuilt C))), ResponsesV19.response (BundledCategoryV19.mul C) (ResponsesV19.Query.map (RoundtripResponsesV19.categoryBackward C) q) = Option.map (RoundtripResponsesV19.categoryBackward C) (ResponsesV19.response (BundledCategoryV19.mul (CategoryRoundtripV19.Rebuilt C)) q)'),
    ('CountermodelsV19.exists_empty_fin', '∀ (p : Fin 0 → Prop), (∃ x, p x) ↔ False'),
    ('CountermodelsV19.coherence_isolated', 'CountermodelsV19.StrongAssoc CountermodelsV19.incoherent ∧ CountermodelsV19.Local CountermodelsV19.incoherent ∧ ¬CountermodelsV19.Coherent CountermodelsV19.incoherent'),
    ('CountermodelsV19.nonassoc_units', '(∀ (x : Fin 3), CountermodelsV19.nonassoc 0 x = x) ∧ ∀ (x : Fin 3), CountermodelsV19.nonassoc x 0 = x'),
    ('CountermodelsV19.associativity_isolated', '(CountermodelsV19.Local fun x y => Option.some (CountermodelsV19.nonassoc x y)) ∧ (CountermodelsV19.Coherent fun x y => Option.some (CountermodelsV19.nonassoc x y)) ∧ ¬CountermodelsV19.StrongAssoc fun x y => Option.some (CountermodelsV19.nonassoc x y)'),
    ('CountermodelsV19.nonassoc_witness', 'CountermodelsV19.nonassoc (CountermodelsV19.nonassoc 1 1) 2 = 2 ∧ CountermodelsV19.nonassoc 1 (CountermodelsV19.nonassoc 1 2) = 1'),
    ('CountermodelsV19.two_point_unital_associative', '∀ {A : Sort u_1} (m : A → A → A) (e a : A), (∀ (x : A), x = e ∨ x = a) → (∀ (x : A), m e x = x) → (∀ (x : A), m x e = x) → ∀ (x y z : A), m (m x y) z = m x (m y z)'),
    ('CountermodelsV19.fin_small_unital_associative', '∀ {n : Nat}, n ≤ 2 → ∀ (m : Fin n → Fin n → Fin n) (e : Fin n), (∀ (x : Fin n), m e x = x) → (∀ (x : Fin n), m x e = x) → ∀ (x y z : Fin n), m (m x y) z = m x (m y z)'),
    ('CountermodelsV19.nonassoc_minimum_size', '∀ {n : Nat} (m : Fin n → Fin n → Fin n) (e : Fin n), (∀ (x : Fin n), m e x = x) → (∀ (x : Fin n), m x e = x) → (∃ x y z, m (m x y) z ≠ m x (m y z)) → 3 ≤ n'),
    ('CountermodelsV19.projection_controls', '(∀ (x y z : Bool), CountermodelsV19.leftProjection (CountermodelsV19.leftProjection x y) z = CountermodelsV19.leftProjection x (CountermodelsV19.leftProjection y z)) ∧ (∀ (x : Bool), CountermodelsV19.leftProjection x Bool.false = x) ∧ (¬∀ (x : Bool), CountermodelsV19.leftProjection Bool.false x = x) ∧ (∀ (x y z : Bool), CountermodelsV19.rightProjection (CountermodelsV19.rightProjection x y) z = CountermodelsV19.rightProjection x (CountermodelsV19.rightProjection y z)) ∧ (∀ (x : Bool), CountermodelsV19.rightProjection Bool.false x = x) ∧ ¬∀ (x : Bool), CountermodelsV19.rightProjection x Bool.false = x'),
    ('CountermodelsV19.projections_have_no_opposite_unit', '(∀ (e : Bool), ¬∀ (x : Bool), CountermodelsV19.leftProjection e x = x) ∧ ∀ (e : Bool), ¬∀ (x : Bool), CountermodelsV19.rightProjection x e = x'),
    ('CountermodelsV19.strong_definedness_isolated', 'CountermodelsV19.WeakAssoc CountermodelsV19.weakOnly ∧ CountermodelsV19.Local CountermodelsV19.weakOnly ∧ CountermodelsV19.Coherent CountermodelsV19.weakOnly ∧ ¬CountermodelsV19.StrongAssoc CountermodelsV19.weakOnly'),
    ('CountermodelsV19.weak_only_witness', '((CountermodelsV19.weakOnly 0 1).bind fun x => CountermodelsV19.weakOnly x 2) = Option.none ∧ ((CountermodelsV19.weakOnly 1 2).bind fun x => CountermodelsV19.weakOnly 0 x) = Option.some 2'),
    ('InformationControlsV19.default_collision', '(∀ (x y : Bool), (InformationControlsV19.discrete x y).getD Bool.true = (InformationControlsV19.join x y).getD Bool.true) ∧ InformationControlsV19.discrete Bool.false Bool.true = Option.none ∧ InformationControlsV19.join Bool.false Bool.true = Option.some Bool.true'),
    ('InformationControlsV19.distinct_unit_information', '(∀ (x : Bool), PartialUnitsV19.IsUnit InformationControlsV19.discrete x) ∧ ∀ (x : Bool), PartialUnitsV19.IsUnit InformationControlsV19.join x ↔ x = Bool.false'),
    ('InformationControlsV19.multiplicative_not_unital', '(∀ (x y : Unit), InformationControlsV19.join (InformationControlsV19.constantMap x) (InformationControlsV19.constantMap y) = Option.some (InformationControlsV19.constantMap (InformationControlsV19.sourceMul x y))) ∧ ¬PartialUnitsV19.IsUnit InformationControlsV19.join (InformationControlsV19.constantMap ())'),
    ('InformationControlsV19.no_empty_units', '¬∃ e, PartialUnitsV19.IsUnit InformationControlsV19.emptyAlgebra.mul e'),
    ('InformationControlsV19.singleton_unit', 'PartialUnitsV19.IsUnit InformationControlsV19.singletonAlgebra.mul ()'),
    ('InformationControlsV19.lifted_unit', '∀ (L : GroupLawsV16.Law), PartialUnitsV19.IsUnit (InformationControlsV19.lifted L) GroupLawsV16.Label.zero'),
    ('InformationControlsV19.lifted_unit_iff', '∀ (L : GroupLawsV16.Law) (x : GroupLawsV16.Label), PartialUnitsV19.IsUnit (InformationControlsV19.lifted L) x ↔ x = GroupLawsV16.Label.zero'),
    ('InformationControlsV19.c4_v4_same_admission_units', '(∀ (x y : GroupLawsV16.Label), (∃ z, InformationControlsV19.lifted GroupLawsV16.c4 x y = Option.some z) ∧ ∃ z, InformationControlsV19.lifted GroupLawsV16.v4 x y = Option.some z) ∧ ∀ (x : GroupLawsV16.Label), PartialUnitsV19.IsUnit (InformationControlsV19.lifted GroupLawsV16.c4) x ↔ PartialUnitsV19.IsUnit (InformationControlsV19.lifted GroupLawsV16.v4) x'),
    ('InformationControlsV19.c4_v4_different_products', 'InformationControlsV19.lifted GroupLawsV16.c4 GroupLawsV16.Label.one GroupLawsV16.Label.one = Option.some GroupLawsV16.Label.two ∧ InformationControlsV19.lifted GroupLawsV16.v4 GroupLawsV16.Label.one GroupLawsV16.Label.one = Option.some GroupLawsV16.Label.zero'),
    ('PartialUnitsV19.Algebra', 'Type u_1 → Type u_1'),
    ('ReconstructedV19.category', '{A : Type u_1} → (P : PartialUnitsV19.Algebra A) → TypedPathsV11.Category P.Unit'),
    ('BundledCategoryV19.mul', '{V : Type u_1} → (C : TypedPathsV11.Category V) → BundledCategoryV19.Arrow C → BundledCategoryV19.Arrow C → Option (BundledCategoryV19.Arrow C)'),
    ('BundledCategoryV19.algebra', '{V : Type u_1} → (C : TypedPathsV11.Category V) → PartialUnitsV19.Algebra (BundledCategoryV19.Arrow C)'),
    ('CategoryRoundtripV19.objectForward', '{V : Type u_1} → (C : TypedPathsV11.Category V) → V → (CategoryRoundtripV19.P C).Unit'),
    ('CategoryRoundtripV19.homForward', '{V : Type u_1} → (C : TypedPathsV11.Category V) → {a b : V} → C.Hom a b → (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b)'),
    ('CategoryRoundtripV19.homBackward', '{V : Type u_1} → (C : TypedPathsV11.Category V) → {a b : V} → (CategoryRoundtripV19.Rebuilt C).Hom (CategoryRoundtripV19.objectForward C a) (CategoryRoundtripV19.objectForward C b) → C.Hom a b'),
    ('ResponsesV19.Query', 'Type u_1 → Type u_1'),
    ('ResponsesV19.run', '{A : Type u_1} → (A → A → Option A) → A → List A → Option A'),
    ('ResponsesV19.response', '{A : Type u_1} → (A → A → Option A) → ResponsesV19.Query A → Option A'),
    ('RoundtripResponsesV19.arrowIso', '{A : Type u_1} → (P : PartialUnitsV19.Algebra A) → TableTransportV19.TableIso P.mul (BundledCategoryV19.mul (ReconstructedV19.category P))'),
    ('RoundtripResponsesV19.categoryIso', '{V : Type u_1} → (C : TypedPathsV11.Category V) → TableTransportV19.TableIso (BundledCategoryV19.mul C) (BundledCategoryV19.mul (CategoryRoundtripV19.Rebuilt C))'),
    ('InformationControlsV19.emptyAlgebra', 'PartialUnitsV19.Algebra Empty'),
    ('InformationControlsV19.singletonAlgebra', 'PartialUnitsV19.Algebra Unit'),
    ('InformationControlsV19.discreteAlgebra', 'PartialUnitsV19.Algebra Bool'),
    ('InformationControlsV19.joinAlgebra', 'PartialUnitsV19.Algebra Bool'),
    ('InformationControlsV19.liftedAlgebra', 'GroupLawsV16.Law → PartialUnitsV19.Algebra GroupLawsV16.Label'),
)

def audit_source():
    imports = "\n".join("import " + name[:-5] for name in SOURCE_NAMES)
    universe = "universe u v w x u_1 u_2 u_3 u_4 u_5 u_6"
    statements = []
    for i, (target, signature) in enumerate(ENTRIES):
        statements.append(f"noncomputable def registered_{i} : {signature} := @{target}")
        statements.append(f"#print axioms registered_{i}")
    return imports + "\n" + universe + "\n" + "\n".join(statements) + "\n"
