"""The four DEV-D8 arms, plus one declared diagnostic.

Every arm shares one serve loop.  What separates them is the store they begin D1
with and what they are permitted to induce, which is the only way a comparison
between them can be about development rather than about implementation.

The exception mechanism is what makes D1 a stage rather than a longer D0.  A
held rule does not license an answer: it licenses a CHECK.  An arm that applies
a rule to an exception is wrong, so every admissible arm pays ``VERIFY_COST``
before applying, and the verification it spends on rules that turn out not to
apply is recorded as ``negative_transfer_work``.  That coordinate exists so that
the cost of carrying structure is charged to the arm carrying it, rather than
appearing as a free option.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Iterable, Sequence

from dev1 import (COMPOSE_COST, COMPOSITE_BITS, D1World, Pair, VERIFY_COST)
from retain import (APPLY_COST, DERIVE_COST, FACT_BITS, INDUCE_COST, K_INDUCE,
                    LOOKUP_COST, RULE_BITS)

__all__ = ["Store", "Phase", "run_d0", "run_d1", "ARMS", "ARM_ROLES", "run_arm"]


@dataclass
class Store:
    """What crosses the stage boundary, or does not."""

    facts: list[int] = field(default_factory=list)
    rules: set[int] = field(default_factory=set)
    composites: set[tuple[int, int]] = field(default_factory=set)
    seen: dict[int, set[int]] = field(default_factory=dict)
    pair_seen: dict[tuple[int, int], int] = field(default_factory=dict)
    #: answers derived and found NOT to be generated by their rule
    known_exceptions: set[int] = field(default_factory=set)

    def bits(self) -> int:
        return (len(self.facts) * FACT_BITS + len(self.rules) * RULE_BITS
                + len(self.composites) * COMPOSITE_BITS)

    def digest_material(self) -> str:
        return "|".join((
            ",".join(map(str, sorted(self.facts))),
            ",".join(map(str, sorted(self.rules))),
            ",".join(f"{a}-{b}" for a, b in sorted(self.composites)),
            ",".join(map(str, sorted(self.known_exceptions))),
        ))

    def copy(self) -> "Store":
        return Store(list(self.facts), set(self.rules), set(self.composites),
                     {k: set(v) for k, v in self.seen.items()}, dict(self.pair_seen),
                     set(self.known_exceptions))


@dataclass
class Phase:
    """Work coordinates for one stage.  Never summed without an explicit sigma."""

    derive_work: int = 0
    apply_work: int = 0
    lookup_work: int = 0
    induce_work: int = 0
    verify_work: int = 0
    compose_work: int = 0
    bit_steps: int = 0
    derivations: int = 0
    inductions: int = 0
    applications: int = 0
    verifications: int = 0
    #: verifications that ended in a refusal: the held rule did not apply
    harmful_transfer_refusals: int = 0
    #: work spent purely because a rule was held and turned out not to apply
    negative_transfer_work: int = 0
    reused_object_ids: set[str] = field(default_factory=set)
    reuse_witnesses: int = 0
    served: int = 0
    correct: int = 0
    peak_bits: int = 0

    def total_work(self, sigma: float) -> float:
        return (self.derive_work + self.apply_work + self.lookup_work + self.induce_work
                + self.verify_work + self.compose_work + sigma * self.bit_steps)

    def correctness(self) -> float:
        return self.correct / self.served if self.served else 0.0

    def as_dict(self, sigmas: Sequence[float]) -> dict:
        return {
            "derive_work": self.derive_work, "apply_work": self.apply_work,
            "lookup_work": self.lookup_work, "induce_work": self.induce_work,
            "verify_work": self.verify_work, "compose_work": self.compose_work,
            "bit_steps": self.bit_steps, "derivations": self.derivations,
            "inductions": self.inductions, "applications": self.applications,
            "verifications": self.verifications,
            "harmful_transfer_refusals": self.harmful_transfer_refusals,
            "negative_transfer_work": self.negative_transfer_work,
            "reuse_witnesses": self.reuse_witnesses,
            "reused_object_count": len(self.reused_object_ids),
            "served": self.served, "correct": self.correct,
            "correctness": self.correctness(), "peak_bits": self.peak_bits,
            "total_work_by_sigma": {str(s): self.total_work(s) for s in sigmas},
        }


def _evict_for(store: Store, world: D1World, room: int, budget: int,
               phase: "Phase", freq: dict[int, int]) -> None:
    """Make ``room`` bits, giving up the least-demanded objects first.

    The first smoke run of this experiment made the case for rule eviction on its
    own: D0 ended with a FULL store of eight rules, and D1's demand distribution
    is not D0's -- pairs are drawn from two DIFFERENT rules, which flattens the
    skew D0 was fitted to.  Without rule eviction the carried competence cannot be
    displaced by anything D1 actually needs, and CONTINUED_OCM loses to RESET_OCM
    purely because it arrives with its budget already spent.  That is a real
    failure mode of carrying state and it is worth naming, but it is a failure of
    THIS ARM rather than of the hypothesis, so the arm gets an eviction policy and
    both lineage arms get the same one.

    Rules are evicted by uses-since-arrival, and a rule that has never been used
    is evicted before any fact.  Carried structure therefore has to earn its slot
    against the current stage, which is the whole point of a bounded store.
    """
    def rule_uses(r: int) -> int:
        return sum(freq.get(g, 0) for g in world.members[r])

    while store.bits() + room > budget:
        cold_rules = [r for r in store.rules if rule_uses(r) == 0]
        if cold_rules:
            store.rules.discard(min(cold_rules))
            continue
        if store.facts:
            store.facts.remove(min(store.facts, key=lambda g: (freq.get(g, 0), g)))
            continue
        if store.rules:
            store.rules.discard(min(store.rules, key=lambda r: (rule_uses(r), r)))
            continue
        if store.composites:
            store.composites.discard(min(store.composites,
                                         key=lambda k: (store.pair_seen.get(k, 0), k)))
            continue
        return


def _on_derive(store: Store, world: D1World, answer: int, budget: int,
               phase: Phase, freq: dict[int, int], induce_base: bool) -> None:
    """Record what a derivation revealed, and induce if demand has proved itself."""
    r = world.rule_of[answer]
    if not world.generated_by_rule(answer):
        store.known_exceptions.add(answer)
    else:
        store.seen.setdefault(r, set()).add(answer)
    if induce_base and r not in store.rules and len(store.seen.get(r, ())) >= K_INDUCE:
        _evict_for(store, world, RULE_BITS, budget, phase, freq)
        if store.bits() + RULE_BITS <= budget:
            phase.induce_work += INDUCE_COST
            phase.inductions += 1
            store.rules.add(r)
            # only answers the rule actually generates become redundant; a stored
            # exception is not covered by the rule and must survive its induction
            for g in [g for g in store.facts
                      if world.rule_of[g] == r and world.generated_by_rule(g)]:
                store.facts.remove(g)
            return
    _evict_for(store, world, FACT_BITS, budget, phase, freq)
    if store.bits() + FACT_BITS <= budget:
        store.facts.append(answer)


def run_d0(world: D1World, stream: Sequence[int], budget: int,
           induce_base: bool = True) -> tuple[Store, Phase]:
    """E10's economy, unchanged: single demands, correct by construction."""
    store, phase = Store(), Phase()
    freq: dict[int, int] = {}
    for answer in stream:
        freq[answer] = freq.get(answer, 0) + 1
        phase.served += 1
        phase.correct += 1
        r = world.rule_of[answer]
        if r in store.rules and world.generated_by_rule(answer):
            phase.apply_work += APPLY_COST
            phase.applications += 1
        elif answer in store.facts:
            phase.lookup_work += LOOKUP_COST
        else:
            if r in store.rules:
                # the rule is held and does not generate this answer; D0 charges
                # the check too, so the exception cost is not invented at D1
                phase.verify_work += VERIFY_COST
                phase.verifications += 1
                phase.harmful_transfer_refusals += 1
                phase.negative_transfer_work += VERIFY_COST
            phase.derive_work += DERIVE_COST
            phase.derivations += 1
            _on_derive(store, world, answer, budget, phase, freq, induce_base)
        b = store.bits()
        phase.bit_steps += b
        phase.peak_bits = max(phase.peak_bits, b)
    return store, phase


def _serve_member(world: D1World, store: Store, answer: int, budget: int,
                  phase: Phase, freq: dict[int, int], induce_base: bool) -> bool:
    """Answer one member of a pair.  Returns whether the answer given was correct."""
    r = world.rule_of[answer]
    if r in store.rules:
        phase.verify_work += VERIFY_COST
        phase.verifications += 1
        if world.generated_by_rule(answer):
            phase.apply_work += APPLY_COST
            phase.applications += 1
            phase.reused_object_ids.add(f"rule:{r}")
            phase.reuse_witnesses += 1
            return True
        phase.harmful_transfer_refusals += 1
        phase.negative_transfer_work += VERIFY_COST
        phase.derive_work += DERIVE_COST
        phase.derivations += 1
        _on_derive(store, world, answer, budget, phase, freq, induce_base)
        return True
    if answer in store.facts:
        phase.lookup_work += LOOKUP_COST
        phase.reused_object_ids.add(f"fact:{answer}")
        phase.reuse_witnesses += 1
        return True
    phase.derive_work += DERIVE_COST
    phase.derivations += 1
    _on_derive(store, world, answer, budget, phase, freq, induce_base)
    return True


def run_d1(world: D1World, stream: Sequence[Pair], budget: int, store: Store,
           induce_base: bool = True, induce_composites: bool = False,
           verify_before_applying: bool = True) -> tuple[Store, Phase]:
    phase = Phase()
    freq: dict[int, int] = {}
    for pair in stream:
        phase.served += 1
        key = tuple(sorted((world.rule_of[pair.left], world.rule_of[pair.right])))
        freq[pair.left] = freq.get(pair.left, 0) + 1
        freq[pair.right] = freq.get(pair.right, 0) + 1
        ok = True
        if induce_composites and key in store.composites:
            # a composite still licenses only a check, never an answer
            for answer in (pair.left, pair.right):
                phase.verify_work += VERIFY_COST
                phase.verifications += 1
                if world.generated_by_rule(answer):
                    phase.apply_work += APPLY_COST
                    phase.applications += 1
                    phase.reused_object_ids.add(f"composite:{key[0]}-{key[1]}")
                    phase.reuse_witnesses += 1
                else:
                    phase.harmful_transfer_refusals += 1
                    phase.negative_transfer_work += VERIFY_COST
                    phase.derive_work += DERIVE_COST
                    phase.derivations += 1
                    _on_derive(world=world, store=store, answer=answer, budget=budget,
                               phase=phase, freq=freq, induce_base=induce_base)
        elif not verify_before_applying:
            for answer in (pair.left, pair.right):
                r = world.rule_of[answer]
                if r in store.rules:
                    phase.apply_work += APPLY_COST
                    phase.applications += 1
                    if not world.generated_by_rule(answer):
                        ok = False
                elif answer in store.facts:
                    phase.lookup_work += LOOKUP_COST
                else:
                    phase.derive_work += DERIVE_COST
                    phase.derivations += 1
                    _on_derive(store, world, answer, budget, phase, freq, induce_base)
        else:
            for answer in (pair.left, pair.right):
                ok = _serve_member(world, store, answer, budget, phase, freq,
                                   induce_base) and ok
        phase.compose_work += COMPOSE_COST
        phase.correct += 1 if ok else 0
        if induce_composites:
            store.pair_seen[key] = store.pair_seen.get(key, 0) + 1
            if key not in store.composites and store.pair_seen[key] >= K_INDUCE:
                _evict_for(store, world, COMPOSITE_BITS, budget, phase, freq)
                if store.bits() + COMPOSITE_BITS <= budget:
                    phase.induce_work += INDUCE_COST
                    phase.inductions += 1
                    store.composites.add(key)
        b = store.bits()
        phase.bit_steps += b
        phase.peak_bits = max(phase.peak_bits, b)
    return store, phase


def strong_adaptive_parent(world: D1World, d0: Sequence[int], d1: Sequence[Pair],
                           budget: int) -> tuple[Store, Phase, Phase]:
    """Sees D0, D1, and the entire future; keeps what a clairvoyant would keep.

    It also knows which answers are exceptions, so it never pays to verify and
    never misapplies.  This is deliberately more information than the lineage has:
    the parent is a bound on the claim, not a competitor for it.
    """
    demand: dict[int, int] = {}
    rule_demand: dict[int, int] = {}
    for answer in d0:
        demand[answer] = demand.get(answer, 0) + 1
    for pair in d1:
        for answer in (pair.left, pair.right):
            demand[answer] = demand.get(answer, 0) + 1
    for answer, count in demand.items():
        if world.generated_by_rule(answer):
            r = world.rule_of[answer]
            rule_demand[r] = rule_demand.get(r, 0) + count

    slots = RULE_BITS // FACT_BITS
    chosen: set[int] = set()
    remaining = budget
    for r in sorted(rule_demand, key=lambda r: (-rule_demand[r], r)):
        if remaining < RULE_BITS:
            continue
        rule_saving = rule_demand[r] * (DERIVE_COST - APPLY_COST)
        best = sorted((demand[f] for f in world.members[r] if f in demand), reverse=True)[:slots]
        if rule_saving > sum(c * (DERIVE_COST - LOOKUP_COST) for c in best):
            chosen.add(r)
            remaining -= RULE_BITS

    capacity = remaining // FACT_BITS
    store = Store(rules=set(chosen))

    def serve(answer: int, phase: Phase, held: list[int], future: dict[int, list[int]],
              t: int, horizon: int) -> None:
        r = world.rule_of[answer]
        if r in chosen and world.generated_by_rule(answer):
            phase.apply_work += APPLY_COST
            phase.applications += 1
            return
        if answer in held:
            phase.lookup_work += LOOKUP_COST
            return
        phase.derive_work += DERIVE_COST
        phase.derivations += 1
        if capacity:
            if len(held) >= capacity:
                held.remove(max(held, key=lambda g: (_next_after(future, g, t, horizon), g)))
            held.append(answer)

    flat: list[int] = list(d0) + [a for p in d1 for a in (p.left, p.right)]
    future: dict[int, list[int]] = {}
    for t, answer in enumerate(flat):
        future.setdefault(answer, []).append(t)
    held: list[int] = []
    p0, p1 = Phase(), Phase()
    t = 0
    for answer in d0:
        p0.served += 1
        p0.correct += 1
        serve(answer, p0, held, future, t, len(flat))
        t += 1
        b = len(held) * FACT_BITS + len(chosen) * RULE_BITS
        p0.bit_steps += b
        p0.peak_bits = max(p0.peak_bits, b)
    for pair in d1:
        p1.served += 1
        p1.correct += 1
        for answer in (pair.left, pair.right):
            serve(answer, p1, held, future, t, len(flat))
            t += 1
        p1.compose_work += COMPOSE_COST
        b = len(held) * FACT_BITS + len(chosen) * RULE_BITS
        p1.bit_steps += b
        p1.peak_bits = max(p1.peak_bits, b)
    store.facts = list(held)
    return store, p0, p1


def _next_after(future: dict[int, list[int]], answer: int, t: int, horizon: int) -> int:
    for u in future.get(answer, ()):
        if u > t:
            return u
    return horizon


#: The four DEV-D8 arms, plus one arm declared as a DIAGNOSTIC rather than a
#: control: ``CONTINUED_OCM_UNVERIFIED`` exists only to price the check, and its
#: correctness is below 1.0 by construction, so it is INADMISSIBLE for any work
#: comparison and the receipt says so wherever it appears.
ARM_ROLES = {
    "CONTINUED_OCM": "MACHINE",
    "RESET_OCM": "CONTROL_DECISIVE",
    "STRONG_ADAPTIVE_PARENT": "CLAIRVOYANT_PARENT",
    "TASK_SPECIFIC_OCM": "GENERALITY_BOUND",
    "CONTINUED_OCM_UNVERIFIED": "DIAGNOSTIC_INADMISSIBLE",
}
