"""DEV-1: one real D0 to D1 transition, in the only economy where carrying state can pay.

Issue #151 asks for a persistent OCM lineage that carries earned competence
across developmental stages, and asks the one question that makes such a claim
developmental rather than merely cumulative:

    the decisive question is not whether the older machine scores higher, it is
    whether prior developmental experience causally made the next competence
    cheaper

``spine.py`` reported that the repository supported ZERO complete transitions.
This module builds the first one.  It can only be built now, and the reason
matters more than the build: until E10 (``research/cognitive-ladder/retain.py``)
every world in this programme gave retention away for free and without bound,
and in such a world the optimal policy is provably to carry nothing.  A
developmental lineage measured there is a lineage whose central proposition is
arithmetically excluded before the first episode runs.  E10 bounded retention in
bits and priced it, and the sign of the comparison reversed.  DEV-1 is that
economy with a developmental boundary drawn through it.

The two stages
--------------

``D0`` -- *basic exact interaction*.  A stream of single demands.  Serve each
one exactly.  This is E10's world and the D0 arms behave exactly as E10's arms
did, which is deliberate: the D0 phase must not be a new experiment quietly
smuggled in as a premise.

``D1`` -- *composition, failure and scope*.  Three things D0 never asked for:

    COMPOSITION   a demand for a pair drawn from two different rules, which must
                  both be answered and then combined.  Composition depth 2.
    SCOPE         some pair members are EXCEPTIONS: answers that look like they
                  belong to a rule's extension and are not generated by it.  An
                  arm that applies a held rule without checking gets the answer
                  WRONG.
    FAILURE       an arm may pay ``VERIFY_COST`` to check scope before applying,
                  or refuse to apply and derive instead.

Scope is what stops this from being a caching experiment with extra steps.  In
D0 every arm was correct by construction and work was the only free coordinate.
In D1 correctness is a coordinate again, and it moves in the direction that is
DANGEROUS for the hypothesis: carrying rules from D0 is what creates the
opportunity for harmful transfer.  The arm with the most prior competence has
the most ways to be confidently wrong, and the receipt reports negative transfer
and harmful-transfer refusals as first-class fields rather than as caveats.

The four arms DEV-D8 requires
-----------------------------

``CONTINUED_OCM``          runs D0, keeps its store, runs D1.
``RESET_OCM``              runs D0, DISCARDS its store, runs D1.  Identical
                           architecture, identical D1 information.  It is the
                           only control that separates "prior experience made
                           this cheaper" from "D1 is just cheap".
``STRONG_ADAPTIVE_PARENT`` sees D0 and D1 concatenated AND the entire future,
                           and keeps the mixed instance/rule set that a
                           clairvoyant would keep.  Strictly more information
                           than the lineage, on purpose.
``TASK_SPECIFIC_OCM``      never sees D0 and never learns base rules; it acquires
                           COMPOSITE rules directly from D1, which is what a
                           system built for this stage alone would do.  It bounds
                           how much of any CONTINUED gain is generality rather
                           than a head start on the right objects.

What is reported, and what would refute it
------------------------------------------

Two work figures, never one:

    D1_ONLY     the developmental question -- given the lineage exists, is the
                next competence cheaper?
    LIFETIME    D0 + D1 -- did the lineage pay for itself?

A machine can win the first and lose the second, and if it does, that is the
result and it is reported as the result.  ``cheaper_because`` is a required
field: the D1 saving must be attributable to identified reused objects with
execution witnesses, not merely correlated with having a store.

The kill criterion is registered before execution: if ``CONTINUED_OCM`` does not
beat ``RESET_OCM`` on D1-only work at matched correctness, there is no D0 to D1
transition here, and the first entry in the developmental spine is a refusal.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "cognitive-ladder"))

from prereg import Commitment, commit
from retain import (APPLY_COST, DERIVE_COST, FACT_BITS, INDUCE_COST, K_INDUCE,
                    LOOKUP_COST, RULE_BITS, World, build_world, demand_stream)

__all__ = ["DEV1_PLAN", "COMMITMENT", "Pair", "D1World", "build_d1_world",
           "d1_stream", "VERIFY_COST", "COMPOSE_COST", "EXCEPTION_RATE",
           "COMPOSITE_BITS"]


#: Cost to check whether a held rule actually generates a given answer.  Cheaper
#: than deriving and dearer than applying, so that checking is a real decision
#: rather than a free action or an unaffordable one.
VERIFY_COST: int = 25

#: Cost to combine two answers once both are in hand.  Charged to every arm
#: identically, so it cannot separate them; it is here because a composition
#: that costs nothing is not a composition.
COMPOSE_COST: int = 5

#: Fraction of answers that are EXCEPTIONS: inside a rule's nominal extension and
#: not generated by it.  An arm applying the rule to one of these is WRONG.
EXCEPTION_RATE: float = 0.10

#: Bits to hold one composite rule.  A composite names two base rules and the
#: way they combine, so it is dearer than either.
COMPOSITE_BITS: int = 48


DEV1_PLAN: Mapping[str, Any] = {
    "study_id": "DEV1_D0_TO_D1_V1",
    "programme": "SzeChunYiu/ORION-OCM#151",
    "constitution": "SzeChunYiu/ORION-OCM#144",
    "depends_on": "results/RETAIN_E10_V1.json",
    "scientific_question": (
        "Does prior D0 competence, carried across a stage boundary under a bounded and "
        "priced store, causally make D1 competence cheaper -- at matched correctness, and "
        "against a reset arm with the same architecture and the same D1 information?"
    ),
    "evidence_class": "E2",
    "contribution_level": "L1",
    "decisive_causal_question": (
        "CONTINUED_OCM versus RESET_OCM. The two are the same code, the same budget, the "
        "same D1 stream, and the same immutable architecture. They differ in exactly one "
        "bit: whether the D0 store crosses the boundary. Any D1 work difference between "
        "them is caused by the crossing or by nothing."
    ),
    "strongest_parent_attack": (
        "STRONG_ADAPTIVE_PARENT sees D0 and D1 concatenated and the entire future demand "
        "stream, and keeps the mixed instance-and-rule set a clairvoyant would keep. It has "
        "strictly more information than the lineage. E10 already established that the arm "
        "does NOT beat this parent, and DEV-1 does not expect to either; the parent is here "
        "to bound the claim, not to be beaten."
    ),
    "prior_information_audit": {
        "CONTINUED_OCM": "its own D0 store, earned by paying for every derivation in it",
        "RESET_OCM": "nothing from D0; identical architecture and identical D1 stream",
        "STRONG_ADAPTIVE_PARENT": "D0 and D1 and the whole future",
        "TASK_SPECIFIC_OCM": "D1 only, and a representation chosen for D1's composites",
        "exceptions": "no arm is told which answers are exceptions; every arm may pay "
                      "VERIFY_COST to find out, and every arm is charged the same for it",
    },
    "capability_gate": (
        "D1 correctness is NOT 1.0 by construction -- an arm that applies a rule to an "
        "exception answers wrongly. Work is compared only between arms at matched "
        "correctness, and where correctness differs the comparison is reported as "
        "INADMISSIBLE rather than as a win. This is the first experiment in the programme "
        "where the gate can actually bind on the machine under test."
    ),
    "scaling_relevance": (
        "D1 length and store budget are both swept. The developmental claim is that the "
        "D1-only advantage does not vanish as D1 grows, because a reset arm eventually "
        "re-earns everything; if the advantage decays to zero the transition is a "
        "STARTUP EFFECT and must be reported as one."
    ),
    "predictions_frozen_before_execution": {
        "Q1": "CONTINUED_OCM beats RESET_OCM on D1-only work at matched correctness.",
        "Q2": ("The advantage is attributable: the reused base rules that fire in D1 are "
               "named, and removing them from the carried store removes the advantage."),
        "Q3": ("CONTINUED_OCM does NOT beat STRONG_ADAPTIVE_PARENT, which sees the future. "
               "If it does, the parent is implemented wrongly and the run is void."),
        "Q4": ("CONTINUED_OCM's advantage over RESET_OCM SHRINKS as D1 lengthens, because a "
               "reset arm re-earns the same rules. Registered in this direction so that a "
               "shrinking advantage is a confirmed prediction and not a discovered excuse."),
        "Q5": ("Carrying state carries risk: CONTINUED_OCM's harmful-transfer exposure is at "
               "least RESET_OCM's, because it holds more rules to misapply. If it is lower, "
               "the exception mechanism is not biting and the run is uninformative."),
    },
    "kill_criterion": (
        "If CONTINUED_OCM does not beat RESET_OCM on D1-only work at matched correctness, "
        "there is no D0 to D1 transition here. The spine's first entry is then a REFUSAL, "
        "recorded with the same weight as a success would have been."
    ),
    "costs": {
        "derive": DERIVE_COST, "apply": APPLY_COST, "lookup": LOOKUP_COST,
        "induce": INDUCE_COST, "verify": VERIFY_COST, "compose": COMPOSE_COST,
        "k_induce": K_INDUCE, "fact_bits": FACT_BITS, "rule_bits": RULE_BITS,
        "composite_bits": COMPOSITE_BITS, "exception_rate": EXCEPTION_RATE,
    },
    "sweep": {
        "rule_count": 16,
        "extension": 16,
        "d0_length": 2000,
        "d1_lengths": [250, 1000, 4000],
        "budget_bits": [256, 1024],
        "skew": 1.0,
        "reps": 8,
        "sigmas": [0.0, 0.001, 0.01, 0.1],
    },
    "why_extension_16": (
        "E10 located the compressibility crossover at extension 16 and the D0 economy here "
        "is E10's economy unchanged. Running the transition BELOW the crossover would test "
        "whether a lineage helps in a world where keeping anything is already a mistake, "
        "which is a question with a known answer. This is a choice made for a stated reason "
        "and it bounds the result: DEV-1 says nothing about incompressible domains."
    ),
    "what_this_does_not_establish": (
        "One transition, on one synthetic stage pair, with disjoint uniform rules and "
        "error-free induction. D1 is authored to require composition, so the fact that "
        "composition helps is a property of the authored stage and not a discovery. What is "
        "NOT authored is whether carrying the store beats re-earning it, which is the only "
        "thing being measured. Nothing here speaks to D1 to D2 or to any later transition, "
        "and one completed transition does not make a developmental lineage."
    ),
    "novelty": (
        "NONE CLAIMED. Curriculum and transfer learning own the question of whether earlier "
        "training makes later training cheaper; catastrophic forgetting and negative "
        "transfer own the risk side. The contribution is the RECEIPT DISCIPLINE -- a reset "
        "arm, a clairvoyant parent, a task-specific bound, attributable reuse witnesses, and "
        "a registered kill criterion -- applied to a transition that is otherwise ordinary."
    ),
}

COMMITMENT: Commitment = commit(DEV1_PLAN)


@dataclass(frozen=True)
class Pair:
    """One D1 demand: two answers from two different rules, to be combined."""

    left: int
    right: int


@dataclass(frozen=True)
class D1World:
    """D0's world, plus the exceptions that make scope a real question."""

    base: World
    #: Answers that are inside a rule's nominal extension and NOT generated by it.
    exceptions: frozenset[int]

    @property
    def rule_of(self) -> tuple[int, ...]:
        return self.base.rule_of

    @property
    def members(self) -> tuple[tuple[int, ...], ...]:
        return self.base.members

    @property
    def rule_count(self) -> int:
        return self.base.rule_count

    def generated_by_rule(self, answer: int) -> bool:
        """False for exceptions: applying a rule to one of these gives a wrong answer."""
        return answer not in self.exceptions


def build_d1_world(rule_count: int, extension: int, rate: float,
                   rng: random.Random) -> D1World:
    base = build_world(rule_count, extension)
    exceptions = set()
    for r in range(rule_count):
        for f in base.members[r]:
            if rng.random() < rate:
                exceptions.add(f)
    return D1World(base, frozenset(exceptions))


def d1_stream(world: D1World, horizon: int, skew: float,
              rng: random.Random) -> tuple[Pair, ...]:
    """Pairs drawn from two DIFFERENT rules, so every D1 demand is a composition."""
    singles = demand_stream(world.base, horizon * 2, skew, rng)
    out: list[Pair] = []
    i = 0
    while len(out) < horizon and i + 1 < len(singles):
        a, b = singles[i], singles[i + 1]
        if world.rule_of[a] != world.rule_of[b]:
            out.append(Pair(a, b))
            i += 2
        else:
            i += 1
    while len(out) < horizon:
        a = rng.randrange(world.base.answers)
        b = rng.randrange(world.base.answers)
        if world.rule_of[a] != world.rule_of[b]:
            out.append(Pair(a, b))
    return tuple(out)
