"""Guarded rules: paying bits instead of a check, and the condition under which that works.

This module is ``DEV-3``.  It exists because ``DEV2_CONTINUAL_PARENTS_V1`` did
not merely beat the lineage, it said exactly why, by pricing the reason:

    a held rule licenses a scope CHECK, never an answer, so using one costs
    VERIFY + APPLY where a stored answer costs LOOKUP.  Sweeping the check price
    on identical worlds flips the sign between 10 and 25, with replay's own work
    constant throughout.  Rules are cheaper to ACQUIRE and much dearer to USE.

The tempting response is to make the check cheap and declare a win.  That is
precisely what publication constitution section 11 forbids -- making the
environment one in which explicit reuse is optimal by construction -- and the
sweep in DEV-2 already reports what happens at every check price, so nothing
would be learned by fixing one.

The principled response is a REPRESENTATION change: a rule that carries its own
scope precondition.  A guarded rule costs more BITS and no per-use check.  It
competes for the same budget against the same replay parent, so if it wins it
wins by being a better thing to hold, not by being charged less to hold it.

The reason this might be impossible, stated before it is attempted
-----------------------------------------------------------------

A guard is only useful if it is SOUND: an arm that skips verification on the
strength of a guess is not cheaper, it is wrong, and the capability gate throws
it out.  And in DEV-1's world, soundness looks unaffordable:

    exceptions are drawn independently per answer, so the only sound guard is
    the exception LIST, and learning that list requires deriving every member of
    the extension -- which costs exactly what memoizing the extension costs

If that is the whole story then guarded rules cannot win here, and DEV-3's
result is an impossibility rather than an experiment.  That would be worth
reporting, and it is registered as a possible outcome rather than discovered as
a disappointment.

What makes it a question rather than a theorem is that the argument depends on
the exceptions being STRUCTURELESS.  If exceptions are generated by a rule of
their own, the guard is a small predicate rather than a list, and it is learnable
from a few observations.  So the experiment is not "do guards work" -- it is:

    **a guard pays exactly when the exception set is itself compressible**

which is the same condition the acquired structure had to meet, applied one level
up.  That recursion is the interesting claim and it is the one under test.

The two exception regimes
-------------------------

``RANDOM``      exceptions are placed at random, in EXACTLY the number the
                structured world of the same replicate has.  No predicate in the
                guard language covers them, the version space empties, and the
                arm must fall back to verifying every application.  This regime
                is the ANTI-RIGGING CONTROL: it must reproduce DEV-2's result,
                with replay beating the lineage. If it does not, the harness is
                not DEV-1's and the run is void.  Matching the COUNT rather than
                a rate matters: the structured draw yields about 35 per cent
                exceptions and an independent 10 per cent rate yields 11, so an
                unmatched control would have let a rate difference masquerade as
                a structure effect, in the direction that flatters the guard.
``STRUCTURED``  exceptions are the answers whose within-rule index satisfies
                ``index % period == phase``, for a period and phase drawn per
                rule.  The guard language contains this family, so a sound guard
                exists and is small.

Soundness without a gift
------------------------

The arm is NOT told which regime it is in and is not told any rule's guard.  It
holds a version space over the guard language and may skip verification only
when that version space is a SINGLETON.  Since the truth is always consistent
with the observations, a singleton version space provably contains the truth, so
skipping is sound rather than lucky, and correctness stays at 1.0 by
construction rather than by hope.  Under RANDOM exceptions the version space
empties instead, the arm detects that it has no guard and verifies for ever,
which is the honest failure mode and is also how it reproduces DEV-2.

The gift that IS taken, declared: the guard language contains the truth in the
STRUCTURED regime.  This is the same gift E6 declared when it gave each method
its candidate evidence set -- which predicate is right is discovered, that the
right one is expressible is given.  A world where the guard language must also
be learned is a different and larger experiment, and it can only make the arm's
position worse.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "cognitive-ladder"))

from dev1 import COMPOSE_COST, D1World, EXCEPTION_RATE, Pair, VERIFY_COST, d1_stream
from prereg import Commitment, commit
from retain import FACT_BITS, RULE_BITS, build_world

__all__ = ["DEV3_PLAN", "COMMITMENT", "GUARD_BITS", "GUARD_PERIODS", "guard_candidates",
           "build_structured_world", "build_random_world", "REGIMES", "Guard"]


#: Bits to hold a guard alongside its rule.  A guard names a period and a phase,
#: so it is small and constant -- and it is charged against the SAME budget the
#: replay parent spends on answers, which is what makes the comparison fair. Two
#: fact-slots: a guarded rule costs RULE_BITS + GUARD_BITS = six answer slots.
GUARD_BITS: int = 16

#: The guard language: ``index % period == phase``, plus the empty guard.
GUARD_PERIODS: tuple[int, ...] = (2, 3, 4, 5)


@dataclass(frozen=True)
class Guard:
    """``None`` period means 'this rule has no exceptions'."""

    period: int | None
    phase: int

    def excludes(self, index: int) -> bool:
        return self.period is not None and index % self.period == self.phase


def guard_candidates() -> tuple[Guard, ...]:
    out = [Guard(None, 0)]
    for period in GUARD_PERIODS:
        for phase in range(period):
            out.append(Guard(period, phase))
    return tuple(out)


def build_structured_world(rule_count: int, extension: int,
                           rng: random.Random) -> tuple[D1World, dict[int, Guard]]:
    base = build_world(rule_count, extension)
    truth: dict[int, Guard] = {}
    exceptions: set[int] = set()
    for r in range(rule_count):
        period = rng.choice(GUARD_PERIODS + (None,))
        phase = rng.randrange(period) if period else 0
        guard = Guard(period, phase)
        truth[r] = guard
        for index, answer in enumerate(base.members[r]):
            if guard.excludes(index):
                exceptions.add(answer)
    return D1World(base, frozenset(exceptions)), truth


def build_random_world(rule_count: int, extension: int, exception_count: int,
                       rng: random.Random) -> tuple[D1World, dict[int, Guard]]:
    """Exactly ``exception_count`` exceptions, placed at random.

    The count is MATCHED to the structured world of the same replicate rather
    than drawn from a rate. Without that the two regimes would differ in how
    MANY exceptions there are as well as in whether they have structure, and a
    sign change could be attributed to the rate -- the structured draw produces
    about 35 per cent exceptions against an independent rate's 11, so the
    confound is large and in the direction that would have flattered the guard.
    """
    base = build_world(rule_count, extension)
    answers = [a for r in range(rule_count) for a in base.members[r]]
    rng.shuffle(answers)
    return D1World(base, frozenset(answers[:exception_count])), {}


REGIMES = ("RANDOM", "STRUCTURED")


DEV3_PLAN: Mapping[str, Any] = {
    "study_id": "DEV3_GUARDED_RULES_V1",
    "programme": "SzeChunYiu/ORION-OCM#151",
    "doctrine": "PR #150 PARENT_SYNTHESIS_DOCTRINE_V0_2.md",
    "responds_to": "results/DEV2_CONTINUAL_PARENTS_V1.json",
    "scientific_question": (
        "DEV-2 showed the lineage loses to experience replay because a rule is dearer to "
        "USE than a stored answer, by exactly the price of its scope check. Does a rule "
        "that carries its own precondition -- paying BITS instead of a per-use check, from "
        "the same budget -- beat replay? And under what condition on the world?"),
    "evidence_class": "E2",
    "contribution_level": "L1",
    "the_claim_under_test": (
        "A guard pays exactly when the exception set is itself compressible. That is the "
        "same condition the acquired structure had to meet, applied one level up, and it "
        "predicts a SIGN CHANGE between two regimes of the same world rather than a win."),
    "decisive_causal_question": (
        "The exception regime is the only knob. Under RANDOM exceptions no guard in the "
        "language is sound, the version space empties, and the arm must verify for ever. "
        "Under STRUCTURED exceptions a small sound guard exists. Everything else -- the "
        "streams, the budget, the parents, the costs -- is identical, so a sign change "
        "between the two regimes is caused by exception structure or by nothing."),
    "strongest_parent_attack": (
        "REPLAY_ONLY_PARENT, which beat the lineage in DEV-2 at five of six settings and by "
        "1.57x at the loose budget. It is unchanged here, it runs the same streams at the "
        "same budget, and it does not care about exception structure at all -- a stored "
        "answer is correct whether or not its rule would have been."),
    "anti_rigging_control": (
        "The RANDOM regime must REPRODUCE DEV-2: replay beats the guarded arm, because the "
        "arm degenerates to DEV-1's unguarded lineage when no guard is learnable. If the "
        "guarded arm wins under RANDOM exceptions, it is skipping checks it has not earned, "
        "the correctness gate should have caught it, and the run is VOID. Section 11 of the "
        "constitution is the reason this control exists: the way to fake this result is to "
        "build only the world where guards work."),
    "prior_information_audit": {
        "guarded_arm": "the guard LANGUAGE, not any guard. Which predicate holds for a rule "
                       "is discovered from derivations it already paid for; that the right "
                       "predicate is expressible is given, and under RANDOM exceptions it "
                       "is not expressible and the arm must find that out too",
        "unguarded_lineage": "DEV-1's arm exactly, unchanged",
        "REPLAY_ONLY_PARENT": "DEV-2's parent exactly, unchanged",
        "regime": "NO ARM IS TOLD WHICH REGIME IT IS IN",
    },
    "capability_gate": (
        "An arm may skip verification only when its version space over the guard language "
        "is a SINGLETON. The truth is always consistent with the observations, so a "
        "singleton provably contains it and skipping is sound. Correctness is asserted to "
        "be 1.0 for every arm in every regime; an arm below it is inadmissible and its work "
        "figure is not quoted."),
    "predictions_frozen_before_execution": {
        "G0": ("The two regimes have the SAME number of exceptions in every replicate, by "
               "construction, so nothing below can be a rate effect. Asserted, not assumed."),
        "G1": ("RANDOM regime: REPLAY_ONLY_PARENT beats the guarded arm, reproducing DEV-2. "
               "This is the control and a failure here voids the run."),
        "G2": ("STRUCTURED regime: the guarded arm beats REPLAY_ONLY_PARENT at the loose "
               "budget, because a sound guard removes the per-use check that DEV-2 priced "
               "as the cause."),
        "G3": ("The guarded arm beats the UNGUARDED lineage in the STRUCTURED regime and "
               "ties it in the RANDOM regime, since with no learnable guard it degenerates "
               "to the same policy."),
        "G4": ("Correctness is 1.0 for every arm in both regimes. A guarded arm that is "
               "ever wrong has skipped a check it had not earned."),
        "G5": ("The guarded arm's advantage appears only INSIDE the analytic window and is "
               "absent below 768 bits and at or above 2048. If it appears outside the "
               "window the window is not the explanation and the receipt says so."),
        "G6": ("The advantage is at least as large at skew 0.0 as at skew 1.0. Uniform "
               "demand is the worst case for any cache, so it is where coverage -- what a "
               "rule has and a buffer does not -- should matter most. A result that needs a "
               "skewed stream is a result in a convenient world."),
    },
    "kill_criterion": (
        "If the guarded arm does not beat REPLAY_ONLY_PARENT in the STRUCTURED regime, then "
        "removing the per-use check is not sufficient to make abstraction pay, DEV-2's "
        "explanation is incomplete, and this lane has no carry advantage under any "
        "representation it has tried. That is to be reported in those words."),
    "pilot_disclosure": (
        "A one-replicate pilot preceded this plan and did three things worth recording. It "
        "showed the guarded arm LOSING everywhere at the budgets DEV-1 and DEV-2 used. It "
        "then showed why, and the cause was an arm defect rather than a fact about guards: "
        "at 1024 bits the arm learned all sixteen guards during D0, filled the rest of the "
        "budget with facts, evicted every guard to fit them, and paid to verify 1958 of "
        "2000 member demands -- an arm holding sixteen sound guards and using none. The "
        "policy is corrected here so that a guard is admitted with its rule and discarded "
        "only with its rule; guards are charged exactly what they were charged before. And "
        "it showed that budgets at or above 2048 bits are DEGENERATE, because the whole "
        "answer space fits in the replay buffer and memoization wins by arithmetic. The "
        "budget grid below is derived from that arithmetic rather than searched, and the "
        "protected sweep runs on a seed disjoint from the pilot."),
    "analytic_budget_window": (
        "The comparison is informative only between two computable bounds. Below "
        "rule_count * (RULE_BITS + GUARD_BITS) = 768 bits the arm cannot hold its rules and "
        "their guards at all. At or above rule_count * extension * FACT_BITS = 2048 bits "
        "the replay parent holds the ENTIRE answer space and serves everything at LOOKUP, "
        "so it wins by arithmetic and nothing is being compared. Both bounds are computed "
        "from the registered constants, they are asserted in the tests, and the grid spans "
        "the window AND both sides of it so that the degenerate regions are visible in the "
        "table rather than excluded from it."),
    "sweep": {
        "rule_count": 16,
        "extension": 16,
        "d0_length": 2000,
        "d1_lengths": [250, 1000, 4000],
        "budget_bits": [256, 512, 1024, 1536, 2048],
        "skews": [0.0, 1.0],
        "reps": 8,
        "regimes": list(REGIMES),
        "random_exception_count": (
            "matched per replicate to the structured world's realised count, not drawn "
            "from a rate"),
    },
    "costs": {"guard_bits": GUARD_BITS, "rule_bits": RULE_BITS, "fact_bits": FACT_BITS,
              "verify": VERIFY_COST, "compose": COMPOSE_COST,
              "guard_language_size": len(guard_candidates())},
    "what_this_does_not_establish": (
        "The guard language is given and contains the truth in one of the two regimes. A "
        "world where the language must also be learned is larger and can only be worse for "
        "the arm. Exceptions are either fully structured or fully unstructured; the "
        "interesting real case is partial structure and is not run. One stage pair, "
        "disjoint uniform rules, error-free induction, stationary streams."),
    "novelty": (
        "NONE CLAIMED. Preconditions on reusable abstractions are program synthesis and "
        "contract programming; version-space learning of a predicate is Mitchell 1982. The "
        "contribution is the regime comparison and the control that requires the "
        "unstructured regime to reproduce the earlier loss."),
}

COMMITMENT: Commitment = commit(DEV3_PLAN)
